- libs/core/buttons.cpp
- libs/core/input.cpp
- libs/core/pins.h
Missing pin definition to compile against BOARD_ID_ZERO
> Fix pin layout for BOARD_ID_ZERO

- libs/core/_locales/core-jsdoc-strings.json
- libs/core/pxt.cpp
Using sensor data to seed random generator
> better seed selection using sensor data

- libs/lightsensor/lightsensor.cpp
- libs/lightsensor/test.ts
- libs/microphone/microphone.cpp
- libs/music/music.ts
Remove light/microphone as buttons (confusing)
> Simplebuttons

- libs/core/test.ts
- libs/light/neopixel.ts
The pin ``D13`` is clearly printed on the board so let's use that instead.
> removed LED from devpins

- libs/core/pins.cpp
- libs/core/shims.d.ts
- libs/light/docs/reference/light/default-pin.md
- libs/light/neopixel.ts
Makes it easier to use digital read values in conditionals.
https://github.com/Microsoft/pxt/issues/2068
> use booleans in digital read/write signature

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/docs/reference/input/acceleration.md
- libs/accelerometer/docs/reference/input/on-gesture.md
- libs/accelerometer/docs/reference/input/rotation.md
- libs/accelerometer/docs/reference/input/set-accelerometer-range.md
- libs/accelerometer/shims.d.ts
- libs/core/docs/reference/input.md
> Acceleration input docs

- libs/core/control.cpp
- libs/core/pxt.cpp
- libs/core/pxt.h
- libs/light/neopixel.ts
- package.json
Support for an internal animation queue for neopixels
> Animationqueue

- libs/core/docs/reference/input.md
- libs/temperature/docs/reference/input/on-temperate-condition-changed.md
- libs/temperature/docs/reference/input/on-temperature-condition-changed.md
- libs/temperature/docs/reference/input/temperature.md
- libs/temperature/shims.d.ts
- libs/temperature/temperature.cpp
* on-termperate-condition.md is no more
> Add and update temperature docs

- libs/core/buttons.cpp
- libs/core/docs/reference/input/is-pressed.md
- libs/core/docs/reference/input/was-pressed.md
* isPressed.md
* wasPressed.md
* soDepressed.md, not really
> Pressing buttons docs

- libs/core/docs/reference/input.md
- libs/microphone/docs/reference/input/on-sound-condition-changed.md
- libs/microphone/docs/reference/input/sound-level.md
* soundLevel added to input.md
* added onSoundLevelChanged
> Add and update the sound docs

- libs/core/docs/reference/input.md
- libs/lightsensor/docs/reference/input/light-level.md
- libs/lightsensor/docs/reference/input/on-light-condition-changed.md
> light sensor docs

- libs/music/docs/reference/music.md
- libs/music/docs/reference/music/beat.md
- libs/music/docs/reference/music/note-frequency.md
- libs/music/docs/reference/music/play-tone.md
- libs/music/docs/reference/music/rest.md
- libs/music/docs/reference/music/ring-tone.md
- libs/music/docs/reference/music/set-tempo.md
- libs/music/docs/reference/music/tempo.md
> Music docs 02

- libs/accelerometer/accelerometer.cpp
Requires https://github.com/lancaster-university/codal/pull/21
> Correct orientation of accelerometer data

- libs/light/neopixel.ts
Reordered the API 
1. Action API come first
2. Color get API next
3. Neopixel centric api last
@pelikhan take a look
> Rearrange More.. API

- libs/light/neopixel.ts
- support for "show animation frame"
- support for custom animation in typescript
> refactoring animations to support custom animation, render single frame

- libs/core/docs/reference/input.md
- libs/light/docs/reference/light/brightness.md
- libs/light/docs/reference/light/clear.md
- libs/light/docs/reference/light/colors.md
- libs/light/docs/reference/light/hsv.md
- libs/light/docs/reference/light/rgb.md
- libs/light/neopixel.ts
- libs/microphone/docs/reference/input/on-loud-sound.md
- libs/microphone/docs/reference/input/sound-level.md
* add some light docs
* update some others
* put in on-sound-loud
> Add/update more 'light' docs

- libs/core/docs/reference/loops/forever.md
- libs/core/docs/reference/loops/pause.md
* These are the 'loop' namespace methods
* The get pasted in with the for, while, and repeat blocks but are
pathed from /reference/loops in the card render.
> Add 'forever' and 'pause' topics

- libs/core/docs/reference/pins/analog-read.md
- libs/core/docs/reference/pins/analog-write.md
- libs/core/docs/reference/pins/digital-write.md
* add analog read/write topics. Might expand these as I keep going.
> More 'pins' topics

- libs/core/docs/reference/pins/set-pull.md
* a try at describing this in kid speak.
> Add 'set pull' topic

- libs/core/pxt.h
- libs/touch/touch.cpp
This depends on https://github.com/lancaster-university/codal/pull/26 - only merge after that one is merged
> Add support for hardware cap-touch

- libs/music/melodies.ts
> Add siren sound to the list of build in sounds. 

- libs/music/music.ts
Because of https://github.com/Microsoft/pxt/pull/2235
> Set decompile literals flag

- libs/core/core.cpp
- libs/core/hf2.cpp
- libs/core/pxt.cpp
- libs/core/pxt.h
This fixes https://github.com/Microsoft/pxt/issues/2199 and https://github.com/Microsoft/pxt-adafruit/issues/167.
There's a supporting PXT PR: https://github.com/Microsoft/pxt/pull/2250 , which also adds some docs
> Unify ref counting for RefCounted and RefObject

- libs/core/core.cpp
- libs/core/math.ts
- libs/light/neopixel.ts
- package.json
Requires https://github.com/Microsoft/pxt/pull/2292
> support for log,exp,sin,cos,tan,asin,acos,atan,atan2

- libs/core/core.cpp
- libs/core/test.ts
- libs/light/neopixel.ts
- package.json
https://github.com/Microsoft/pxt/pull/2337
> Moving to JS random

- libs/core/pxt.cpp
Part of the fix for https://github.com/Microsoft/pxt/issues/2461
> Fixing array pop

- libs/core/pins.h
- libs/light/neopixel.cpp
As per this change: https://github.com/Microsoft/uf2-samd21/commit/2f1ce04fbb3d0fb380d67d01e9833fa706ff7e93
> Fixing neopixel configuration for metro express board

- libs/light/neopixel.cpp
I had an error in my earlier PR that got covered up because I redefined neopixel.cpp in the target. This should fix it.
> Fixing location of metro fix

- libs/infrared/docs/reference/network.md
- libs/infrared/docs/reference/network/infrared-send-number.md
- libs/infrared/docs/reference/network/on-infrared-packet-received.md
- libs/infrared/ir.ts
> Add some 'infrared' docs.

- libs/base/pxt.cpp
https://github.com/Microsoft/pxt/issues/3093
> Remove some dead code; Remove decr() in removeAt()

- libs/touch/pxt.json
- libs/touch/sim/touch.ts
- libs/touch/touch.cpp
- libs/touch/touch.h
- libs/touch/touch.ts
Support for set threshold and reading live capacitive value from touch button
> support for threshold/value blocks for touch buyttons

- libs/accelerometer/accelerometer.cpp
- libs/base/loops.cpp
- libs/base/math.ts
- libs/base/ns.ts
- libs/base/serial.cpp
- libs/buttons/buttons.cpp
- libs/core/i2c.ts
- libs/core/ns.ts
- libs/core/pins.cpp
- libs/core/pins.ts
- libs/lightsensor/lightsensor.cpp
- libs/microphone/microphone.cpp
- libs/music/melodies.ts
- libs/music/music.cpp
- libs/music/music.ts
- libs/music/ns.ts
- libs/switch/switch.cpp
- libs/thermometer/temperature.cpp
- libs/touch/touch.cpp
Lights: 
- I haven't made any changes yet since we still need to discuss how we're going to refactor the complex APIs perhaps into a package, and make it all work together.
Input:
Music:
Note: I made the set Tone block hidden, block usage on that was extremely low, and given it's complex usage I'm not convinced it needs to be a block.
Math: 
Pins:
Serial:
> Refactor blocks to remove subcategories, and order some in groups.

- libs/core/pins.cpp
- libs/servo/README.md
- libs/servo/pxt.h
- libs/servo/servo.cpp
Refactor servo blocks into their own package
> Create a servo package

- libs/core/control.cpp
- libs/core/enums.d.ts
- libs/core/shims.d.ts
fixes https://github.com/Microsoft/pxt-adafruit/issues/219
> Remove useless mode parameter to control.raiseEvent

- libs/core/pins.h
Removing double-click, hold until tested on HW
> hide double click and hold until better test

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/axis.h
- libs/buttons/buttons.cpp
- libs/core/codal.cpp
- libs/core/hf2.cpp
- libs/core/hf2dbg.h
- libs/core/i2c.cpp
- libs/core/pins.cpp
- libs/lightsensor/lightsensor.cpp
- libs/switch/switch.cpp
Build available here https://makecode.adafruit.com/app/2665d3163fd760e170a4b5eee9f552694921916a-b211c34609
> Switching to newest codal (CPX v1.2.2)

- libs/light/neopixeloverrides.ts
- libs/light/pxt.json
> add overrides placeholder

- libs/buttons/buttons.cpp
Adding trackArgs, and renaming to buttons instead of buttonpair
> Update button annotations to support breadboarding

- libs/cable/pxt.json
Add cable image. The image lives in the target though
> Add cable package image

- libs/buttons/buttons.cpp
- libs/core/pins.h
I think this got left behind in a refactoring a while back.
> Moving button events enum to buttons package

- libs/base/loops.cpp
Fixes https://github.com/Microsoft/pxt-adafruit/issues/444
> Fix upgrade issue with the pause block

- libs/switch/sim/switch.ts
- libs/switch/switch.cpp
Fixes https://github.com/Microsoft/pxt-adafruit/issues/224
> Revert switch trigger on start.

- libs/base/control.ts
- libs/light/neopixel.ts
This allows to create smooth animation even when using a duration
> use last renderer to generate smooth animations

- libs/microphone/microphone.cpp
Using a logarithmic scale for sound level. Works great with clapping now.
> Tuning and scaling of sound level values.

- libs/cable/docs/reference/network.md
- libs/infrared/docs/reference/network.md
Sorry, should've included this in #171.
> Fix 'network' base card pages

- libs/base/serial.ts
- libs/light/neopixel.ts
> jet color map for graph

- libs/light/docs/reference/light.md
- libs/light/docs/reference/light/show-animation.md
- libs/light/docs/reference/light/sparkle-animation.md
- libs/light/docs/reference/light/stop-all-animations.md
- libs/light/docs/reference/light/theatre-chase-animation.md
> Fix showAnimation in docs

- libs/accelerometer/accelerometer.cpp
- libs/buttons/buttons.cpp
- libs/lightsensor/lightsensor.cpp
- libs/microphone/microphone.cpp
- package-lock.json
> Increasing the block gap in input category

- libs/base/docs/reference/console.md
- libs/base/docs/reference/console/log-value.md
- libs/base/docs/reference/console/log.md
- libs/base/docs/reference/serial/write-line.md
Add a card page and do some small edits.
Are we tagging package `base`?
> Small edits to console docs

- libs/light/docs/reference/light/neopixelstrip/show-animation-frame.md
- libs/light/docs/reference/light/neopixelstrip/show-animation.md
- libs/light/docs/reference/light/neopixelstrip/stop-all-animations.md
More fixes to showAnimation related docs
> some fixes to the light docs

- libs/light/neopixel.ts
Render animation buffered, then enforce buffering mode
> more efficient at rendering showAnimationFrame

- libs/base/core.cpp
- libs/base/loops.ts
- libs/base/pxt.cpp
- libs/base/pxt.json
- libs/base/pxtbase.h
Test: tilt to change colors, press A to play sound and crash
```
loops.when(function () {
return input.acceleration(Dimension.X) > 500;
}, function () {
light.setAll(Colors.Red);
})
loops.when(function () {
return input.acceleration(Dimension.Y) > 500;
}, function () {
light.setAll(Colors.Blue);
})
while (true) {
music.playTone(Note.A, music.beat(BeatFraction.Half))
loops.waitUntil(() => {
music.playTone(Note.G, music.beat(BeatFraction.Half))
return input.buttonA.isPressed();
});
music.playTone(Note.C, music.beat(BeatFraction.Half))
}
```
> Wait and when

- libs/base/core.cpp
- libs/base/pxtbase.h
> Add fast path to toBoolDecl and isTagged

- libs/accelerometer/docs/reference/input/acceleration.md
- libs/accelerometer/docs/reference/input/on-gesture.md
- libs/accelerometer/docs/reference/input/rotation.md
- libs/base/docs/reference/control/on-event.md
- libs/base/docs/reference/control/raise-event.md
- libs/base/docs/reference/control/run-in-background.md
- libs/base/docs/reference/control/wait-for-event.md
- libs/base/docs/reference/loops/forever.md
- libs/base/docs/reference/loops/pause.md
Set of fixes for pixel examples. Removes use of CPX-like pixel strip instance.
> Generalize pixel examples

- libs/buttons/docs/reference/input/button/is-pressed.md
- libs/buttons/docs/reference/input/button/on-event.md
- libs/buttons/docs/reference/input/button/was-pressed.md
- libs/core/docs/reference/pins/analog-read.md
- libs/core/docs/reference/pins/analog-write.md
- libs/core/docs/reference/pins/digital-read.md
- libs/core/docs/reference/pins/digital-write.md
- libs/core/docs/reference/pins/pulse-in.md
> Generalize light examples - 02

- libs/lightsensor/docs/reference/input/light-level.md
- libs/lightsensor/docs/reference/input/on-light-condition-changed.md
- libs/lightsensor/docs/reference/input/set-light-threshold.md
- libs/microphone/docs/reference/input/on-loud-sound.md
- libs/microphone/docs/reference/input/set-loud-sound-threshold.md
- libs/microphone/docs/reference/input/sound-level.md
- libs/music/docs/reference/music/play-sound-until-done.md
- libs/music/docs/reference/music/play-sound.md
- libs/switch/docs/reference/input/on-switch-moved.md
- libs/thermometer/docs/reference/input/on-temperature-condition-changed.md
- libs/thermometer/docs/reference/input/temperature.md
> Generalize 'light' examples - 04

- libs/music/music.ts
- libs/music/piano.ts
- libs/music/pxt.json
Support for piano size configuration.  Goes with https://github.com/Microsoft/pxt/pull/3520 and https://github.com/Microsoft/pxt-ev3/pull/56.
> Initial work

- libs/base/loops.ts
Lazy allocate poll event queue to save a bool variable
> don't preallocate poll event queue

- libs/light/docs/reference/light.md
- libs/light/docs/reference/light/neopixelstrip/photon-forward.md
- libs/light/docs/reference/light/neopixelstrip/set-photon-position.md
- libs/light/neopixel.ts
Support for setting position on photon
> support for set photon position

- libs/base/ns.ts
- libs/buttons/sim/buttons.ts
- libs/light/ns.ts
Remove picker functions from Intellisense, 
extend CommonButtonState to support any number of buttons
> Remove picker functions from intellisense

- package.json
- sim/tsconfig.json
Part of https://github.com/Microsoft/pxt/pull/3559
> Changes for TS 2.6.1

- libs/accelerometer/shims.d.ts
- libs/buttons/enums.d.ts
- libs/buttons/shims.d.ts
- libs/core/enums.d.ts
- libs/core/shims.d.ts
- libs/light/shims.d.ts
- libs/lightsensor/shims.d.ts
- libs/microphone/shims.d.ts
- libs/tests/README.md
- libs/tests/platformoverrides.ts
- libs/tests/pxt.json
- libs/tests/tests.ts
- libs/touch/shims.d.ts
- package.json
- pxtarget.json
Easier to write clean test suites
> Add proper unit test framework for pxt packages

- libs/behaviors/README.md
- libs/behaviors/behaviors.ts
- libs/behaviors/pxt.json
- libs/behaviors/targetoverrides.ts
- libs/tests/platformoverrides.ts
- libs/tests/targetoverrides.ts
- pxtarget.json
A behavior driven manager (subsumption-based) and simple base class that can be implemented in targets with various strategies.
> Boiler plate for Behaviors Drive Robotics

- libs/base/pxt.cpp
- libs/base/pxtbase.h
Also fix overflows in array code
> Use 32 bit array size on Linux

- libs/base/math.ts
Needed for more interesting animations
> Add PI, E and other Math constants

- libs/core/fieldeditors.ts
- libs/core/pinsDigital.cpp
- libs/core/pxt.json
- libs/gamepad/gamepad.cpp
- libs/mouse/mouse.cpp
Adding shim helpers for the various toggles.
> allow on/off / high/low to drop values in

- .travis.yml
- libs/gamepad/gamepad.cpp
- package-lock.json
- package.json
> Gamepad move

- libs/infrared/ir.cpp
Not a big deal, but generating documentation with a typo.
Thanks for all your work!  This is an awesome idea!
> Typo fix in comment

- libs/storage/sim/state.ts
- libs/storage/sim/storage.ts
- libs/storage/storage.cpp
- libs/storage/storage.ts
Crashing for 
```
input.buttonA.onEvent(ButtonEvent.Click, function () {
light.photonForward(1)
storage.append("test.txt", "hello")
})
input.buttonB.onEvent(ButtonEvent.Click, function () {
light.photonForward(-1)
storage.append("test.txt", "bye")
})
light.photonForward(1)
```
> simulator support for storage

- libs/accelerometer/docs/reference/input/acceleration.md
- libs/game/game.ts
- libs/screen/frame.ts
Also fixing samples to use pause instead of loops.pause
> Moving loops.frame to frame (top level api)

- libs/base/pxtbase.h
- libs/screen/image.cpp
- libs/screen/screen.cpp
Avoid name clash with codal::Image
> Rename Image to Image_

- libs/buttons/buttons.cpp
- libs/buttons/sim/buttons.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
- libs/keys/enums.ts
- libs/keys/keys.ts
- libs/keys/pxt.json
- libs/keys/targetoverrides.ts
It's probably not the end of it but it allows to specify the underlying button for a CODAL based target.
> tweak keys to support C++

- libs/game/sprite.ts
Allow sprites to have a speed bubble
> Sprite say feature

- libs/core/codal.cpp
- libs/core/pins.h
- libs/core/pxt.h
Allow target to override classes for pins and timers.
> Make Pin and Timer types configurable

- libs/game/game.ts
- libs/game/sprite.ts
- libs/screen/image.ts
Depends on https://github.com/Microsoft/pxt/pull/3983
> Use the new blockCombine

- libs/game/sprite.ts
- libs/game/spriteanimation.ts
- libs/turtle/turtle.ts
Support for setting image on a sprite using sprite editor
> allow to override image on a sprite

- libs/accelerometer/sim/accelerometer.ts
- libs/buttons/shims.d.ts
- libs/core/shims.d.ts
- libs/gamepad/shims.d.ts
- libs/infrared/shims.d.ts
- libs/keyboard/enums.d.ts
- libs/keyboard/shims.d.ts
- libs/mouse/enums.d.ts
- libs/mouse/shims.d.ts
- libs/screen/shims.d.ts
- libs/storage/shims.d.ts
> Support for accelerometer simulation

- libs/game/background.ts
- libs/game/game.ts
- libs/screen/image.cpp
- libs/screen/sim/image.ts
- libs/screen/text.ts
game.paint runs after rendering background and before sprites.
> Support for game.paint handler

- libs/game/sprites.ts
Requires https://github.com/Microsoft/pxt/pull/4000
> support blockSetVariable feature

- libs/game/background.ts
- libs/game/game.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
Allow a full screen image on the game
> Game background

- libs/game/background.ts
- libs/game/game.ts
- libs/game/sprite.ts
> added "ask" function

- libs/game/game.ts
Sorta important to actually create the physics engine 🤔
> Forgot a local change in the scenes PR

- libs/core/pins.h
- libs/core/pins.ts
- libs/core/pinsAnalog.cpp
- libs/core/sim/pins.ts
- libs/music/music.cpp
> Introduce more pin classes; support DAC on samd

- libs/game/prompt.ts
- libs/game/pxt.json
- libs/keys/enums.ts
- libs/keys/keys.ts
As part of this change I also had to change the keys library so that we can turn off user events. Any other prompt or "system" UI APIs will need to do the same.
> Adding string prompt to game library

- libs/music/docs/reference/music/change-tempo-by.md
- libs/music/docs/reference/music/note-frequency.md
- libs/music/docs/reference/music/play-sound-until-done.md
- libs/music/docs/reference/music/play-sound.md
- libs/music/docs/reference/music/play-tone.md
- libs/music/docs/reference/music/rest.md
- libs/music/docs/reference/music/ring-tone.md
- libs/music/docs/reference/music/set-output.md
- libs/music/docs/reference/music/set-pitch-pin.md
- libs/music/docs/reference/music/set-speaker-volume.md
- libs/music/docs/reference/music/set-tempo.md
- libs/music/docs/reference/music/set-tone.md
- libs/music/docs/reference/music/set-volume.md
- libs/music/docs/reference/music/sounds.md
- libs/music/docs/reference/music/stop-all-sounds.md
Remove target specific notes and example bits.
RE: https://github.com/Microsoft/pxt-ev3/issues/406
> Go generic in 'music' docs

- libs/game/game.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
All images are now shadow blocks and all color pickers use the new "color index" picker instead of a number field. This requires the latest PXT core
> Game color picker and image shadow blocks

- libs/game/background.ts
- libs/game/camera.ts
- libs/game/fieldeditors.ts
- libs/game/game.ts
- libs/game/physics.ts
- libs/game/prompt.ts
- libs/game/pxt.json
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
- libs/game/tilemap.ts
> Reorg game blocks

- libs/game/background.ts
- libs/game/scenes.ts
- libs/game/sprites.ts
- libs/turtle/turtle.ts
Ability to setup and manipulate a background image
> adding background image block

- libs/game/fieldeditors.ts
- libs/screen/sim/image.ts
- libs/screen/sim/state.ts
Palette now defined in `pxt.json`; depends on https://github.com/Microsoft/pxt/pull/4051
> Palette support

- libs/display/displayImage.ts
- libs/game/sprites.ts
- libs/screen/fieldeditors.ts
- libs/screen/image.ts
- libs/screen/pxt.json
> Shim cleanup + images category

- libs/game/physics.ts
- libs/game/sprite.ts
Ability to query the obstacle involved in the last physics iteration.
> sync api to query current obstacles

- libs/base/pxtbase.h
- libs/core/codal.cpp
Depends on https://github.com/Microsoft/pxt/pull/4061
> Support for .comm symbols in assembly

- libs/light/ns.ts
Remove dupe pickers that are already defined in field editors in /base
> Remove dupe pickers

- libs/base/fieldeditors.ts
- libs/light/neopixel.ts
> more default colors, graph default

- libs/screen/fieldeditors.ts
Requires https://github.com/Microsoft/pxt/pull/4157
> Fix decompilation of image shim

- libs/keyboard/keyboard.cpp
- libs/keyboard/shims.d.ts
- libs/keyboard/sim/keyboard.ts
@mmoskal can you check the conversion of the first character to character code?
> Standard key support

- libs/game/docs/reference/info.md
- libs/game/docs/reference/info/change-life-by.md
- libs/game/docs/reference/info/change-score-by.md
- libs/game/docs/reference/info/high-score.md
- libs/game/docs/reference/info/life.md
- libs/game/docs/reference/info/score.md
- libs/game/docs/reference/info/set-life.md
- libs/game/docs/reference/info/set-score.md
- libs/game/docs/reference/info/start-countdown.md
- libs/game/info.ts
First blast of 'Info' NS docs.
> Initial set of game 'info' docs

- libs/game/game.ts
> Adding interval block to game

- libs/game/image.d.ts
- libs/game/pxt.json
- libs/screen/fieldeditors.ts
Couldn't get `image.repeatY` to work; TypeScript kept complaining about ambient overloads (but `image.create()` is apparently fine 🤷‍♂️).
> Adding image blocks to the game package

- libs/game/fieldeditors.ts
- libs/game/image.d.ts
Requires https://github.com/Microsoft/pxt/pull/4239 but is safe to merge now
> Fixing decompilation of image APIs and color picker

- libs/game/docs/reference/images/image/clone.md
- libs/game/docs/reference/images/image/draw-line.md
- libs/game/docs/reference/images/image/draw-rect.md
- libs/game/docs/reference/images/image/fill-rect.md
- libs/game/docs/reference/images/image/fill.md
- libs/game/docs/reference/images/image/get-pixel.md
- libs/game/docs/reference/images/image/set-pixel.md
- libs/game/docs/types/image.md
- libs/game/image.d.ts
>   A batch of 'image' ref docs

- libs/controller/controller.ts
- libs/game/animation.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/screen/fieldeditors.ts
> updated block names

- libs/game/docs/reference/images.md
- libs/game/docs/reference/images/image/fill.md
- libs/game/docs/reference/images/image/flip-x.md
- libs/game/docs/reference/images/image/flip-y.md
- libs/game/docs/reference/images/image/replace.md
- libs/game/docs/reference/images/image/scroll.md
- libs/game/image.d.ts
> Another set of 'images' ref docs

- libs/game/scenes.ts
- libs/screen/fieldeditors.ts
Requires https://github.com/Microsoft/pxt/pull/4336
> support for drawing full screen image

- libs/game/physics.ts
- libs/game/pxt.json
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/spritemap.ts
- libs/game/sprites.ts
- libs/game/tilemap.ts
Adds top level events for created, destroed, collision, overlap. None of the existing APIs have been removed yet.
Test script: https://makecode.com/_hMuaE7PCxgre
> Top level events for sprites

- libs/base/fieldeditors.ts
Exposes speed and turn ratio block field editors.
Requires https://github.com/Microsoft/pxt/pull/4365/files
> new field editors

- libs/game/physics.ts
> restore spritemap

- libs/core/ns.ts
- libs/servo/README.md
- libs/servo/pxt.json
- libs/servo/servo.ts
- libs/servo/targetoverrides.ts
- pxtarget.json
Adds friendlier blocks to control servos.
(would be nice to have a dedicated angle picker)
> Servo blocks

- libs/display/graph.ts
- libs/game/game.ts
- libs/game/info.ts
- libs/game/prompt.ts
- libs/game/sprite.ts
- libs/screen/text.ts
It mostly works and helps to have a slightly bigger font. We can tune later on.
> using font8 whenever possible

- libs/game/sprite.ts
- libs/game/spriteevents.ts
> Sprite events naming

- libs/game/sprite.ts
- libs/game/sprites.ts
Fixes https://github.com/Microsoft/pxt-32/issues/139
> Add flag for keeping sprites on the screen

- libs/base/control.ts
> essential compat layer for microbit

- libs/game/mathUtil.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/sprites.ts
- libs/screen/fieldeditors.ts
Requires the latest PXT.
Two other small changes that made their way into this PR:
1. Tilemap now defaults to the screen size
2. Added a pickRandom API for arrays
> Sprite kind enum

- libs/base/fieldeditors.ts
- libs/light/docs/reference/light/neopixelstrip/set-photon-mode.md
- libs/light/neopixel.ts
See https://github.com/Microsoft/pxt-adafruit/pull/739
> Fix photon hue picker

- libs/music/piano.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/598
Relies on https://github.com/Microsoft/pxt/pull/4440
> Fix piano field when its on its own (color fix)

- libs/base/console.ts
- libs/music/melodies.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/564
Fixes https://github.com/Microsoft/pxt-adafruit/issues/689
> Couple of fixes for Adafruit

- libs/light/neopixel.ts
We refactor all the pickers in pxt and fixed Chibitronics Hue selector (which broke ths).
> use correct color picker again

- libs/microphone/microphone.cpp
- package-lock.json
Tune "on loud sound" for new PDM algo
> fixing onloud sound event

- libs/controller/controller.ts
- libs/game/scene.ts
After a 500ms delay, repeats key every 30ms (this can be tuned but it matches the native keyboard behavior).
> Repeat behavior in keys

- libs/game/controller.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/sprites.ts
"sprite" is now "agent" and the new create empty sprite API is in the "Lifecycle" category
> Rename sprite variable and adding an API for creating an "empty" sprite

- libs/game/spritemap.ts
- libs/game/tilemap.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/193
> Overlap map should not use screen width/height

- libs/game/info.ts
- libs/game/textDialogs.ts
I broke it when I redid the info category
> Fix monochrome HUD

- libs/game/docs/reference/sprites/sprite/bottom.md
- libs/game/docs/reference/sprites/sprite/left.md
- libs/game/docs/reference/sprites/sprite/right.md
- libs/game/docs/reference/sprites/sprite/top.md
- libs/game/docs/reference/sprites/sprite/x.md
- libs/game/docs/reference/sprites/sprite/y.md
> Sprite position properties ref docs

- libs/game/docs/reference/sprites/sprite/ax.md
- libs/game/docs/reference/sprites/sprite/ay.md
- libs/game/docs/reference/sprites/sprite/height.md
- libs/game/docs/reference/sprites/sprite/width.md
> Sprite size and accel property ref docs

- libs/game/docs/reference/sprites/sprite/image.md
- libs/game/docs/reference/sprites/sprite/left.md
- libs/game/docs/reference/sprites/sprite/lifespan.md
- libs/game/docs/reference/sprites/sprite/set-image.md
- libs/game/docs/reference/sprites/sprite/type.md
- libs/game/docs/reference/sprites/sprite/vx.md
> Sprite 'image', 'type', and 'lifespan' prop ref

- libs/core/platform.h
update i2c object for samd21. This fixed some weirdness with i2c reads
> DM: update I2C object

- libs/game/docs/reference/sprites/on-destroyed.md
- libs/game/docs/reference/sprites/sprite/destroy.md
- libs/game/docs/reference/sprites/sprite/set-flag.md
- libs/game/docs/reference/sprites/sprite/set-image.md
> Sprites destroy and set flag ref

- libs/base/pxtbase.h
- libs/core---linux/config.cpp
- libs/core---linux/linux.cpp
- libs/core---linux/pxt.json
- libs/core---linux/target.cpp
If `POKY` is defined, we assume no file system and some other simplifications.
> Make core---linux more friendly towards embedded Linux

- libs/game/scenes.ts
- libs/game/tilemap.ts
Implementation of expanded Tile api (fixes Microsoft/pxt-arcade#236)
Changes from initial suggestions:
* Instead of exposing TileMap._map, I went with just adding in a public facing setter method to avoid giving away too much of the internal state
* Did not include my implementation of "on %sprite of kind %kind=spritetype touches tile $tile=colorindexpicker"; the implementation I wrote required a bit more changes than would seem reasonable, and an alternative approach is really easy (and more extendable) with `getTilesByType(index)` and `Tile.place(sprite)`; just spawning 'lava' or 'speed boost' sprites on each tile you want to add interactions to allows for this behavior, without impacting performance for cases where you don't care about interacting with background tiles
Makes it easier …
> Expand TileMap interactions

- libs/base/core.cpp
Ports https://github.com/Microsoft/pxt-microbit/pull/1134 to common packages
Value | Rounded
-|-
1.8 | 2
1.3 | 1
1.5 | 2
-1.8 | -2
-1.3 | -1
-1.5 | -1
> C++: Round towards positive infinity

- libs/game/docs/reference/info/on-countdown-end.md
- libs/game/docs/reference/info/on-life-zero.md
- libs/game/docs/reference/info/start-countdown.md
- libs/game/docs/reference/info/stop-countdown.md
> Add more game 'info' ref docs

- libs/game/docs/reference/game/set-dialog-cursor.md
- libs/game/docs/reference/game/set-dialog-frame.md
- libs/game/docs/reference/game/set-dialog-text-color.md
- libs/game/docs/reference/game/show-long-text.md
> Add 'game' dialog ref docs

- libs/game/docs/reference/game/on-update-interval.md
- libs/game/docs/reference/game/on-update.md
> Update the game 'update' ref docs

- libs/game/docs/reference/scene/get-tile.md
- libs/game/docs/reference/scene/get-tiles-by-type.md
- libs/game/docs/reference/scene/place.md
- libs/game/docs/reference/scene/set-tile-at.md
- libs/game/docs/reference/scene/set-tile.md
- libs/game/docs/types/tile.md
> Add more 'tile' related ref docs

- libs/game/game.ts
- libs/game/info.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/sprites.ts
- libs/game/textDialogs.ts
- libs/game/tilemap.ts
Update the game api help links and descriptions.
> Update game api help links

- libs/base/core.cpp
C++ runtime for https://github.com/Microsoft/pxt/pull/4651
> added indexOf/includes

- libs/controller/docs/reference/controller.md
- libs/controller/docs/reference/controller/control-sprite.md
- libs/controller/docs/reference/controller/dx.md
- libs/controller/docs/reference/controller/dy.md
- libs/game/controller.ts
> Add 'controlSprite' to 'contoller' docs

- libs/core/pinsAnalog.cpp
analog write takes a number 0...1023
> set range on analog write value

- libs/core/pxtparts.json
- libs/servo/ns.ts
- libs/servo/pxt.json
- libs/servo/servo.ts
Requires https://github.com/Microsoft/pxt/pull/4771
Also reformat parts.json for easy diff with microbit.
> Update servo parts to support servo library

- libs/animation/animation.ts
- libs/animation/docs/reference/animation.md
- libs/animation/docs/reference/animation/add-animation-frame.md
- libs/animation/docs/reference/animation/attach-animation.md
- libs/animation/docs/reference/animation/create-animation.md
- libs/animation/docs/reference/animation/set-action.md
- libs/animation/docs/types/animation.md
> Add animation ref pages

- libs/gamepad/pxt.json
- libs/keyboard/pxt.json
- libs/mouse/pxt.json
- libs/storage/pxt.json
- libs/storage/storage.cpp
> WebUSB build fix

- libs/datalogger/datalogger.ts
- libs/storage/storage.cpp
- libs/storage/storage.ts
> PR feedback

- libs/local-multiplayer/local.ts
Add function to apply an action to each player that has been assigned a sprite
Additional minor tweak: change where existence of sprite is checked in ``controller.controlPlayer``. This is more consistent with how ``setPlayerSprite`` updates the player (it will keep track that the player is meant to be controlled, even if they haven't been assigned a sprite yet).
> local-multiplayer: Add controller.forEachPlayer (JavaScript only) 

- libs/core---linux/pxt.json
> Removing buffer.ts reference because it moved to base

- libs/core/pxt.h
- libs/serial/docs/reference/serial.md
- libs/serial/docs/reference/serial/read-string.md
- libs/serial/serial.cpp
- libs/serial/sim/serial.ts
> adding serial readstring

- libs/storage/storage.cpp
Required to build libs/storage
> typing fix for maker

- libs/serial/serial.cpp
- libs/serial/sim/serial.ts
Ensure serial in microbit is compatiable with this one.
> cross-compat changes for serial

- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/messagebusdriver.ts
- libs/jacdac/ns.ts
- libs/jacdac/pxt.json
blocks to broadcast a named value
> Jacdac broadcast

- libs/accelerometer/accelerometer.cpp
Change 'occurs' to 'happens' in onGesture jsdoc
RE: #470
> Fix ongesture jsdesc

- libs/game/mathUtil.ts
> add fast random mathUtil class

- libs/jacdac/jacdac.ts
- libs/jacdac/loggerdriver.ts
Ability to broadcast and listen for console.log messages over jacdac.
```
if (game.ask("see console?")) {
jacdac.listenConsole()
game.consoleOverlay.setVisible(true)
console.log('log')
} else {
jacdac.broadcastConsole()
game.consoleOverlay.setVisible(true)
forever(function () {
console.log("ms " + control.millis())
})
}
```
> Jacdac log

- libs/controller/controller.ts
Fix controller button repeat; event was never triggering because SYSTEM_KEY_REPEAT is the default value when no events are set, so ``raiseButtonRepeat`` was raising the wrong event.
> fix controller button repeat

- libs/base/gc.cpp
- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/loggerdriver.ts
- libs/jacdac/sensordriver.ts
- libs/jacdac/shims.d.ts
- libs/jacdac/sim/jacdac.ts
``handlePacket`` is ok in IRC + relax GC assertion
> Do not execute TS JacDac in IRC context

- libs/microphone/microphone.cpp
microphone PDM ctor had an incorrect sample rate. Tested "onLoudSound" on CPX.
> fixing microphone ctor

- libs/base/gc.cpp
- libs/core/codal.cpp
> Clean up fibers

- libs/core/codal.cpp
- libs/screen---st7735/screen.cpp
Store first panic code and prevent recursion.
> Prevent recursive panic

- libs/game/console.ts
- libs/game/menu.ts
- libs/game/sprite.ts
- libs/game/systemmenu.ts
- libs/jacdac/bridgedriver.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/pxt.json
- libs/jacdac/shims.d.ts
Add some menu support as well.
> support for jacdac bridge style drivers

- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/sensordriver.ts
- libs/jacdac/sim/jacdac.ts
- libs/jacdac/sim/state.ts
Sim programs using JACDAC don't crash anymore, but it's still acting as disconnected always.
> Basic support for JACDAC in sim

- libs/jacdac/jacdac.cpp
Adding compat layer to handle JACDAC new ctor (until all targets are aligned).
> JACDAC ctor update

- libs/accelerometer/accelerometer.cpp
> use CODAL_I2C in accelerometer

- libs/servo/servo.ts
RE: https://github.com/Microsoft/pxt-microbit/issues/1681
> Set servo api help paths

- libs/buttons/jacdac.ts
- libs/buttons/pxt.json
- libs/jacdac-drivers/accelerometerdriver.ts
- libs/jacdac-drivers/buttondriver.ts
- libs/jacdac-drivers/pxt.json
- libs/jacdac-drivers/touchbuttondriver.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/touch/jacdac.ts
- libs/touch/pxt.json
button/touch services + ensure jacdac builds for older codals
> Jacdacbuttons

- libs/base/eventcontext.ts
- libs/game/console.ts
- libs/game/game.ts
- libs/game/scene.ts
- libs/game/systemmenu.ts
Use screen to show FPS. Value still does not make sense...
> Render FPS on screen

- libs/game/spriteevents.ts
- libs/jacdac/jacdac.cpp
The C++ code wasn't being built.
> fixing build issue in jacdac

- libs/jacdac/jacdac.cpp
Always going for buzzer for now. No sounds on STM32 still.
> disable JD Router, force buzzer mode

- libs/screen---st7735/panic.cpp
- libs/screen---st7735/screen.cpp
- libs/screen/panic.cpp
- libs/screen/pxt.json
We should now always properly show the panic screen
> Add bitbang screen driver for showing panic codes

- libs/game/console.ts
- libs/game/scene.ts
- libs/game/systemmenu.ts
- libs/jacdac-drivers/sensordriver.ts
- libs/jacdac/driver.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/packet.ts
> JD set serial number

- libs/game/game.ts
- libs/game/menu.ts
- libs/game/systemmenu.ts
@riknoll please review what i am doing to your UI system :)
> Better support for systemmenu

- libs/game/systemmenu.ts
- libs/mixer/melody.ts
> volum up/down in settings

- libs/mixer/melody.ts
- libs/music/music.cpp
- libs/music/music.ts
- libs/music/ns.ts
- libs/music/piano.ts
> regorg music blocks

- libs/mixer/docs/reference/music/melody/loop.md
- libs/mixer/docs/reference/music/melody/play-until-done.md
- libs/mixer/docs/reference/music/melody/play.md
- libs/mixer/docs/reference/music/melody/stop.md
- libs/mixer/melody.ts
> Put in the mixer-music melody function docs

- libs/game/scenes.ts
Place given sprite on a random tile of the given color
>  Place on random (color) tile

- libs/jacdac-drivers/sensorclient.ts
- libs/jacdac-game/debugger.ts
- libs/jacdac/driver.ts
- libs/jacdac/pxt.json
- libs/jacdac/sensordriver.ts
- libs/jacdac/test.ts
Better retry for start/stop sensor data streaming
> Jacdac sensorstartstop

- libs/game/docs/reference/game/over.md
- libs/game/docs/reference/sprites.md
- libs/game/docs/reference/sprites/sprite/kind.md
- libs/game/docs/reference/sprites/sprite/set-kind.md
- libs/game/game.ts
- libs/game/sprite.ts
Some missing ref pages and help path fixes.
> Game ref updates/fixes

- libs/game/spriteevents.ts
- libs/game/sprites.ts
* split out projectile blocks
* uses a random velocity is vx,vy are 0
> Projectile

- libs/game/scene.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/413
> Avoid reentrant code in scene init

- libs/game/mathUtil.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/252
> hide pick random from blocks / still useful in typescript

- libs/game/sprite.ts
- libs/game/sprites.ts
Adds a mode per sprite to display position/velocity/acceleration.
> add option to show physics position for sprite

- libs/game/sprites.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/385
> remove createEmptySprite

- libs/base/sim/control.ts
- libs/base/sim/core.ts
- libs/jacdac-game/debugger.ts
- libs/jacdac/console.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/shims.d.ts
- libs/jacdac/sim/jacdac.ts
> Jacdac state

- libs/jacdac-game/console.ts
- libs/jacdac/console.ts
- libs/jacdac/debugviews.ts
- libs/jacdac/docs/reference/jacdac.md
- libs/jacdac/driver.ts
- libs/jacdac/pxtparts.json
- libs/jacdac/sim/jacdac.ts
Fixing removedriver simulator, pin mapping switch to JACK_TX
> JD pin mappings

- libs/jacdac-drivers/controllerclient.ts
- libs/jacdac-drivers/gamepadclient.ts
- libs/jacdac-drivers/mouseclient.ts
- libs/jacdac-drivers/pxt.json
- libs/jacdac-drivers/servoclient.ts
- libs/jacdac-game/controllerservice.ts
- libs/jacdac-game/pxt.json
- libs/jacdac/debugviews.ts
- libs/mouse/mouse.cpp
Service to implement additional arcade controllers
> Jd controller client

- libs/game/docs/reference/scene/set-tile-map.md
* Correct the tile_map link in the description of set-tile-map
> Fix link in set-tile-map

- libs/game/sprite.ts
> setting the right velocity

- libs/buttons/jacdac.ts
- libs/game/game.ts
- libs/game/menu.ts
- libs/game/systemmenu.ts
- libs/jacdac-drivers/accelerometerclient.ts
- libs/jacdac-drivers/buttonclient.ts
- libs/jacdac-drivers/gamepadclient.ts
- libs/jacdac-drivers/keyboardclient.ts
- libs/jacdac-drivers/lightclient.ts
- libs/jacdac-drivers/lightsensorclient.ts
- libs/jacdac-drivers/microphoneclient.ts
- libs/jacdac-drivers/mouseclient.ts
- libs/jacdac-drivers/musicclient.ts
- libs/jacdac-drivers/pixelclient.ts
- libs/jacdac-drivers/pxt.json
- libs/jacdac-drivers/servoclient.ts
- libs/jacdac-drivers/switchclient.ts
- libs/jacdac-drivers/thermometerclient.ts
- libs/jacdac-drivers/touchclient.ts
- libs/jacdac-game/controllerservice.ts
- libs/jacdac/config.ts
- libs/jacdac/controllerclient.ts
- libs/jacdac/debugviews.ts
- libs/jacdac/driver.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/ns.ts
- libs/jacdac/pxt.json
- libs/jacdac/pxtparts.json
> Jacdac controller client

- libs/game/controller.ts
- libs/jacdac-game/controllerservice.ts
Events to notify when a controller is connected
> Controller connected

- libs/game/scene.ts
- libs/particles/effects.ts
- libs/particles/particles.ts
lifespan for sources for making temporary effects (e.g. a fire that goes out after 5 seconds), destroy effects at the given anchor (destroys all that match x and y).
> particle source lifespan and destroy all effects at anchor

- libs/touch/sim/touch.ts
Touch is handled by the simulator.
> don't trigger pin action on touch

- libs/buttons/buttons.cpp
- libs/buttons/shims.d.ts
The part notation needs to be added on each button singleton.
> don't mark buttons api since they are shared with touch

- libs/serial/docs/reference/serial.md
- libs/serial/docs/reference/serial/read-until.md
- libs/serial/docs/reference/serial/set-rx-buffer-size.md
- libs/serial/docs/reference/serial/set-tx-buffer-size.md
- libs/serial/serial.cpp
- libs/serial/serial.ts
- libs/serial/shims.d.ts
- libs/serial/sim/serial.ts
serial.readUntil support.
Replacement for https://github.com/Microsoft/pxt-common-packages/pull/603
> support for readuntil

- libs/mixer/melody.cpp
- libs/mixer/melody.h
This is slightly different than in pxt (pxt uses 100k samples pre-computed buffer), but the result should be very similar.
https://github.com/Microsoft/pxt/pull/5150
> Implement wave ~5 - real noise tone

- libs/base/shims.d.ts
- libs/serial/enums.d.ts
- libs/serial/serial.cpp
- libs/serial/serial.ts
- libs/serial/shims.d.ts
- libs/serial/sim/serial.ts
- libs/storage/shims.d.ts
- libs/storage/sim/storage.ts
- libs/storage/storage.cpp
- libs/storage/storage.ts
- package.json
Ended up implementing readUntil on the TS side. @mmoskal could you double check my logic when slurping characters from the serial stream?
> utf8 freindly serial

- libs/touch/docs/reference/input/touch/calibrate.md
- libs/touch/docs/reference/input/touch/set-threshold.md
- libs/touch/docs/reference/input/touch/value.md
- libs/touch/sim/touch.ts
- libs/touch/touch.cpp
Capacitity touch may require to be recalibrated.
> Touch calibration 

- libs/touch/touch.cpp
Touch values are 12bit, normalizing to 10bit.
> normalize touch values (0..4096) to (0..1023)

- libs/mouse/shims.d.ts
- libs/serial/enums.d.ts
- libs/touch/shims.d.ts
- libs/touch/sim/touch.ts
- libs/touch/touch.cpp
- package-lock.json
> Touch threshold

- libs/serial/serial.cpp
- libs/serial/shims.d.ts
In pxt-gps baudrate is of 9600, I have added the function again
> add setbaudrate block

- libs/game/effects.ts
- libs/game/game.ts
- libs/game/particleeffects.ts
- libs/game/particles.ts
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
> Move around effects categories

- libs/game/effects.ts
- libs/game/game.ts
- libs/game/particleeffects.ts
- libs/game/particles.ts
- libs/game/pxt.json
- libs/game/sprite.ts
closes Microsoft/pxt-arcade#574 (see discussion there)
> trimming Particle effects blocks

- libs/game/game.ts
- package.json
needs to bump pxt core as well to get the field editor
> Use win / lose for `game over`

- libs/base/console.ts
> Fixing typescript errors

- libs/game/docs/reference/game/over.md
- libs/game/docs/reference/sprites/sprite/destroy.md
Thanks for the heads up @jwunderl
> Include new 'effect' parm for ref pages

- libs/game/game.ts
> game over make win/lose optional again

- libs/game/controller.ts
> Fix for controller button swap

- libs/game/controller.ts
- libs/game/docs/reference/controller/button/is-pressed.md
- libs/game/docs/reference/controller/dx.md
- libs/game/docs/reference/controller/dy.md
- libs/game/docs/reference/controller/move-sprite.md
- libs/game/docs/reference/controller/on-button-event.md
- libs/game/docs/reference/controller/on-event.md
- libs/game/docs/reference/info/change-life-by.md
- libs/game/docs/reference/info/change-score-by.md
- libs/game/docs/reference/info/has-life.md
- libs/game/docs/reference/info/life.md
- libs/game/docs/reference/info/on-life-zero.md
- libs/game/docs/reference/info/score.md
- libs/game/docs/reference/info/set-life.md
- libs/game/docs/reference/info/set-score.md
- libs/game/info.ts
> Multiplayer updates - 'controller' and 'info' ref docs

- libs/game/particleeffects.ts
- libs/game/particlefactories.ts
> star field scene effect

- libs/game/controller.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/663
Test
```
controller.A.onEvent(ControllerButtonEvent.Repeated, function () {
info.changeScoreBy(1)
})
```
> ensure player1 exists

- libs/game/game.ts
- libs/game/targetoverrides.cpp
Screenshots are done via the UI now.
> removing takeScreenshot

- libs/game/effects.ts
> Splatter and lines

- libs/base/sim/control.ts
- libs/game/particleeffects.ts
- libs/game/particles.ts
- libs/game/scene.ts
Slice sources before pruning since pruning modifies the array.
Requires https://github.com/Microsoft/pxt/pull/5198
> Particle 980 fix

- libs/screen/sim/image.ts
- libs/screen/sim/state.ts
> adding sim placeholders for screen status bar apis

- libs/base/control.ts
setInterval, setTimeout, setImmediate and the like. Makes it easier to port existing typescript libraries.
> javascript timers

- libs/base/core.cpp
- libs/base/pxtbase.h
Exposing BoxedString.charCodeAt(...). Allows C++ packages to manipulate strings.
> expose charCodeAt in C++

- libs/game/game.ts
The frame handlers are great, but you need to know when to register them! Just adding some lifecycle callbacks for extensions to use.
@jwunderl FYI
> Adding scene push/pop handlers

- libs/base/sim/cfg.ts
- libs/base/sim/control.ts
- libs/base/sim/core.ts
- libs/core/sim/pins.ts
Moving sim functions to be integrated in arcade sim
> move sim functions

- libs/lora/lora.ts
Better error handling when pins are missing or LoRa is incorrect version (e.g. simulator case)
> handle missing lora

- libs/datalogger/storagedatalogger.ts
- libs/storage/storage.cpp
- libs/storage/storage.ts
> Datalogger fix

- libs/light/defaultlights.ts
- libs/light/neopixel.ts
> better size picker for neopixels

- libs/game/scenes.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/760
> Make gamesettile expanded always

- libs/game/controller.ts
- libs/game/docs/reference/controller.md
- libs/game/docs/reference/controller/button/on-event.md
- libs/game/docs/reference/controller/button/repeat-delay.md
- libs/game/docs/reference/controller/button/repeat-interval.md
- libs/game/docs/reference/controller/on-event.md
quick documentation for `Button.repeatDelay` and `Button.repeatInterval`
I didn't link it in too many places as it's javascript only currently
> basic documentation for repeat properties

- libs/game/effects.ts
- libs/game/particlefactories.ts
Chase noticed this in the game from this tweet: https://twitter.com/mr_isaacs/status/1096089919615832066
> don't leave black ring around splatter

- libs/accelerometer/accelerometer.cpp
- libs/mixer/melody.cpp
- libs/mixer/melody.ts
also log random seed from accelerometer
> Use bootloader config key for volume

- libs/animation/animation.ts
- libs/game/game.ts
- libs/game/info.ts
- libs/game/scene.ts
> adding constants for all priorities

- libs/screen/image.ts
Circle drawing using Fx algos. (FillCircle could/should be speeded up in the future)
> adding circle apis

- libs/servo/servo.ts
More configuration option to deal with drift issue from continuous servos.
> Servo config

- libs/pulse/pulse.cpp
- libs/pulse/pulse.h
- libs/pulse/samd21.cpp
Contains a final update to make the no-mbed version of CPX feature complete.
@pelikhan and I will look to integrate and test next week, if that's ok @abchatra ?
> Update IR library for CircuitPlayground Express

- libs/servo/servo.ts
> Fix shadow annotation for servo blocks

- libs/servo/docs/reference/servos/set-stop-on-neutral.md
Tracking parameter change to api ref from #728.
> Track parameter change in servo ref

- libs/jacdac-drivers/lcdclient.ts
- libs/jacdac-drivers/pxt.json
- libs/jacdac-drivers/servoclient.ts
- libs/jacdac/config.ts
- libs/lcd/docs/reference/lcd.md
- libs/lcd/jacdac.ts
- libs/lcd/lcd.ts
- libs/lcd/pxt.json
Allow remote controlling a LCD screen with jacdac.
> Jacdac support for LCD

- libs/core/pinscompat.ts
Better coverage of pins API to support bridge with micro:bit.
> adding pin apis

- libs/lcd/characterlcd.ts
- libs/lcd/lcd.ts
- libs/lcd/sim/state.ts
Perform a minimum redraw of the LCD screen.
> Lcd tweaks

- libs/cable/cable.cpp
- libs/light/create.ts
- libs/light/defaultlights.ts
- libs/light/defaultlightsoverrides.ts
- libs/light/neopixel.ts
- libs/light/pxt.json
Splitting light APIs into separate files to allow redefinition in adafruit editor.
> Adafruit  light patch

- libs/base/control.ts
- libs/base/pxt.json
- libs/base/templates.ts
Move "hex" template string in separate file to be used in microbit.
> move hex literal in separate file for micro:bit

- libs/pulse/pulse.cpp
Offset compare did not take into account the current value of the timer counter.
Fixes IR @pelikhan
> Use setCompare rather than offset compare.

- libs/mouse/docs/reference/mouse.md
- libs/mouse/docs/reference/mouse/move.md
- libs/mouse/docs/reference/mouse/set-button.md
- libs/mouse/docs/reference/mouse/turn-wheel.md
- libs/mouse/mouse.cpp
Fill in the api ref for the mouse lib.
RE: https://github.com/Microsoft/pxt-adafruit/issues/799
> Mouse api ref docs

- libs/keyboard/docs/reference/keyboard.md
- libs/keyboard/docs/reference/keyboard/function-key.md
- libs/keyboard/docs/reference/keyboard/key.md
- libs/keyboard/docs/reference/keyboard/media-key.md
- libs/keyboard/docs/reference/keyboard/type.md
- libs/keyboard/keyboard.cpp
Fill in some ref docs for the keyboard API.
> Keybd ext ref docs

- libs/controller/README.md
- libs/controller/pxt.json
- libs/controller/vibration.ts
- libs/game/scene.ts
- libs/game/systemmenu.ts
- pxtarget.json
This new extension provides blocks to drive optional controller features - accelerometer, vibration, etc...
* this is a separate package.
> Controller extras package (vibration)

- libs/screen---linux/screen.cpp
- libs/screen/sim/image.ts
- libs/screen/sim/state.ts
> Missing setScreenBrightness

- libs/accelerometer/sim/accelerometer.ts
> fix typing on accelerometer sim

- libs/core/sim/edgeconnector.ts
- libs/core/sim/pins.ts
- libs/touch/sim/touch.ts
Fix for https://github.com/Microsoft/pxt-adafruit/issues/963
> better tracking when a pin is used

- libs/base/configkeys.h
- libs/core/pins.ts
- libs/core/pinscompat.ts
Support for configuriong pin P*
> adding p0-p20 to config keys

- libs/game/sprite.ts
Marking Sprite getters (x, vx, ax, y, vy, ay) to be called in the debugger.
> Adding comment attributes to sprite getters we want to show in the debugger

- libs/serial/docs/reference/serial.md
- libs/serial/docs/reference/serial/attach-to-console.md
- libs/serial/docs/reference/serial/create-serial.md
- libs/serial/docs/reference/serial/on-delimiter-received.md
- libs/serial/docs/reference/serial/on-event.md
- libs/serial/docs/reference/serial/read-buffer.md
- libs/serial/docs/reference/serial/read-line.md
- libs/serial/docs/reference/serial/read-string.md
- libs/serial/docs/reference/serial/read-until.md
- libs/serial/docs/reference/serial/redirect.md
- libs/serial/docs/reference/serial/set-baud-rate.md
- libs/serial/docs/reference/serial/set-rx-buffer-size.md
- libs/serial/docs/reference/serial/set-tx-buffer-size.md
- libs/serial/serial.ts
Update and add new ref pages for serial lib.
RE: #760
> Serial ref update

- libs/gamepad/gamepad.ts
- libs/jacdac-drivers/gamepadclient.ts
- libs/jacdac-drivers/lcdclient.ts
A few jsDoc bugs found by translators.
> Some translator found jsdoc bugs

- libs/base/gc.cpp
I think it would be nice to have `PXT_GC_CHECKS` off by default and have some option somewhere to turn it on. It should definitely be off by default in Arcade. @pelikhan do we have a way of doing that?
> Add a GC check

- libs/base/gc.cpp
- libs/base/pxt.json
> Add option to turn on GC checks

- libs/datalogger/datalogger.ts
- libs/datalogger/docs/reference/datalogger.md
- libs/datalogger/docs/reference/datalogger/add-row.md
- libs/datalogger/docs/reference/datalogger/add-value.md
- libs/datalogger/docs/reference/datalogger/send-to-console.md
- libs/datalogger/docs/reference/datalogger/set-enabled.md
- libs/datalogger/docs/reference/datalogger/set-sample-interval.md
Add the datalogger api reference pages.
> Add datalogger ref docs

- libs/game/particleeffects.ts
- libs/game/particlefactories.ts
- libs/game/particles.ts
Add cloud particle effect used in my blocks platformer game
Also `s/oscilattion/oscillation/g` as it's been bothering me since Richard pointed it out
> Add clouds particle effect

- libs/base/sim/cfg.ts
- libs/jacdac-drivers/musicclient.ts
- libs/servo/targetoverrides.ts
Support for edge connector in arcade
Requires https://github.com/Microsoft/pxt/pull/5403
> Dynamic pin configuration

- libs/music/sim/music.ts
- libs/screen/sim/image.ts
- package.json
Part of the debugger work on fiber management.
Also added debug preview for images (unrelated but harmless).
> Using correct api to schedule a setTimeout in the runtime.

- libs/base/control.ts
- libs/base/docs/reference/text/convert-to-text.md
- libs/base/docs/reference/text/to-text.md
See https://github.com/Microsoft/pxt-microbit/pull/1977
> toString -> toText, default to numbers

- libs/servo/docs/reference/servos.md
- libs/servo/docs/reference/servos/run.md
- libs/servo/docs/reference/servos/set-angle.md
- libs/servo/docs/reference/servos/set-pulse.md
A few links to the 'Servos' hardware video in the servo ref pages.
> Some linking to the 'Servos' hw video

- libs/base/gc.cpp
fixes https://github.com/Microsoft/pxt-microbit/issues/1985
> Fix GC assertion

- libs/base/docs/reference/text/convert-to-text.md
Fill in the 'convertToText' ref doc.
> Update 'convertToText' ref page

- libs/mixer/legacy.ts
- libs/mixer/melody.ts
* keep track of 4 melodies
* stop all melodies if needed
> Stop all sounds in mixer

- libs/accelerometer/accelhw.cpp
1. try loading accelerometer type from CFG_ACCELEROMETER_TYPE
2. if fail, sniff i2c and try to instantiate again.
> Dynamic detection of acceleremeter

- libs/game/menu.ts
> Don't log menu debug in console

- libs/game/game.ts
Moving this block to be defined as just forever in arcade
> Move remove game.forever block (set block in target instead)

- libs/game/gameoverrides.ts
- libs/game/pxt.json
Allows to plug forever in the game library (since it relies on game.forever
> add an overrides file in game

- libs/base/eventcontext.ts
No eventContext in microbit/maker/adafruit.
> handle missing context

- libs/base/gc.cpp
Fixes https://github.com/Microsoft/pxt-microbit/issues/2032
> Allow for GC out-of-order blocks

- libs/light/neopixel.ts
- libs/light/pxt.json
- libs/light/transitions.ts
> light linear gradients, brightness transitions

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/gesture.ts
- libs/accelerometer/pxt.json
This API allows to define gesture recognizers in typeScript.
> Support for defining custom recognizers in TS

- .travis.yml
- libs/base/buffer.cpp
- libs/base/configkeys.h
- libs/base/console.ts
- libs/base/eventcontext.ts
- libs/base/shims.d.ts
Misc updates from fashion branch:
> JACCDAC config keys

- libs/screen/image.ts
re: Peli's comment on https://github.com/microsoft/pxt-common-packages/pull
> Always enforce bounds on brightness

- libs/base/core.cpp
- libs/base/pxtbase.h
- libs/core---linux/linux.cpp
- libs/core/codal.cpp
- libs/game/controller.ts
This code has been around for a long time, and it is wrong. The previous lookup will find matches with DEVICE_EXT_ANY
> Fix ANY processing

- libs/controller/pxt.json
- libs/controller/thermometer.ts
- libs/thermometer/temperature.cpp
Add support for reading temperature of controller.
> Temperature support in controller

- libs/mixer/melody.ts
Also, change playTone() to use sine wave
Fixes https://github.com/microsoft/pxt-adafruit/issues/1041 (hopefully)
> Make sure playUntilDone() waits until the melody is done

- libs/base/buffer.cpp
- libs/base/core.cpp
- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/core---vm/platform.h
- libs/core---vm/scheduler.cpp
- libs/core---vm/target.cpp
- libs/core---vm/verify.cpp
- libs/core---vm/vmload.cpp
- libs/screen/image.cpp
Also adds explicit casts to silence warnings.
> iOS GC fixes for VM

- libs/controller/light.ts
- libs/light/neopixel.ts
Add a simple "light pulse" effect for controller lights. bump up default max.
> Adding some light pulse for lights

- libs/base/core.cpp
- libs/base/gc.cpp
- libs/base/pxt.cpp
- libs/base/pxtbase.h
- libs/core---linux/linux.cpp
- libs/core---vm/Makefile
- libs/core---vm/scheduler.cpp
- libs/core---vm/verify.cpp
- libs/core---vm/vm.cpp
- libs/core---vm/vm.h
also:
* optimize class member lookup
* free memory properly when deallocating image
> support for 32 bit machines in VM

- libs/core---vm/vmload.cpp
allow running of binary buffer with vm image instead of just filename
> Add pxt_vm_start_buffer

- libs/core/sim/buttons.ts
My build broke in arcade and microbit off master in pxt / here / target, didn't look into when this broke. Probably not noticed cause it would be fixed in dev with classlisthelper change?
> fix broken build for arcade and microbit

- libs/core/docs/reference/pins.md
- libs/core/docs/reference/pins/i2c-read-register.md
- libs/core/docs/reference/pins/i2c-write-register.md
- libs/core/docs/reference/pins/spi-frequency.md
- libs/core/docs/reference/pins/spi-mode.md
- libs/core/docs/reference/pins/spi-transfer.md
- libs/core/docs/reference/pins/spi-write.md
- libs/core/i2c.ts
- libs/core/spi.ts
RE: https://github.com/microsoft/pxt-adafruit/issues/864
> Pins ref doc update

- libs/core/sim/buttons.ts
> cherry pick to gcregion: fix broken build for arcade and microbit

- libs/base/core.cpp
fixes https://github.com/microsoft/pxt-arcade/issues/1088
> fix optional parameter for string.indexOf

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/core/sim/buttons.ts
This needs separate porting to `dev`, so do not merge to `master`
> Add gcPreAllocateBlock()

- libs/controller/accelerometer.ts
- libs/controller/state.ts
- support 2,3,6,8g
- support for custom gestures
> Custom gesture support in controller.

- libs/game/pxt.json
- libs/game/texteffects.ts
- libs/screen/text.ts
For character-level position-based text effects. Currently not exposed in blocks
> Text sprite object to manage state of text effects

- libs/mixer/melody.ts
- libs/music/melodies.ts
> Added "pew pew" laser sounds

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/core/sim/buttons.ts
See https://github.com/microsoft/pxt-common-packages/pull/866/files which was completed against stable6.9
> Cherry-pick Add gcPreAllocateBlock() into master

- libs/cable/sim/cable.ts
- libs/cable/sim/state.ts
- libs/infrared/sim/ir.ts
- libs/infrared/sim/state.ts
In support of https://github.com/microsoft/pxt/pull/5763
(though these were no-op for quite a while IIRC)
> Remove calls to incr/decr in JS

- libs/base/core.cpp
- libs/base/gc.cpp
- libs/base/pxt.cpp
- libs/base/pxtbase.h
- libs/core---vm/vm.cpp
- libs/core---vm/vm.h
- libs/core/codal.cpp
> runtime support for exceptions

- libs/controller/crank.ts
- libs/controller/pxt.json
Expose crank position under the controller category.
> expose crank in controller namespace

- libs/color/colorbuffer.ts
- libs/color/colors.ts
- libs/palette/palette.ts
- libs/storyboard/pxt.json
- libs/storyboard/storyboard.ts
Bring back the nice background fading between boot sequences.
> Fade background between boot sequences

- libs/jacdac-services/pxt.json
- libs/jacdac-services/rotaryencoderclient.ts
- libs/jacdac/config.ts
- libs/rotary-encoder/README.md
- libs/rotary-encoder/jacdac.ts
- libs/rotary-encoder/pxt.json
> rotary encoder jacdac

- libs/feather/README.md
- libs/feather/device.d.ts
Update feather pin to match spec
> Feather pins update

- libs/game/game.ts
- libs/game/info.ts
game over needs to take into account that the score is stored in the scene.state.
> score information is store in the scene

- libs/controller/crank.ts
- libs/rotary-encoder/jacdac.ts
- libs/rotary-encoder/rotary.cpp
Allow to customize how the crank is connected.
> add block to set crank pins

- libs/game/sim/api.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1207
> Move localstorage reference into try/catch

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/screen---linux/screen.cpp
- libs/screen---st7735/screen.cpp
- libs/screen/image.cpp
- libs/screen/sim/image.ts
- libs/screen/text.ts
This allows images larger than 255x255. The encoding of image changes, the new header is 8 bytes instead of 4.
There's a related pxt PR coming with compiler support (though this should work independently, as it also has dynamic conversions).
> Support for big image encoding

- libs/light/defaultlights.ts
- libs/light/neopixel.ts
Port #933 to stable for https://github.com/microsoft/pxt-adafruit/pull/1097
> [stable6.14] fix gradient block

- libs/base/core.cpp
> Use proper JS semantics for bitshifts

- libs/game/sprite.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1262
> make show physics respect camera offset

- libs/game/physics.ts
> [stable6.15] only collide once in each direction per tile color

- libs/screen/image.cpp
- libs/screen/sim/image.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1293
> Implement image.scroll() in both directions

- libs/edge-connector/pxt.json
- libs/feather/pxt.json
Since we're pulling pin definition, we also get serial.
> require serial with feather/edge-connector

- libs/game/physics.ts
re: https://forum.makecode.com/t/why-is-the-speed-up-to-153-floating-point-numbers/255/5
make it so max speed is more easily setable at runtime, by exposing getters and setters in ArcadePhysicsEngine / a method to set to the physics engine base class.
I also added getters / setters for each in the ArcadePhysicsEngine; to be used there would have to be a cast for the engine off the scene as the base class doesn't have it, but nice enough to have in any case / there if someone actually wants more control
quick example: 
```typescript
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
game.currentScene().physicsEngine.setMaxSpeed(3000);
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
game.currentScene().physicsEngine.setMaxSpeed(50);
}) …
```
> more reasonable max speed config option

- libs/base/configkeys.h
Also adds pins from #973 to avoid collisions
> Add pin for USB power detection

- libs/base/control.cpp
- libs/base/shims.d.ts
- libs/base/sim/control.ts
- libs/game/particles.ts
- libs/screen/sim/image.ts
- package.json
support for https://github.com/microsoft/pxt/pull/6017
> memory leak tracking

- libs/settings/RAFFS.cpp
- libs/storage/SNORFS.cpp
> missing hash_fnv1a from pxtbase

- libs/animation/animation.ts
This requires the new version of PXT, which I will bump pxt-arcade to use shortly
> Adding block for the animation editor

- libs/esp32/ninacontroller.ts
- libs/net/net.ts
- libs/net/requests.ts
> moving to execption in esp32 code

- libs/keyboard/keyboard.cpp
- libs/keyboard/keyboard.ts
- libs/keyboard/shims.d.ts
- libs/keyboard/sim/keyboard.ts
- libs/keyboard/test.ts
Keeps track of the down state of a key so that we don't span the computer with incorrect up/down events.
> Keyboard buffered

- libs/core/leveldetector.ts
Add ''reset'' to clear internal state of level detector
> allow level detector to be resetted

- libs/screen/fieldeditors.ts
filter in / out background images, like the ones here: https://github.com/microsoft/pxt-arcade/pull/1414/commits/cc6ab629342920fdd5c9617d824a310a7d4072d4
> add filter for background images

- libs/esp32/ninacontroller.ts
Fix for ESP32<->STM32 communication
> Wake up SPI in ESP32 driver before pulling CS down

- libs/buttons/buttons.cpp
- libs/controller/accelerometer.ts
- libs/core/pinsDigital.cpp
- libs/microphone/microphone.cpp
A few typos found by translators....
> Fix some typos found by Crowdin translators

- libs/game/info.ts
- libs/game/scene.ts
- libs/game/sprite.ts
- libs/game/spriteset.ts
These public-facing classes should be marked as export.
See also: https://github.com/microsoft/pxt/pull/6167
> Fixes typings needed by Python

- libs/azureiot/azureiot.ts
- libs/core/keyvaluestorage.ts
- libs/core/light.h
- libs/jacdac/docs/reference/jacdac.md
- libs/jacdac/driver.ts
- libs/serial/pxt.json
- libs/thermometer/pxt.json
Typos fixed for 11-25-2019 scan of Crowdin comments/issues.
> Fixes for typos found in Crowdin - 11252019

- libs/game/hitbox.ts
- libs/game/physics.ts
- libs/game/sprite.ts
use the newly useful (https://github.com/microsoft/pxt-common-packages/pull/1015) constants in physics, and also store hitbox as Fx8 instead of going back and forth all the time
> use consts for Fx8 1 / 2, and use Fx8 for hitbox

- libs/base/pxt.json
- libs/net-game/pxt.json
- libs/storyboard/pxt.json
- pxtarget.json
Fix dependency issues that were creating warnings. Used with https://github.com/microsoft/pxt/pull/6275
> Low warnings

- libs/game/sprites.ts
Fix some typos found by translators in Crowdin:
* https://crowdin.com/translate/kindscript/2959/en-fr#686174
> Fix typos found thru Crowdin - 12052019

- libs/game/docs/reference/sprites/sprite/tile-kind-at.md
- libs/game/docs/reference/tiles/get-tile.md
- libs/game/docs/reference/tiles/get-tiles-by-type.md
- libs/game/docs/reference/tiles/on-hit-wall.md
- libs/game/docs/reference/tiles/on-overlap-tile.md
- libs/game/docs/reference/tiles/place-on-random-tile.md
- libs/game/docs/reference/tiles/place.md
- libs/game/docs/reference/tiles/set-tile-at.md
- libs/game/docs/reference/tiles/set-tile-map.md
- libs/game/docs/reference/tiles/tile-map.md
- libs/game/physics.ts
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/tilemap.ts
- libs/screen/fieldeditors.ts
TODO: 
- Go over all examples and ensure they're correct
- Fix bug with using 'location' argument in sprite overlaps tile block
> Tilemap block definitions

- libs/base/control.ts
- libs/game/game.ts
- libs/game/info.ts
- libs/game/scenes.ts
- libs/music/ns.ts
- libs/screen/fieldeditors.ts
Use the colors from pxt-arcade.
Fixes: https://github.com/microsoft/pxt-arcade/issues/1489
Sister PR: https://github.com/microsoft/pxt/pull/6320
> fix arcade colors in common packages

- libs/screen/image.cpp
Fix for https://github.com/microsoft/pxt-arcade/issues/700
> off by one issues

- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/tilemap.ts
Also rename 'Direction' enum to avoid potential conflicts with existing projects
> Old tilemap blocks should still use Tile type

- libs/game/tilemap.ts
> Reorder arguments in set tile at location, update array of tiles block

- libs/base/buffer.cpp
To better support https://github.com/microsoft/pxt-common-packages/pull/1044
Requires https://github.com/microsoft/pxt/pull/6377
> Add isReadOnly method on Buffer

- libs/base/buffer.cpp
- libs/color-coded-tilemap/tilemap.ts
- libs/game/tilemap.ts
Includes the fix for microsoft/pxt-arcade#1625 and the old tilemap stuff
> Cherry pick write tilemap and old tilemap

- libs/game/tilemap.ts
Cherry picking the fix for https://github.com/microsoft/pxt-arcade/issues/1618
> Adding missing null check (#1047)

- libs/base/control.ts
- libs/base/gc.cpp
fixes https://github.com/microsoft/pxt-arcade/issues/1622
> Fix GC fragmentation bug and add control.gcStats()

- libs/base/control.ts
- libs/base/gc.cpp
Cherry picking the gc fix to stable
> Fix GC fragmentation bug and add control.gcStats() (#1049)

- libs/base/docs/device/error-codes.md
Should there be a note for `000`?
RE: https://github.com/microsoft/pxt-arcade/issues/1688, https://github.com/microsoft/pxt-arcade/issues/1474
> Include new codes is error codes page

- libs/core---samd/shims.d.ts
- libs/core/shims.d.ts
- libs/game/controller.ts
- libs/game/docs/reference/sprites/sprite/vy.md
- libs/game/info.ts
- libs/game/particles.ts
- libs/game/sprite.ts
String bugs found by translators.
> String bugs found by translators - 01242020

- package.json
Bumping ts dependency to 3.7.5
> bump typescript version

- libs/base/buffer.cpp
- libs/base/buffer.ts
- libs/base/test.ts
- libs/tsconfig.json
> Move methods to Buffer namespace

- libs/accelerometer/docs/reference/input/on-gesture.md
- libs/accelerometer/docs/reference/input/rotation.md
- libs/base/buffer.ts
- libs/buttons/docs/reference/input/button/is-pressed.md
- libs/buttons/docs/reference/input/button/on-event.md
- libs/buttons/docs/reference/input/button/was-pressed.md
- libs/cable/docs/reference/network/on-cable-received-number.md
- libs/core/docs/reference/pins/analog-read.md
- libs/core/docs/reference/pins/digital-read.md
- libs/core/docs/reference/pins/pulse-in.md
- libs/infrared/docs/reference/network/on-infrared-received-number.md
- libs/switch/docs/reference/input/on-switch-moved.md
- libs/touch/docs/reference/input/touch/set-threshold.md
- libs/touch/docs/reference/input/touch/value.md
Change out the pixel examples to more generic ones.
> Change out more pixel examples

- libs/base/core.cpp
- libs/base/eventcontext.ts
- libs/game/textDialogs.ts
Also disable auto-dumping of counters on hardware (clogs the buffer)
and minor perf fix in dialogs
> Fix crash in hw profiling

- libs/game/textDialogs.ts
see https://github.com/microsoft/pxt-arcade/issues/1812
> Optimize frame drawing for unit==1 case

- libs/keyboard/keyboard.ts
> more keyboard combos

- libs/core/sim/neopixel.ts
> fix neopixel zoom

- libs/base/eventcontext.ts
Would be nice to be able to unplug some 1-time use frame handlers.
> ability to unregister a frame handler

- libs/mouse/enums.d.ts
- libs/mouse/mouse.cpp
- libs/mouse/mouse.ts
- libs/mouse/shims.d.ts
Easy block to generate a mouse click
> Add mouse click

- libs/serial/enums.d.ts
- libs/serial/serial.ts
> Aligning serial with microbit

- libs/radio/radio.cpp
- libs/radio/radio.ts
- libs/radio/sim/radio.ts
- libs/radio/sim/state.ts
Support an RSSI value from a simulator.
> rssi support in sim

- libs/core/sim/neopixel.ts
Support for various data layout in ws2812b strips
> read light mode from state

- libs/radio/sim/state.ts
Our TS version does not like this one.
> ?? does not seem to be supported with the current ts in makecode

- libs/jacdac-services/musicclient.ts
- libs/mixer/melody.ts
@pelikhan do you want to add block for `playMelody`? I'm not sure I'm too good at that
> Allow melody playing through jacdac

- libs/game/docs/reference/tiles.md
- libs/game/docs/reference/tiles/set-wall-at.md
Add the reference page for `setWallAt()`.
Closes https://github.com/microsoft/pxt-arcade/issues/2004
> Add a ref page for 'set-wall-at'

- libs/game/docs/reference/game/on-update-interval.md
- libs/game/docs/reference/game/on-update.md
Typos in the 'on-update' reference pages.
Closes https://github.com/microsoft/pxt-arcade/issues/2039
> Fix the 'when' s in game 'onUpdate'

- libs/game/docs/reference/math/percent-chance.md
- libs/game/mathUtil.ts
Add the reference page for `percentChance()`.
Closes https://github.com/microsoft/pxt-arcade/issues/2080
> Add a reference page for 'percentChance'

- libs/game/tilemap.ts
- package.json
This is to support https://github.com/microsoft/pxt/pull/7274
> Adding tilemap helper to support new jres implementation

- libs/game/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2104
> Add snippet comment attribute for tilemaps

- libs/game/game.ts
- libs/game/textDialogs.ts
Required by https://github.com/microsoft/pxt/pull/7317
> Remove () from .widht()/.height()

- libs/game/tilemap.ts
Doh forgot to push this change to my previous PR
https://github.com/microsoft/pxt-arcade/issues/2112
> Default to TileScale.Sixteen explicitly

- libs/game/textDialogs.ts
This is bringing over the greedy line break algorithm I implemented in my story extension (with a few fixes). It produces much, much, better results than the current behavior. It also respects line breaks including those from blocks (i.e. both "\n" and "\\\\n").
Here is some lorem ipsum text on the current editor:
and here it is with my changes:
Note the lack of annoying hyphens!
> Better algorithm for breaking up text in dialogs

- libs/accelerometer/accelhw.cpp
Reverts https://github.com/microsoft/pxt-common-packages/pull/1028
Fixes https://github.com/microsoft/pxt-arcade/issues/1745
> Align meowbit acceleration axis with other boards

- libs/core---nrf52/platform.h
- libs/core---samd/platform.h
- libs/microphone/microphonehw.cpp
A long-forgotten PR that was lingering on my machine - makes microphone config more flexible
> Move mic includes to platform files

- libs/base/core.cpp
- libs/base/pxt.cpp
- libs/base/pxtbase.h
- libs/core---vm/keys.cpp
- libs/core---vm/platform.h
- libs/core---vm/verify.cpp
- libs/core---vm/vm.cpp
- libs/core---vm/vmcache.cpp
Support for https://github.com/microsoft/pxt/pull/7367
Also deals with settings path on VM
>  make VM work again

- libs/core---vm/vm.cpp
Should fix issue mentioned here https://github.com/microsoft/pxt-arcade/pull/2324#issuecomment-672112650
> Fixing generation of enums.d.ts

- libs/game/sprite.ts
should use rate of the followingSprite to calculate maxMomentumDiff
https://github.com/microsoft/pxt-arcade/issues/2389
> speed -> rate

- libs/core/codal.cpp
- libs/settings/RAFFS.h
- libs/settings/settings.cpp
Used here https://github.com/microsoft/pxt-tensorflow/blob/main/shims.d.ts#L22
> Support code for re-writing large binary blobs in flash

- libs/mixer/melody.cpp
fixes https://github.com/microsoft/pxt-arcade/issues/2441
cc @klausw
> Don't bother with buggy caching of freq sweeps

- libs/base/core.cpp
- libs/base/pxtbase.h
- libs/core/pxtcore.h
needs https://github.com/microsoft/pxt/pull/7507 (or it will print junk)
> Have pxt::failedCast() report failure address

- libs/base/sim/controlmessage.ts
Updated to match pxt::sendMessage
> fix control simmessages shim name

- libs/core/sim/analogSensor.ts
Allows for displaing in microbit sim
> make threashold public

- libs/base/controlmessage.ts
- libs/base/sim/controlmessage.ts
> [stable8.1] Cherry pick send message changes

- libs/accelerometer/accelhw.cpp
- libs/core---nrf52/platform.cpp
- libs/core---nrf52/platform.h
- libs/core/light.cpp
- libs/core/pins.cpp
* allow for accelerometer without INT pin
* implement pxt::deepSleep() on nrf52
* support SPI neopixel on nrf52
> fixes for nrf52 JD brain board

- libs/settings---files/pxt.json
> fix settings-files name

- libs/base/sim/controlmessage.ts
- libs/core---nrf52/shims.d.ts
- libs/core---samd/shims.d.ts
- libs/core---stm32/shims.d.ts
- libs/core/pinsAnalog.cpp
- libs/core/pinsDigital.cpp
- libs/core/shims.d.ts
- package.json
> External simulators

- libs/radio/sim/state.ts
- package.json
> Self registration of message in radio state

- libs/game/ask.ts
fix https://github.com/microsoft/pxt-arcade/issues/2738
fix https://github.com/microsoft/pxt-arcade/issues/1639
Someday we should probably see about better handling for controller events creating new scenes / maybe think on the queuing behavior~
> fix ask block inside on a / b pressed controller event

- libs/game/docs/reference/sprites/sprite/set-flag.md
fix https://github.com/microsoft/pxt-arcade/issues/2544
> update set flag ref doc

- libs/core---samd/platform.h
on behalf of @wallarug. Part 3 of 3.
changes for the platform.h in common packages
See: https://github.com/microsoft/pxt-common-packages/pull/1207
For rest of files: https://github.com/microsoft/pxt-maker/pull/329
> Updated pull request (1207) platform.h

- libs/game/sprite.ts
re: https://github.com/microsoft/pxt-common-packages/pull/1220/commits/c2f3c6ee991d6aadb3ba21b12d0639d4e09bd768, remove autodestroy block & default setflag to autodestroy:
ported in https://github.com/microsoft/pxt-common-packages/pull/1220
> remove autodestroy block, default dropdown to auto destroy

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
port #1219 and https://github.com/microsoft/pxt-common-packages/pull/1221 to stable
> [stable8.4] Split wall & tile flag, add top level blocks for flags in tutorials (#1219)

- libs/mixer/melody.ts
These are intended to provide some additional options for games and provide inspiration for custom sounds.
Test program based on using a modified editor with this PR included: https://makecode.com/_4PfMrpP9bg0h
Adapted from this standalone demo: https://makecode.com/_2uac15Pjbig9
> Add effects to music "play sound" block

- libs/base/pxtbase.h
- libs/core---vm/scheduler.cpp
Changes to get pxt.dll working in Unity.
> Changes for vm operation

- libs/game/animation.ts
> Fixes stop animation not working with legacy state animation

- libs/settings/NRF52Flash.cpp
Soft device requires control over everything...
> add protected flash writes/erases for when SD is in use

- libs/game/docs/reference/tiles/place-on-random-tile.md
Add a `jres` section and update example to use the defined tilemap.
Fixes https://github.com/microsoft/pxt-arcade/issues/3358
> Update example for 'place on random tile' page

- libs/music/music.ts
My daughter complained about the triplets missing in MakeCode - So here they are and hopefully okay ;-)
> Add - Triplet note

- libs/core---samd/platform.h
Support extra pins for Neotrellis.
> use 128 pins for samd51

- libs/game/physics.ts
- libs/game/tilemap.ts
Make it easier to subclass physics engine, as these are all things you might need to change when you're doing something new & no reason to keep them private.
> private->protected for physics collisions

- libs/core/hf2.cpp
Add define for dbl reset pointer address for nordic processors that support usb
> add ifdef for nrf52 in hf2.cpp

- libs/game/textDialogs.ts
Cherry picking #1249 to stable to support the release of a patch for https://github.com/microsoft/pxt-arcade/pull/3454
> Cherry pick "Handle very large dialog frames (#1249)"

- libs/game---light/compat.ts
@eanders-MS feel free to add a little more here - whatever you think is generally useful and you need in kojac. With these two functions my jacdac-multitool (menu system) works fine with game---light
> Add game.push/popScene (aliases to push/popEventContext)

- sim/tsconfig.json
Should fix build. Thanks @mmoskal
> Fix sim rootdir

- libs/game/ask.ts
- libs/game/numberprompt.ts
- libs/game/prompt.ts
- libs/game/textDialogs.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3199
Also does all the "ask" functions and splash
> Make all string inputs permissive

- libs/game/controller.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1616
Adds the field editor to the "Move mySprite with buttons" block
> Add shadow to vx and vy on moveSprite block so it shows field editor

- libs/game/pxt.json
- libs/game/renderText.ts
- libs/game/sprite.ts
- libs/game/spritesay.ts
New sprite say with line wrapping and animations. Also implemented a new RenderText class that can be used for general line wrapping. Eventually I'll move the other dialogs to use the same thing. Please forgive the probably very incorrect Chinese in that gif, I just used a translator.
The old sprite say is deprecated but still exists. Old programs will be unchanged.
> New Sprite.say with line wrapping and animations

- libs/azureiot/azureiot.ts
- libs/base/sim/control.ts
- libs/net/requests.ts
- libs/settings/settings.ts
- libs/wifi---esp32/shims.d.ts
plus fixes for net.getJSON/Text and color-coding for console.log
> more azure iot twin support

- libs/azureiot/azureiot.ts
If parsing key with invalid format, clear key.
> azure iot: catch invalid key errors

- libs/azureiot/azureiot.ts
> fix azure iot connection logic, disconnect

- package.json
Updating to have the latest pxt for these changes: https://github.com/microsoft/pxt/pull/8506
> Update pxt-core dependency

- libs/screen/image.cpp
- libs/screen/sim/image.ts
> fix blit bug

- libs/screen/image.cpp
- libs/screen/sim/image.ts
Blit was mishandling left/top clipping. Last fix I hope.
> blit: fix clipping issue

- libs/net/controller.ts
More information about why the wifi stack does not connect.
> net: additional events

- libs/game/docs/reference/scene.md
Arcade build was throwing this error.
> Fixing couple of issues with the snippet of scene

- libs/text-to-speech/pxt.json
- libs/text-to-speech/shims.d.ts
- libs/text-to-speech/sim/tts.ts
- libs/text-to-speech/tts.ts
Adds text to speech support in the browser simulator.
> Add browser text to speech library

- libs/game/renderText.ts
- libs/game/spritesay.ts
This is to support reusing this code in the storytelling extension. Just adding some missing functions for calculating the dimensions of the animation and a callback for when a character is printed. Also refactoring the code for drawing the sprite.say bubble so that it's accessible elsewhere.
> Small render text code refactor and adding some useful functions

- libs/color/colors.ts
Reported here: https://forum.makecode.com/t/javascript-wont-translate-back-to-blocks/11786
> Fix decompilation of colors enum

- libs/color/colors.ts
Reported here: https://forum.makecode.com/t/javascript-wont-translate-back-to-blocks/11786
Cherry picking to adafruit stable branch
> [stable8.1] Fix decompilation of colors enum

- libs/sprite-scaling/scaling.ts
Note: These are breaking changes!
Latest:
> Tweak scale extension block definitions

- libs/sprite-scaling/scaling.ts
> Tweak scaling category icon, title

- libs/game/controllerbutton.ts
- libs/game/scene.ts
- libs/game/tilemap.ts
Cherry picking the tilemap load/unload events (#1324) and controller button events (#1323)
> [Stable9.4] Cherry pick my two events PRs

- libs/radio/radio.cpp
- libs/radio/sim/radio.ts
- libs/radio/sim/state.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4047
While in that code, I changed the default group to zero as well to match micropython as an experimentation. If we hear back issues from the customers for beta, I will revert this back.  This seems a good way to test the hypotheses.
> Adding radio.off and radio.on api

- libs/radio-broadcast/radio-broadcast.ts
- libs/radio/radio.cpp
- libs/radio/radio.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/3247 
While there I categorized the blocks as well to look nice.
> Categorize radio and move the order of blocks

- libs/game/docs/reference/sprites/sprite/follow.md
- libs/game/sprite.ts
Add a reference page for `sprite.follow()`.
> Reference page for sprite 'follow'

- libs/game/extendableSprite.ts
- libs/game/keymap.cpp
- libs/game/keymap.ts
- libs/game/pxt.json
- libs/game/sim/keymap.ts
- libs/game/sprite.ts
Cherry picking two PRs for a patch release
> [Stable9.4] Cherry pick #1342 and #1343

- libs/game/game.ts
- libs/game/info.ts
Saves the scores for each player after a game has ended.
> Save all player scores at the end of each game

- libs/game/docs/reference/tiles/tile-image-at-location.md
- libs/game/sprite.ts
- libs/game/tilemap.ts
A few tilemap help path fixes when checking after @eanders-ms bump https://github.com/microsoft/pxt-arcade/pull/4796. Finally, been waiting for that to test the tilemap page migration.
> Tilemap help path fixes

- libs/game/docs/reference/info/change-score-by.md
- libs/game/docs/reference/info/on-score.md
- libs/game/docs/reference/info/score.md
- libs/game/docs/reference/info/set-score.md
- libs/game/info.ts
Adding the "on score" blocks as Kiki proposed! I also added docs
> Add on score events for game info category

- libs/game/sim/keymap.ts
Reverts microsoft/pxt-common-packages#1356
> Revert "temporarily change reset to 2 for kiosk"

- libs/game/docs/reference/effects/clear-particles.md
re: https://forum.makecode.com/t/effects-clearparticles-doesnt-clear-particles/14373
> Add note about particles.clearAll()

- libs/core---rp2040/platform.cpp
- libs/core/hf2.cpp
- libs/core/hf2.h
- libs/core/pxt.h
- libs/mixer---rp2040/SoundOutput.h
- libs/settings/settings.cpp
* find "bootloader" config data in flash on rp2040; fix `settings` flash position
* bump sound sample rate to 44kHz on RP2040
* use new `USB_EP_FLAG_ASYNC` codal flag to implement async HF2 packet queue
> fixes for RP2040

- libs/game/camera.ts
remove the normalization that was causing the issue
> Resolve center camera off by one

- libs/game/assetTemplates.ts
- libs/mixer/instrument.ts
- libs/mixer/melody.h
- libs/mixer/melody.ts
- libs/mixer/pxt.json
- libs/mixer/sequencer.ts
This adds the song decoding, asset template functions, and sequencer to the mixer package.
Eventually, I would like to make the sequencer more accurate by moving the timing callback into C++/sim
> Add music editor code to the mixer package

- libs/game/sim/multiplayer.ts
- package.json
One question, do we want to attach a millis field (should just be `runtime.runningTime()`) in case we eventually want to do some type of timing?
(also unrelated I snuck in some ?. by accident last time and got rid of them here, it's not a big deal as browsers support them nowadays but figure it's better to minimize errors in the build when it's easy)
Build will fail until pxt pr which contains `soundEventCallback` is in (https://github.com/microsoft/pxt/pull/9165)~
> multiplayer send around audio channels

- libs/game/info.ts
Adding getters and setters to the player info in order to avoid breaking anyone who was using the javascript only properties.
In other words, just for @jwunderl
> Add getters and setters to avoid breaking change

- libs/multiplayer/player.ts
- libs/multiplayer/stateKind.ts
I meant to include this in my last PR!
> lowercase score and life

- libs/game/controller.ts
- libs/game/info.ts
Reverts microsoft/pxt-common-packages#1393
> Revert "Deprecate existing multiplayer blocks"

- libs/mixer/melody.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5481
> Add snippet override for song editor

- libs/game/ask.ts
- libs/game/game.ts
- libs/game/gameutil.ts
- libs/game/ns.ts
- libs/game/numberprompt.ts
- libs/game/prompt.ts
- libs/game/pxt.json
* Pull namespace config into one location
* Move Game Over sub-category up to second position (tentative! need to look at telemetry for any surprise usage patterns)
> Game namespace cleanup

- libs/mixer/instrument.ts
- libs/mixer/melody.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5598
> Stop all sounds should also stop songs

- libs/game/controller.ts
- libs/game/scene.ts
- libs/game/sim/multiplayer.ts
cherry pick:
* https://github.com/microsoft/pxt-common-packages/pull/1409
* https://github.com/microsoft/pxt-common-packages/pull/1413
> [stable10.3] cherry picks for connection & better empty icon handling

- libs/game/sim/multiplayer.ts
if user sets an image with no pixels treat it as if they set undefined (just show icon). Also a bit of null safety I didn't account for apparently~
> bit of safety && treat empty images as undefined

- libs/multiplayer/player.ts
Closes https://github.com/microsoft/pxt-arcade/issues/5608
> mp: add $player connected block

- libs/multiplayer/ns.ts
- libs/multiplayer/player.ts
* add "array of all players" block
* rename
* Update libs/multiplayer/player.ts
Co-authored-by: Joey Wunderlich <jwunderl@users.noreply.github.com>
---------
Co-authored-by: Joey Wunderlich <jwunderl@users.noreply.github.com>
> (hotfix stable10.3) cherry-pick: add "array of all players" block (#1416)

- libs/multiplayer/docs/reference/multiplayer.md
- libs/multiplayer/docs/reference/multiplayer/change-player-state-by.md
- libs/multiplayer/docs/reference/multiplayer/game-over-player-win.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-index.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-number.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-sprite.md
- libs/multiplayer/docs/reference/multiplayer/get-player-property.md
- libs/multiplayer/docs/reference/multiplayer/get-player-sprite.md
- libs/multiplayer/docs/reference/multiplayer/get-player-state.md
- libs/multiplayer/docs/reference/multiplayer/is-button-pressed.md
- libs/multiplayer/docs/reference/multiplayer/move-with-buttons.md
- libs/multiplayer/docs/reference/multiplayer/multiplayer-state.md
- libs/multiplayer/docs/reference/multiplayer/on-button-event.md
- libs/multiplayer/docs/reference/multiplayer/on-controller-event.md
- libs/multiplayer/docs/reference/multiplayer/on-life-zero.md
- libs/multiplayer/docs/reference/multiplayer/on-score.md
- libs/multiplayer/docs/reference/multiplayer/player-selector.md
- libs/multiplayer/docs/reference/multiplayer/set-player-indicators-visible.md
- libs/multiplayer/docs/reference/multiplayer/set-player-sprite.md
- libs/multiplayer/docs/reference/multiplayer/set-player-state.md
- libs/multiplayer/docs/types/player.md
- libs/multiplayer/fieldEditors.ts
- libs/multiplayer/player.ts
cherry pick https://github.com/microsoft/pxt-common-packages/pull/1406, which is needed to pull in help link paths from `libs/multiplayer/fieldEditors.ts` and `libs/multiplayer/player.ts`
> [stable10.3] Reference pages for 'multiplayer' blocks

- libs/game/multiplayer.ts
- libs/game/scene.ts
- libs/game/sim/multiplayer.ts
Register listeners so we pick up these events outside host mode
> always listen for multiplayer connection messages, not just when multiplayer app

- libs/mixer/melody.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5652
I ended up not making the breaking change because it completely broke the decompile story. This fixes the decompilation as it currently exists!
> Fix create song decompile

- libs/mixer/instrument.ts
- libs/mixer/melody.cpp
- libs/mixer/sequencer.ts
- libs/mixer/sim/music.ts
- package.json
* Better support for playing songs in the browser sim
* upate core
> [Stable10.3] Cherry pick sim music fix

- libs/screen/image.cpp
> fillTriangle/Polygon() use new added drawVLineCore()

- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
cherry pick over https://github.com/microsoft/pxt-common-packages/pull/1440, https://github.com/microsoft/pxt-common-packages/pull/1441 for release
> [stable10.3] Cherry pick triangles

- libs/mixer/melody.ts
https://github.com/microsoft/pxt-common-packages/pull/1444
> [Stable10.3] Cherry pick tagged template fix

- libs/mixer/docs/reference/music/create-sound-effect.md
- libs/mixer/docs/reference/music/play-sound-effect.md
- libs/mixer/docs/reference/music/play.md
- libs/mixer/docs/reference/music/randomize-sound.md
- libs/mixer/docs/types/sound-effect.md
- libs/mixer/playable.ts
- libs/mixer/soundEffect.ts
Set the help paths, add jsDoc playable, add the missing reference pages.
> Update music api reference for playable and sound effect apis

- libs/screen/fieldeditors.ts
- sim/tsconfig.json
Also includes: Fix simulator build (#1460)
> [stable10.3] Cherry pick: Change img field editor to sprite (#1459)

- libs/game/animation.ts
- libs/game/docs/reference/controller/dy.md
- libs/game/docs/reference/info/countdown.md
- libs/game/docs/reference/scene/get-tile-location.md
- libs/game/docs/reference/scene/tile-at-location-equals.md
- libs/game/docs/reference/scene/tile-at-location-is-wall.md
Fix some omissions and shameless copy/paste errors from #1466.
RE: https://github.com/microsoft/pxt-arcade/issues/6231
> Reference page fixes for PR 1466

- libs/settings/settings.cpp
fix for https://github.com/microsoft/pxt-microbit/issues/5521
> special case for settings under MICROBIT_CODAL

- libs/screen/fieldeditors.ts
- libs/screen/image.d.ts
- libs/screen/image.ts
a few tweaks to the image category:
* adds a width/height block for images
* adds draw image to image block
* fixes image variable names
* deprecates the image_picker block which is basically just a duplicate of the regular create image block
> fix image variable names and add width/height + draw

- libs/screen/image.ts
Also make it symmetrical. Fixes https://github.com/microsoft/pxt-arcade/issues/6336
> Update rotated help for rotated

- libs/screen/image.cpp
Fixes https://github.com/microsoft/pxt-arcade/issues/6335
> Fix incorrect transposed in screen

- libs/browser-events/browserEvents.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6875
Also fixes a similar bug mentioned on the forum that I confirmed was a problem: https://forum.makecode.com/t/arcade-2025-update-is-live/34864/4
> flip some mouse events

- libs/browser-events/browserEvents.ts
- libs/browser-events/keyboard.ts
- libs/browser-events/sim/keyboard.ts
- libs/browser-events/sim/mouseState.ts
cherry picking my second round of browser event fixes
> [Stable12.2] Cherry pick "fix queueing of browser events and handle scenes with the mouse (#1515)"

- libs/base/docs/reference/math/constant.md
- libs/base/math.ts
Add a reference page describing the new `Math.XXXX` constants.
Closes https://github.com/microsoft/pxt-microbit/issues/6328
> Math constants reference page
