microsoft/pxt-common-packages

- libs/core/buffer.cpp
- libs/core/control.ts
- libs/core/enums.d.ts
- libs/core/i2c.cpp
- libs/core/i2c.ts
- libs/core/pins.ts
This PR adds:
* support for uint32 and float NumberFormats when operating on buffers
* pins.packBuffer, unpackBuffer (similar for Python struct.pack)
* I2CDevice class (encapsulates address and in future lock)
* adds return codes to I2C functions
* adds control.fail
Please takes a look and see if the APIs and their names make sense.
CC @pelikhan @abchatra @microsoftsam @riknoll @tballmsft
> support classes for python converter and other goodies

- libs/microphone/microphone.cpp
- libs/microphone/shims.d.ts
* Doc path and block ids change to reflect the new function names.
Change the enum for 'LoudnessCondition' to 'SoundCondition' also???
> Change 'loudness' to 'sound' for microphone ids

- libs/core/docs/reference/serial.md
- libs/core/docs/reference/serial/write-buffer.md
- libs/core/docs/reference/serial/write-line.md
- libs/core/docs/reference/serial/write-number.md
- libs/core/docs/reference/serial/write-string.md
- libs/core/docs/reference/serial/write-value.md
- libs/core/serial.cpp
- libs/core/serial.ts
These are fairly simple. I suppose we could add a description of serial communications and terminals and such but do we want to go there?
Also, **writeBuffer** is and was in _advanced_. It uses Buffer which is not documented yet. We can keep it in advanced or select it out in and entends doc.
> Update the serial docs.

- libs/accelerometer/sim/accelerometer.ts
- libs/accelerometer/sim/state.ts
- libs/core/sim/analogSensor.ts
- libs/core/sim/buttons.ts
- libs/core/sim/control.ts
- libs/core/sim/core.ts
- libs/core/sim/loops.ts
- libs/core/sim/pins.ts
- libs/core/sim/serial.ts
- libs/light/sim/neopixel.ts
- libs/light/sim/state.ts
- libs/lightsensor/sim/lightsensor.ts
- libs/lightsensor/sim/state.ts
- libs/microphone/sim/microphone.ts
- libs/microphone/sim/state.ts
- libs/music/sim/music.ts
- libs/music/sim/state.ts
- libs/switch/sim/state.ts
- libs/switch/sim/switch.ts
- libs/temperature/sim/state.ts
- libs/temperature/sim/temperature.ts
- libs/touch/sim/touch.ts
- tsconfig.json
Each package now has a `sims` folder that exports an interface for the simulator to implement. In the root of this repo I've added a `tsconfig.json` that builds all the sim folders together into one file called `common-sim.js`. I'll be opening a PR in pxt-core that builds that file as part of the target build and copies it into the target's `built` directory.
> Moving simulator code into common packages

- libs/core/hf2.cpp
- libs/core/hf2.h
- libs/core/pxt.cpp
See https://github.com/Microsoft/pxt-adafruit/issues/171
This will be compatible with bootloader 1.23, but also the earlier versions.
Also, it changes HID usage ID to 0xff97 0x0001 for easier identification in winrt (in line with bootloader 1.23).
Some testing would be in order.
> Bootloader v1.23 compat

- libs/music/music.ts
Fixes the "stop all sounds" API so that it doesn't stop sound forever.
> Set minimum rest time

- libs/core/docs/reference/pins/analog-set-period.md
- libs/core/docs/reference/pins/servo-set-pulse.md
- libs/core/docs/reference/pins/servo-write.md
- libs/core/docs/reference/pins/what-is-pwm.md
- libs/core/pins.cpp
* microbit DAL uses a wider duty cycle than standard servo ranges. Is
that the case here too? 1 ms to 2ms or is it 500 us to 2500 us?
> Add the 'PWM' topics

- libs/light/neopixel.ts
Adjusting pink, purple, and orange definitions to maximize contrast on the device while retaining color integrity in the browser.
Original: ![original](https://user-images.githubusercontent.com/16658549/28633139-ad01258a-71e7-11e7-8f81-f85c263a7674.PNG)
New: ![new](https://user-images.githubusercontent.com/16658549/28633146-b3bde61a-71e7-11e7-8a6f-32a3a46ec4e5.PNG)
> Neopixel colors

- libs/base/control.cpp
- libs/base/control.ts
- libs/base/docs/reference/control.md
- libs/base/ns.ts
- libs/core/control.cpp
> Enable help for base lib APIs.

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/axis.h
- libs/accelerometer/pxt.json
- libs/accelerometer/sim/accelerometer.ts
- libs/accelerometer/sim/state.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/304
The Y axis of the accelerometer doesn't match the markings on the circuit playground or the simulator behavior. This PR inverts that value and also fixes the simulator tilt up and down events so that they match the hardware.
> Inverting y axis in accelerometer

- libs/light/docs/reference/light.md
- libs/light/docs/reference/light/set-buffered.md
- libs/light/docs/reference/light/show.md
- libs/light/neopixel.ts
RE: https://github.com/Microsoft/pxt-adafruit/issues/348
> Add 'set-buffered.md', modify 'show.md'

- libs/light/neopixel.ts
- libs/music/melodies.ts
- libs/music/music.cpp
- libs/music/music.ts
Better defaults as you type in JS for showAnimation and music functions (instead of nulls and placeholders)
```
light.showAnimation(light.animation(LightAnimation.Rainbow), 500)
light.showAnimationFrame(light.animation(LightAnimation.Rainbow))
music.playSound(music.sounds(Sounds.PowerUp))
music.playTone(Note.C, music.beat(BeatFraction.Half))
music.ringTone(Note.C)
music.rest(100)
```
In conjunction with https://github.com/Microsoft/pxt-adafruit/pull/381
> Better defaults for animation and music methods in JS.

- libs/light/create.ts
- libs/light/docs/reference/light.md
- libs/light/docs/reference/light/create-strip.md
- libs/light/docs/reference/light/set-mode.md
- libs/light/docs/reference/light/set-pixel-white-led.md
- libs/light/neopixel.ts
- libs/light/test.ts
> light.createStrip

- libs/light/docs/examples/photon-bounce.md
- libs/light/docs/examples/photon-color-wipe.md
- libs/light/docs/examples/photon-raibow.md
- libs/light/docs/examples/photon-roundtrip.md
- libs/light/docs/examples/photon-wand.md
- libs/light/docs/reference/light.md
- libs/light/docs/reference/light/set-photon-mode.md
- libs/light/docs/reference/light/set-photon-pen-color.md
- libs/light/docs/reference/light/set-photon-pen-hue.md
- libs/light/neopixel.ts
Add a photon API that uses a color hue instead of RGB. Hue is needed to do cool math on colors. RGB does not cut it. The wording is changed so that there is no more confusion about this.
> support for hue in photon

- libs/light/neopixel.ts
In most scenario, the user has a single LED strip and the brightness buffer is not necessary: we can apply the brightess value when rendering.
This change optimizes for that case to retain memory in the common case.
> Lazy per-pixel brightness

- libs/cable/cable.ts
- libs/infrared/docs/reference/network.md
- libs/infrared/docs/reference/network/on-infrared-received.md
- libs/infrared/ir.ts
Split IR handlers into three handlers, only surfacing the one sending a single number. 
Did the same for cable. 
Added JSdoc and updated IR documentation
Tested with two Circuit playgrounds. (IR is very finicky)
Fixes https://github.com/Microsoft/pxt-adafruit/issues/392
> Update IR and cable blocks

- libs/core/i2c.cpp
`DEVICE_OK` is equal to 0, so we were inverting the check.
> Fixing the error checking in i2c read buffer

- libs/base/serial.ts
Change to "x" instead of x. Need to add quotes in the eg parameter.
Fix https://github.com/Microsoft/pxt-adafruit/issues/432
> Fix serial default value

- libs/light/neopixel.ts
Forgive the typo in the commit message. This make the neopixel animation blocks use a shadow block. Requires https://github.com/Microsoft/pxt/pull/3423
> Change the animation blocks to use shadow blocks

- libs/light/neopixel.ts
Fix for https://github.com/Microsoft/pxt-adafruit/issues/477
> bring back duration in animation

- libs/base/sim/control.ts
- libs/base/sim/loops.ts
- libs/base/sim/serial.ts
- libs/buttons/buttons.cpp
- libs/buttons/sim/buttons.ts
- libs/core/pins.cpp
- libs/core/sim/pins.ts
- libs/music/sim/music.ts
- libs/touch/sim/touch.ts
Fixes https://github.com/Microsoft/pxt-adafruit/issues/461
```
missing in sim: pxsim.BufferMethods.toHex
missing in sim: pxsim.serial.writeBuffer
missing in sim: pxsim.pxtcore.lookupComponent
missing in sim: pxsim.pxtcore.getMultiButton
missing in sim: pxsim.DigitalPinMethods.pushButton
missing in sim: pxsim.AnalogPinMethods.touchButton
```
> Fix sim shims

- libs/cable/cable.ts
- libs/cable/docs/reference/network/cable-send-number.md
- libs/cable/docs/reference/network/on-cable-packet-received.md
- libs/cable/docs/reference/network/on-cable-received-number.md
- libs/infrared/docs/reference/network/on-infrared-packet-received.md
- libs/infrared/docs/reference/network/on-infrared-received-number.md
- libs/infrared/ir.ts
> Fixup the 'network' docs a bit

- libs/base/control.cpp
- libs/base/pxtbase.h
- libs/base/sim/core.ts
- libs/core/codal.cpp
CODAL supports executing an event under different concurrency/queueing models.  This change exposes the CODAL events flags as a default parameter.  No change of behavior for existing targets.  For example of use, see 
https://makecode.com/_1xWL07DrvM23
> add plumbing for event flags

- libs/light/neopixel.ts
Fix show animation duration to remove optional parameter that breaks decompilation
Fixes https://github.com/Microsoft/pxt-adafruit/issues/505
> Fix show animation duration

- libs/light/docs/reference/light/neopixelstrip/show-animation-frame.md
- libs/light/neopixel.ts
show animation uses "autoShow" instead of forcing the buffering mode. This allows for calling multiple animation frame on different ranges before showing the entire strip.
> do not enforce color on show-animation-frame

- libs/core/docs/device/usb.md
Intro paragraph referred to uploading code on a micro:bit. I replaced that with @boardname@ to eliminate possible confusion
> Remove reference to micro:bit in usb.md

- libs/base/docs/reference/control/device-dal-version.md
A minor fix to the docs:
As implied by the original example, the return type is string, not number.
> Fix type of control.deviceDalVersion in docs.

- libs/light/neopixel.ts
Include missing 'neopixelstrip' sub-path for help urls in a few methods.
Found in https://github.com/Microsoft/pxt-adafruit/issues/559.
> Fix missing 'neopixelstrip' paths

- libs/base/pxt.cpp
- libs/base/pxtbase.h
- libs/core/codal.cpp
> add 500ms sleep on start to allow HID interfaces to "settle"

- libs/core/hf2.cpp
- libs/core/hf2.h
This seems to fix issues with WebUSB serial lockups - https://github.com/Microsoft/pxt-adafruit/issues/632
> Only enable serial on webusb after we got some command

- libs/core/hf2.cpp
- libs/core/hf2.h
see https://github.com/Microsoft/pxt-adafruit/issues/632
I think this should fix the issue above, but it might need testing if we're still getting serial data in WinRT app.
> Don't vent HID serial packets into space - wait for some HF2 message

- libs/accelerometer/docs/reference/input/acceleration.md
- libs/accelerometer/docs/reference/input/on-gesture.md
- libs/accelerometer/docs/reference/input/rotation.md
- libs/accelerometer/docs/reference/input/set-accelerometer-range.md
- libs/base/docs/reference/console/log-value.md
- libs/base/docs/reference/console/log.md
- libs/base/docs/reference/control/assert.md
- libs/base/docs/reference/control/device-dal-version.md
- libs/base/docs/reference/control/device-serial-number.md
- libs/base/docs/reference/control/millis.md
- libs/base/docs/reference/control/on-event.md
- libs/base/docs/reference/control/panic.md
- libs/base/docs/reference/control/raise-event.md
- libs/base/docs/reference/control/reset.md
- libs/base/docs/reference/control/run-in-parallel.md
- libs/base/docs/reference/control/wait-for-event.md
- libs/base/docs/reference/control/wait-micros.md
- libs/base/docs/reference/loops/forever.md
- libs/base/docs/reference/loops/pause.md
- libs/base/docs/reference/serial/write-buffer.md
- libs/base/docs/reference/serial/write-line.md
- libs/base/docs/reference/serial/write-number.md
- libs/base/docs/reference/serial/write-string.md
- libs/base/docs/reference/serial/write-value.md
- libs/core/docs/reference/pins/analog-read.md
- libs/thermometer/docs/reference/input/on-temperature-condition-changed.md
- libs/thermometer/docs/reference/input/temperature.md
First batch of mods for CP docs for sections to override in targets.
> Tag cp doc sections for overrides - 01

- libs/base/docs/reference/control/wait-for-event.md
- libs/base/docs/reference/serial/write-number.md
- libs/buttons/docs/reference/input/button/is-pressed.md
- libs/buttons/docs/reference/input/button/on-event.md
- libs/buttons/docs/reference/input/button/touch-sensors.md
- libs/buttons/docs/reference/input/button/was-pressed.md
- libs/cable/docs/reference/network/cable-send-number.md
- libs/cable/docs/reference/network/on-cable-received-number.md
- libs/core/docs/reference/pins/analog-set-period.md
- libs/core/docs/reference/pins/analog-write.md
- libs/core/docs/reference/pins/digital-read.md
- libs/core/docs/reference/pins/digital-write.md
- libs/core/docs/reference/pins/i2c-read-number.md
- libs/core/docs/reference/pins/i2c-write-number.md
- libs/core/docs/reference/pins/on-pulsed.md
- libs/core/docs/reference/pins/pulse-duration.md
- libs/core/docs/reference/pins/pulse-in.md
- libs/core/docs/reference/pins/servo-set-pulse.md
- libs/core/docs/reference/pins/servo-write.md
- libs/core/docs/reference/pins/set-pull.md
- libs/core/docs/reference/pins/what-is-pwm.md
- libs/infrared/docs/reference/network/infrared-send-number.md
- libs/infrared/docs/reference/network/on-infrared-received-number.md
> Section tagging for target overrides in docs - 02

- libs/lightsensor/docs/reference/input/light-level.md
- libs/lightsensor/docs/reference/input/on-light-condition-changed.md
- libs/lightsensor/docs/reference/input/set-light-threshold.md
- libs/microphone/docs/reference/input/on-loud-sound.md
- libs/microphone/docs/reference/input/set-loud-sound-threshold.md
- libs/microphone/docs/reference/input/sound-level.md
- libs/music/docs/reference/music/beat.md
- libs/music/docs/reference/music/change-tempo-by.md
- libs/music/docs/reference/music/note-frequency.md
- libs/music/docs/reference/music/play-sound-until-done.md
- libs/music/docs/reference/music/play-sound.md
- libs/music/docs/reference/music/play-tone.md
- libs/music/docs/reference/music/rest.md
- libs/music/docs/reference/music/ring-tone.md
- libs/music/docs/reference/music/set-output.md
- libs/music/docs/reference/music/set-pitch-pin.md
- libs/music/docs/reference/music/set-speaker-volume.md
- libs/music/docs/reference/music/set-tempo.md
- libs/music/docs/reference/music/set-tone.md
- libs/music/docs/reference/music/set-volume.md
- libs/music/docs/reference/music/sounds.md
- libs/music/docs/reference/music/stop-all-sounds.md
- libs/music/docs/reference/music/tempo.md
> Add section ids for target overrides - 03

- libs/accelerometer/accelerometer.cpp
LIS3DH is currently hardcoded but any type inheriting from codal::Accelerometer should work.
> allow configuration of accelerometer

- libs/base/docs/blocks/pause-until.md
A stub doc for the **pauseUntil**. This is a hybrid built-in/lib function. Doesn't play well with _/reference/loops_ or the like due to it's static block definition.
> A base doc for 'pause until'

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/spritemap.ts
- libs/game/tilemap.ts
It's more flexible to treat the "sprite type" as a layer and a bitmask. So a sprite can be part of multiple "layers" efficiently.
> converting sprite type to layer (bitmask)

- libs/game/scene.ts
- libs/game/sprite.ts
- libs/game/tilemap.ts
The tile map creates a sprite for every tile, even if the tile isn't an obstacle. This change makes it so that the tilemap only creates sprites for obstacles and draws all of the ghost-tiles at once. This improves render time by a lot (roughly 10x on the princess walking program).
> Improving tile map performance

- libs/game/animation.ts
- libs/game/pxt.json
- libs/game/sprite.ts
This defines two type of animations: one that advances based on movement and one that advances based on time.
The first two blocks are for movement; the way it works is that you add frames (images) for a movement direction and then the frames are automatically advanced when the sprite moves. Right now the threshold for advancement is not configured in blocks (not sure if that's useful or not).
The remaining blocks are for timed animations. Unlike movement animations, timed animations are not tied to a sprite so they can be created once and then fired multiple times on multiple sprites.
The `fireAnimation()` API just adds an animation to a sprite's animation queue and is non-blocking. We can't really make it blocking because that would totally break the game loop if you fired it within the …
> Adding animations for sprites

- libs/game/sprite.ts
Maybe we should discuss before merging this, but very often when you create a sprite you do it in a function (e.g. creating projectiles) and top-level event handlers are useless in that case. In general it is more useful for these blocks to be nestable.
> Make sprite handlers nestable

- libs/lightsensor/docs/reference/input/on-light-condition-changed.md
- libs/lightsensor/docs/reference/input/set-light-threshold.md
RE: https://github.com/Microsoft/pxt-adafruit/issues/707
> Update light sensor ref docs for level parms

- libs/game/spriteevents.ts
The SpriteKind enum starts at 0 so most the events appear to be broken right now (whoops)
> Allow a sprite kind of 0

- libs/music/melodies.ts
This at least gets us the old behavior in the toolbox (Power Up is selected by default) and the completions from Monaco are no longer broken (you get an empty string; not ideal but whatever)
Any other fix will require changes to PXT. Just to break down why this is an issue:
`playSound()` takes a string argument but uses a shadow block called `sound()` for the default value in blocks
`sound()` takes an enum argument and returns a string
In PXT when you give a default value for an argument then that value is sent to the shadow block in the toolbox and also the completion snippets in Monaco. Usually that works because the shadow block doesn't do anything to the value (shim=TD_ID) and so the same default argument for the shadow block also works for the parameter. Because the `sound()` shadow …
> Removing playSound's default value

- libs/core/buffer.ts
- libs/screen/image.cpp
This just adds `#ifndef __linux__` around memset/memcpy, but I also fixed line endings, hence the diff...
> Don't do custom memset on linux

- libs/game/camera.ts
- libs/game/hitbox.ts
- libs/game/physics.ts
- libs/game/pxt.json
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/temp.d.ts
- libs/game/tilemap.ts
Changes:
1. All tiles are now 16x16 px
2. Physics now has a maximum velocity of 15px per step
3. Collisions are now based on hitboxes and not overlaps
Hitboxes for sprites are calculated based on the content of the image but are always rectangular. Swapping images will recalculate the hitboxes. Sprites that are larger than 15x15 px have multiple hitboxes because there is a hard limit based on the tile size;, having a ton of hitboxes doesn't really have a noticeable impact on perf so we're all good.
Things I still need to do before merging:
1. Render hitboxes when debug is on
2. Figure out what to do if an image is changed directly (i.e. when you draw to an image we should maybe recalculate hitboxes)
*NOTE:* This PR only affects the TileMap. Overlap behavior is still exactly the same.
> New arcade physics

- libs/screen/image.d.ts
Changes we discussed offline. I think this is *technically* a breaking change for Image blocks because of that old buggy behavior where the block definition sets the name of the block input.
> Tweaking wording of image APIs

- libs/switch/switch.cpp
The cpp => ts code generator appears to look for a particular comment style when generating the `shims.d.ts` file. This patch fixes the comment style for the `switchRight()` method in `switch.cpp` so that the corresponding method gets generated in `switch/shims.d.ts`.
I ran a local pxt-adafruit editor with this change and confirmed that the `switchRight()` method gets generated, and that a `<switch right>` block shows up in the UI:
I also confirmed that the block works as expected, in this sketch:
I noticed that there was no block in the Adafruit editor representing the state of the switch, and I tracked it down to this comment.
> Fix comment style preventing switchRight method from being auto-gen'd

- libs/game/textDialogs.ts
Fixes Microsoft/pxt-arcade#195
To reproduce the bug you need to use the "show long text" block and display a message that will go up to a third row of characters. Then when you click space (a) an extra message block will show up with nothing in it. 
What the program was doing before was it would push rows of messages to a screen  and ultimately it pushed the last row of characters and reset the message to blank and push it once more.
To fix this I added a piece of logic so that whenever the message contains any string then it would push the row of the message to the screen. This works because there would be no point it pushing a row of nothing.
> Message should only be pushed if not empty

- libs/game/docs/reference/scene/get-background-color.md
- libs/game/docs/reference/scene/get-background-image.md
- libs/game/scenes.ts
- libs/game/sprite.ts
- Exposes backgroundImage and backgroundColor as API's (Fixes https://github.com/Microsoft/pxt-arcade/issues/190)
- "Stay in screen" is the default for setflag API (Fixes https://github.com/Microsoft/pxt-arcade/issues/183). We decided to skip another API for auto destroy.
- Get and Set image of the sprite are back to facilitate custom animations.
> Arcade bugs 

- libs/game/scenes.ts
Quick fix for microsoft/pxt-arcade#155 so we can use it in the course.
> Make scene.centerCameraAt() center camera properly / fix microsoft/pxt-arcade#155

- libs/game/physics.ts
- libs/game/prompt.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
- libs/game/textDialogs.ts
- libs/game/tilemap.ts
- libs/screen/fieldeditors.ts
Issues:
* fixes Microsoft/pxt-arcade#230
* resolves Microsoft/pxt-arcade#235
* fixes Microsoft/pxt-arcade#237
* fixes Microsoft/pxt-arcade#238 and issues relating to sprite.say causing overlaps with the sprite that created it (if it is SpriteKind.Player, and there is an overlap event between two SpriteKind.Player)
* fixes Microsoft/pxt-arcade#243 (same as 237)
* fixes jwunderl/pxt-corgio#3 (same as 243 and 237)
* modifying sprite.type moves sprite to proper array for arrayOfKind; I missed that it was exposed before
> Fixes for small Arcade issues

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
- libs/game/tilemap.ts
Fixes Microsoft/pxt-arcade#159, fixes Microsoft/pxt-arcade#218
Tilemap transparency, so background color / image shows through, instead of replacing all transparent portions with black
Issue 218 caused by hitboxes changing when a sprite's image is changed;  attempts to resolve this by bumping sprite back towards a 'safe' area if the sprite now extends into a wall. This implementation only attempts to resolve this in the case of a sprite that fits within a single tile, as otherwise there isn't a guarantee that the sprite actually fits anywhere on the map.
> Arcade tilemap bugs

- libs/game/scenes.ts
After writing up a lesson focusing on the new tiles implementation, setTileAt feels a bit clunky within blocks. I didn't add a way (exposed in the blocks) to get a tile's row and column, so they'd have to switch to TypeScript to get those properties from the tile, which feels a bit unnecessary.
Ways in which it might be improved:
- Add in row / column getters to tile that are exposed in blocks
- Make setTileAt accept a tile instead of a column and row (implemented)
- Make another function that takes in a tile, and leave setTileAt as is
@riknoll
> Interaction between scenes.setTileAt and getTile / getTilesByType

- libs/game/info.ts
Changed it so that the game considers the player to be out of lives when lives are negative.
Previously, if lives decreased by a number greater than the number of current lives, the game would not recognize this as lives being depleted.
> Game over when life is negative as well

- libs/game/textDialogs.ts
- libs/screen/fieldeditors.ts
* Resolves Microsoft/pxt-arcade#254; up and down arrow keys can be used to scroll through the pages of the text (down arrow key acting as an alternative to A to move to the next chunk, up arrow key going back a screen / page (if possible))
* Allow more of the dialog box to be used to display text
> showLongText tweaks

- libs/game/info.ts
- libs/local-multiplayer/info.ts
- libs/local-multiplayer/local.ts
- libs/local-multiplayer/pxt.json
Adding a few APIs for local multiplayer. ~Still in progress for score / lives; I'll finish it up tonight most likely as I have course material to finish during working hours :) (so do not merge for now)~
* ``control player {} with vx {} vy {}``
* Keeps track of player, so that if the player changes sprites movement switches to that sprite
* ``player {} sprite``
* Returns sprite currently attached to player
* add ``spritescreate``  as a shadow block for ``setPlayerSprite``; feels a bit ambiguous what belongs there to me with just a hole. (Bug with shadow blocks that causes it to be not ideal, though: Microsoft/pxt-arcade#249)
* getters for the colors of the HUD
* functions to turn on / off display of life / score / countdown
* scores and lives for players one and two, as per Richard's …
> local multiplayer APIs

- libs/game/info.ts
split from #414
_life getting set to null after calling _lifeOverHandler resets any behavior the player intended for resetting the lives; e.g. a continue screen where they want to set the player back to life with only a single life.
> Ability to reset life in `on life zero`

- libs/serial/serial.cpp
serial ctor takes codal::Pin, not PinName.
> fixing serial ctor

- libs/keyboard/keyboard.cpp
Automatic tostring on keyboard type.
> fix for https://github.com/Microsoft/pxt-maker/issues/12

- libs/game/tilemap.ts
Fixed issue that @riknoll brought up in Microsoft/pxt-common-packages#452
> Fixed issue with tile maps not being ID'ed correctly

- libs/accelerometer/accelerometer.cpp
Too many "when"s in the description.
RE: https://github.com/Microsoft/pxt-adafruit/issues/849
> Fix onGesture jsdoc description

- libs/switch/switch.cpp
The method description also includes the stuff from the ``@param`` line when there is a 'blank' line in between, an additional ``*`` as an empty line. Go figure.
```typescript
/**
* Do something when the slide switch is moved left or right.
*
* @param direction the direction the switch must be moved to trigget the event
*/
```
versus:
```typescript
/**
* Do something when the slide switch is moved left or right.
* @param direction the direction the switch must be moved to trigget the event
*/
```
RE: https://github.com/Microsoft/pxt-adafruit/issues/852#
> jsdoc parse error for onswitchmoved

- libs/controller/controller.ts
- libs/game/controller.ts
- libs/game/game.ts
- libs/game/sprites.ts
- libs/local-multiplayer/local.ts
Reword sprites.controlSprite so that it's a bit easier to understand for new developers; ``move {mySprite} with buttons`` and give vx / vy default values so they can be suppressed.
Reorder toolbox so that game is below controller ( closes Microsoft/pxt-arcade#349 )
Todo:
Also, since this will require an upgrade path already, I can add in the changes to tilemap apis here if we can agree on something ( https://github.com/Microsoft/pxt-arcade/issues/334 )
> Reword controlSprite and reorder toolbox

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/core---linux/platform.h
In particular, added `if (PXT_IN_ISR()) target_panic(PANIC_CALLED_FROM_ISR);`
> Enable some GC checks in normal builds

- libs/controller/docs/reference/controller.md
- libs/controller/docs/reference/controller/move-sprite.md
- libs/game/controller.ts
broken due to move from ``controlSprite`` to ``moveSprite`` with https://github.com/Microsoft/pxt-common-packages/pull/481.
Will need a bump to 5.1.7 to make everything match in arcade as well
> Fix move sprite docs

- libs/jacdac/batterydriver.ts
- libs/jacdac/jacdac.cpp
- libs/jacdac/jacdac.ts
- libs/jacdac/loggerdriver.ts
- libs/jacdac/messagebusdriver.ts
- libs/jacdac/pxt.json
- libs/jacdac/sensordriver.ts
- libs/jacdac/sim/jacdac.ts
Uses control packets to broadcast a battery level byte. Also brings back handleControlPacket, and basic support for fillControlpacket.
> Battery service over JACDAC

- libs/cable/cable.ts
- libs/core---samd51/i2c.ts
- libs/core---samd51/platform.h
- libs/core---samd51/shims.d.ts
- libs/core/i2c.cpp
- libs/core/i2c.ts
- libs/infrared/ir.ts
- libs/light/neopixel.ts
- libs/pixel/pixel.ts
> Enable i2c for samd packages

- libs/game/docs/reference/sprites/sprite/lifespan.md
- libs/game/sprite.ts
In Microsoft/pxt-common-packages#384, sprite lifespan was changed to measure in milliseconds. This updates the docs for lifespan to reflect this change.
> Fixed the docs for lifespan to reflect that it is measured in ms

- libs/game/textDialogs.ts
The image gets eventually GCed, but only after the frame has finished rendering. Typically we allocate right after game.splash, so this is a problem. Another solution would be pause(100) before exiting dialog, which would GC everything scene-related.
> Clear background image before exiting scene

- libs/core---samd51/platform.h
- libs/serial/serial.cpp
- libs/storage/GhostSNORFS.cpp
- libs/storage/GhostSNORFS.h
- libs/storage/pxt.json
- libs/storage/storage.cpp
``strogae`` requires DEVICE_USB so adding it at the project level and removing devices. (Might make LEGO unhappy, we'll see).
> enable deviceusb for storage project

- libs/game/sprites.ts
Previously, projectiles are placed by default on the edge of the screen (when a velocity is specified) such that it isn't fully shown, but rather moves into frame.
This is problematic when tile maps are used since they will be instantly detected as hitting the wall and will be destroyed.
This places the sprites fully on the screen when a tile map is present to prevent them from initially colliding with a tile map wall.
> Fixed bug with projectiles and tile maps

- libs/game/sprites.ts
default for ``variables_get`` is ``item``, which is not used for sprites
> Default to mySprite in createFromSprite

- libs/particles/particles.ts
- libs/particles/test.ts
On ParticleSource.destroy, leave particles alive until their lifespan runs out
Obligatory example:
https://makecode.com/_Wvhef4EgPfAp
```typescript
enum SpriteKind {
Player,
Projectile
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
const s = sprites.createProjectileFromSide(img`
2
2
`, 0, -100);
s.data = new particles.ParticleSource(s, 50, new particles.SprayFactory(30, 0, 50));
s.x = Math.randomRange(0, screen.width);
});
sprites.onDestroyed(SpriteKind.Projectile, (s) => {
if (s.data) (s.data as particles.ParticleSource).destroy();
});
```
> Don't immediately destroy particles on ParticleSource destroyed

- libs/particles/factories.ts
- libs/particles/test.ts
It's very common to use these in particle effects, so avoid duplication.
(first commit is actual change, second one is just adding examples to tests)
Bonus: fire! and spiral
> Particles: export cached sin and cos functions

- libs/mixer/melody.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/489
In our old editors (i.e. micro:bit), this code:
```typescript
control.runInParallel(function () {
music.playTone(Note.C, 1000)
})
pause(500)
music.playTone(Note.C5, 1000)
``` 
Would result in `C` playing for 500 ms and `C5` playing for 1000 ms (the second `playTone` interrupts the first).
With this change, both notes play for 1000 ms (with 500 ms of overlap).
This is a break from our old behavior, but I talked it over with @Jaqster and we think that this is a better model anyhow. Plus, it lets you do chords!
> Removing the ability to interrupt playTone in mixer

- libs/game/camera.ts
- libs/game/hitbox.ts
- libs/game/physics.ts
- libs/game/sprite.ts
**Fixes the following bugs**
Fixes Microsoft/pxt-arcade#375
Fixes Microsoft/pxt-arcade#448
Fixes Microsoft/pxt-arcade#517
Also fixes some issues with sprites clipping into walls when they should be bouncing. See [here](https://makecode.com/_FkP2g8eqcDHR). Sometimes the white block will bounce like it should, but sometimes it will clip into the bottom wall and get stuck. Thanks Joey for they example!
Moves code that deals with sprites interacting with tile maps to collisions section of the physics. So it 
now moves the sprites relative to the tile map collisions after it as moved the sprites their respective dxdt and dydt.
Reworks the collisions to be more efficient. Instead of checking every corner of every hitbox, only checking the points necessary. 
For example, if a sprite is moving …
> Reworked tile map collisions for various bug fixes and performance

- libs/game/background.ts
- libs/game/camera.ts
- libs/game/docs/reference/scene.md
- libs/game/docs/reference/scene/camera-shake.md
- libs/game/particles.ts
- libs/game/scene.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/tilemap.ts
Classic screen shaking impl -- looks better in game than on gif
* the shacking is added on top of the camera offset so that it does not result in permanent effect.
> basic screenshaking

- libs/base/eventcontext.ts
- libs/game/game.ts
- libs/game/info.ts
- libs/game/scene.ts
- libs/game/sprite.ts
The scene keeps track of time spent in the update loop and countdown use this timer instead of the system timer. As a result, when a menu is displayed, the game timer is not incremented.
Fix for https://github.com/Microsoft/pxt-arcade/issues/441
> scene time tracking

- libs/base/eventcontext.ts
- libs/game/scene.ts
- libs/screen---st7735/screen.cpp
This is used to limit hardware screen to 120px and display status data in the bottom 8px.
Also, use `onStats` to display stats.
Also, fix a race in screen update.
> Add support for status bar on hardware screen

- libs/screen/text.ts
Fixed printCenter to print in the center of the image instead of the screen.
> printCenter center of image instead of screen

- libs/game/controller.ts
Expand both `vx` and `vy` at once, rather than one at a time
> expand `moveSprite` velocities at same time

- libs/game/tilemap.ts
Must have gotten out of sync with a change of x and y to give the center, part of cleaning up https://github.com/Microsoft/pxt-arcade/issues/478
> fix place on tile to properly center sprite

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/screen/text.ts
Instead of allocating scaled bitmap data for entire font, do it dynamically while printing. While this is slower, it saves memory and allows for  arbitrary size for fonts, not only powers of two.
Fixes https://github.com/Microsoft/pxt-arcade/issues/596
Also, change "too big allocation" error code from 845 to 022 (to fit with 020 and 021).
@abchatra your call if you want this in, but seems low risk
> Scale the fonts dynamically

- libs/game/controller.ts
- libs/game/sprite.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/620
When changing a controlled sprite velocity to 0, override its sprite velocity so that it gets updated.
> Fixes pxt-arcade/#620

- libs/core---samd/platform.cpp
I guess we should check if this fixes I2C?
> Use TC4 not TCC0 on SAMD21

- libs/game/particleeffects.ts
- libs/game/sprite.ts
expose durations for all the sprite effects to match the normal `sprite.startEffect` ones, as that is really useful and pretty intuitive.
@pelikhan
> durations for particle effects consistency

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/accelhw.cpp
- libs/accelerometer/pxt.json
- libs/base/core.cpp
- libs/base/pxtbase.h
- libs/core---stm32/platform.cpp
- libs/core/i2c.cpp
- libs/core/i2c.ts
This allows several accelerometer drivers to be compiled in and one to be chosen at runtime using `ACCELEROMETER_TYPE` configuration variable (set in bootloader already).
By default only LIS3DH is compiled in, but this is overridden in Arcade.
Also, add function to use accelerometer as source of randomness.
> Allow dynamic selection of accelerometer used

- libs/game/particleeffects.ts
When using the destroy effect, if the duration provided is falsey, use a 1/4 of the default lifespan instead of just an arbitrary standard value. Looks better this way, as different effects really need a different duration to appear properly.
random effect pick on asteroid destroy with optional parameter not supplied:
Maybe it would be good to have a time picker with `default` (0) and `forever` (probably just an arbitrarily extra long time ) as options in addition to the current ones for the effects?
> destroy effects: use default effect lifespan instead of a standard lifespan

- libs/game/ask.ts
It's a bit too easy to skip through the ``game.ask`` dialogue when you're playing the game (/ mashing A or B) and completely miss it, so this adds a short pause between the prompt appearing and the player being able to make a decision, similar to the behavior in game over. https://github.com/Microsoft/pxt-common-packages/blob/1735068d37288dae04eeb0de30f86ff0a0c8b275/libs/game/game.ts#L190-L192
The 500ms pause is pretty arbitrary, but it's enough that the prompt will at least give them a chance to respond; 1000ms feels alright too, but 2000ms feels sluggish to me
(notice that the first few tries where I'm pressing a to fire the laser cause the prompt to never appear, with the game just appearing to be laggy for a second then the score going down)
> pause on game.ask so it isn't missed

- libs/game/controller.ts
Had two issues:
* this._pressedElapsed wasn't set until after the button was first released, so `+=`ing to it was resulting in NaN. any comparison with NaN results in false besides `!=`, so it always failed the first if in `__update`, and `NaN != NaN` is true so it repeated on each step no matter the `repeatDelay` and `repeatInterval` that was set
* the value being passed to `Controller.__update` was in ms, but was being multiplied by 1000 resulting in each button getting a value in μs instead of ms and updating 1000* too fast
> Fix controller button repeat

- libs/game/controller.ts
- libs/game/scene.ts
- libs/game/textDialogs.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/686
The scene needs to track the controlled sprites and register the event handlers, but the controllers can stay global.
> Have the scene register controller handler on init

- libs/screen---st7735/screen.cpp
More handling of the screen missing case. CPX would crash if screen was referenced.
> do not instantiate screen singleton if pin missing

- libs/accelerometer/accelerometer.cpp
- libs/accelerometer/accelhw.cpp
If ACCELEREMETER_SDA/SCL not provided, default to SDA/SCL. 
If not configured properly, gracefully ignore accelerometer.
> allow standalone accelerometer

- libs/game/game.ts
Fixes Microsoft/pxt-arcade#759
This adds a black bar to the footer of a dialog so that the footer text can be read more clearly.
> Added black background to distinguish dialog footers

- libs/game/controller.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/755
Right now if you use the `moveSprite()` API, you can't ever change the velocity directly because it gets immediately overwritten (the controller takes complete control of the velocity even when buttons aren't being pressed). This change makes it so that it only controls the velocity when there is actual input.
Here's an example:
In the current editor, nothing will happen when the apple and lemon overlap because the controller is controlling the lemon's velocity. With this change, you get this:
The pink arrows are the button's I'm pressing in that gif.
Also, I made it so that pressing directional buttons in opposite directions now cancels out the movement. Before we arbitrarily gave precedence to the up and left buttons.
@jwunderl …
> Let user override controller velocity when there is no input

- libs/game/particleeffects.ts
Calling the factory early makes each source refer to the same factory, which leads to some unintuitive behaviors when the factory maintains state.
Easiest example of this is in the space destroyer game on the home page, when you fire the laser it creates a short radial effect. Currently, this will continue to rotate around weirdly each time the effect is invoked
it should just start from scratch each time, sending particles in the same direction.
Example of effects 'synchronizing' when called multiple times: https://makecode.com/_H1hgpi3g4HH2
Current behavior (notice it speed up instead of creating a second halo, and left and right halo both keep pace with eachother):
After this change (notice that the radials 'start' at the beginning, rather than where the previous one is):
> Give effects their own factories rather than shared across same effect

- libs/base/trig.cpp
Trig functions got moved out of Math_ by accident.
> move trig functions back under Math_

- libs/servo/docs/reference/servos.md
- libs/servo/docs/reference/servos/run.md
- libs/servo/docs/reference/servos/set-angle.md
- libs/servo/docs/reference/servos/set-pulse.md
- libs/servo/docs/reference/servos/set-range.md
- libs/servo/docs/reference/servos/set-stop-on-neutral.md
- libs/servo/docs/reference/servos/stop.md
- libs/servo/servo.ts
**Comment**: Seems to be a decompile to field editor problem in docs:
RE: #720
> Servo docs update

- libs/game/sprite.ts
Before:
<image src="https://user-images.githubusercontent.com/6453828/53916365-56dff000-4062-11e9-810b-a35ecb70101c.png" height="400" />
After:
<image src="https://user-images.githubusercontent.com/6453828/53916375-5e9f9480-4062-11e9-9031-61eac7265bda.png" height="400" />
> Fix blockly category on sprite image blocks

- libs/game/particleeffects.ts
- libs/game/particles.ts
Add a relative priority ranking, so that developers can choose which effects should be destroyed when removing effects is deemed necessary so that the game doesn't crash.
This is used to give scene effects a higher priority, so that they are not destroyed when too many smaller effects are triggered at once
I didn't add in a dirty bit for sorting the array for now (e.g. scene's ``Flag.NeedsSorting``), as the array being sorted will never have more than ``MAX_SOURCES`` (7) elements for the time being. If / when a PID controller is implemented for controlling particle effects, probably would want to revisit that.
@pelikhan for handling scene effects turning off when the player causes too many effects to be created at once: here's space destroyer with firing changed to repeat and star field …
> add priority ranking for sources (don't destroy scene effects)

- libs/animation/animation.ts
- libs/game/scene.ts
I was getting some pretty poor frame rates on hardware in a platformer I'm making as games went on even when the number of elements on screen was relatively static.
Looks like the primary cause was a memory leak in animations, as the updates were keeping old sprites around and trying to update them forever rather than ignoring them after they were destroyed. For example: https://makecode.com/_A6i4uucDtdpu
So this fixes the memory leak
> Do not maintain animations for destroyed sprites

- libs/game/controller.ts
#704 made it so the controller api only applies when pressed, but also made it always apply when pressed, which changes the nice behavior that it ignores the axes that are 0 (e.g. the jumping in this game https://makecode.com/_8ajcjogxp6hF gets messed up as it continually overrides the ``vy`` whenever the left or right button was pressed, setting vy to 0)
This just returns the behavior of the current beta branch - don't change a sprite's ``vx`` or ``vy`` if the speed is set to 0 for that value in moveSprite
> don't change sprite velocities in moveSprite when set to 0

- libs/servo/docs/reference/servos.md
- libs/servo/docs/reference/servos/run.md
- libs/servo/docs/reference/servos/set-angle.md
- libs/servo/docs/reference/servos/set-pulse.md
- libs/servo/docs/reference/servos/set-range.md
- libs/servo/docs/reference/servos/set-stop-on-neutral.md
- libs/servo/docs/reference/servos/stop.md
Include a link to the Kitronik servo guide in the servo pages.
https://www.kitronik.co.uk/pdf/a-brief-guide-to-servos.pdf
> Insert kitronik servo guide link

- libs/game/info.ts
- libs/mixer/melody.ts
MelodyPlayer class is private, and I guess should be.
Visibilty is exposed in PlayerInfo and I guess should be.
> Fix private/export modifier on types

- libs/gamepad/gamepad.ts
- libs/jacdac-drivers/gamepadclient.ts
Unfortunate typo in ``GamepadButton`` enum. Don't take this if it's too much of a breaker.
> Gamepad button enum fix

- libs/datalogger/datalogger.ts
- libs/datalogger/docs/reference/datalogger.md
- libs/datalogger/docs/reference/datalogger/set-separator.md
- libs/datalogger/storagedatalogger.ts
Datalogger
Values of `0` are omitted from the text rows on output. Seems that ``array.join()`` treats values of `0` as `null` and drops them out of the result string. See below:
```typescript
let testRows: number[][] = []
testRows = [[23, 9, 56], [87, 0, 45], [75, 0, 0], [0, 32, 45]]
for (let row of testRows) {
console.log(row.join(','))
}
```
result:
```
23,9,56
87,,45
75,,
,32,45
```
A suggested fix is to convert the row to string prior to formatting and output.
> Add the option to change separator in datalogger

- libs/base/docs/device/error-codes.md
- libs/base/docs/reference/control/panic.md
List the panic codes in a general 'Error Codes' page for Base lib. This page can be overridden in targets for their own extended codes.
> Error codes doc

- libs/screen/fieldeditors.ts
Relies on https://github.com/Microsoft/pxt/pull/5422
Makes all image shadow blocks duplicate on drag. Safe to merge before the pxt change is merged.
> Turning on duplicate on drag for image blocks

- libs/base/control.ts
- libs/base/docs/reference/text/to-string.md
requires https://github.com/Microsoft/pxt/pull/5424 to behave nicely with variable reporters [merged]
Add a top level ``toString`` block to allow for conversions from numbers / any object to text. This could also be handled with join currently, but that is a bit unintuitive for new developers; see https://github.com/Microsoft/pxt-microbit/issues/1637
To show up in Microbit I'll have to duplicate this over to one of the libs there, will do that once this one is finalized to make sure they're consistent
> Add top level `toString` block

- libs/base/pxtbase.h
will fix https://github.com/Microsoft/pxt-microbit/issues/1941, still need to make a PR to the extension repo once this is merged though
moves the macros from microbit to be structures themselves
> Macros for accessing buffer and string data across versions

- libs/game/game.ts
closes https://github.com/Microsoft/pxt-arcade/issues/872
Changed parameter name mainly to disambiguate upgraded / un-upgraded scripts for the upgrade rules.
> Always show win/lose toggle in game.over

- libs/game/controller.ts
fixes https://github.com/Microsoft/pxt-arcade/issues/767
Block sets default for **all** buttons; setting them on a per - button basis is advanced / typescript only.
Also fixes a bug where the time before the first repeat was the repeatDelay plus the repeatInterval, rather than just the repeatDelay
> block to set defaults for repeat events

- libs/base/basic.ts
Add basic.forever for compatibility with microbit; it's absence was noted in https://github.com/Microsoft/pxt-arcade/pull/897
> add missing basic.forever for compatibility with micro:bit

- libs/screen/image.cpp
Translator found spelling. Shows up in jsdoc strings.
RE: https://crowdin.com/translate/kindscript/2961/en-zhtw#118775
> Iffy jsDoc on 'isMono'

- libs/core/hf2.cpp
- libs/core/hf2.h
- libs/core/usb.cpp
This adds code removed in https://github.com/Microsoft/pxt-common-packages/pull/616 (under #ifdef)
> Bring back HID for WinRT app

- libs/base/eventcontext.ts
Event context maintains a set of idling callbacks
Requires https://github.com/Microsoft/pxt/pull/5530
> support for idling

- libs/base/control.ts
- libs/core---linux/control.cpp
- libs/core/control.cpp
Completely untested.
See https://github.com/microsoft/pxt-arcade/pull/958
CC @jwunderl
> Add control.ramSize()

- libs/game/particles.ts
requires https://github.com/microsoft/pxt-common-packages/pull/816
Base max sources off of the available ram
Max sources are all pretty arbitrary off of what seemed to work well on hardware
> base max sources off of available ram

- libs/light/neopixel.ts
- libs/light/transitions.ts
It messes up Python
@darzu you should be able to recreate a repro out of this. This is different from the unexported enum.
> don't use Easing type

- libs/game/physics.ts
Fixes Microsoft/pxt-arcade#585
Currently on some PCs the callback loop is executed too quickly and when the delta time is converted to a fixed point number, the number is too small to accurately represent as a fixed point number. 
This change switches to use milliseconds when using fixed point math so that the delta time is a larger value.
> Sprite velocity fixes

- libs/game/systemmenu.ts
Set minimum brightness to 10 when changing by menu, so that the game doesn't become unusable without a reset
> Don't let user turn off screen brightness fully from menu

- libs/game/temp.d.ts
Just noticed after editing these that they only affect the tooltips from vs code / etc (as the parameter names are already good in the actual implementations in pxt), but still nice to change for future clamping in vs code.  Parameter names here match the ones you'd see in the editor now
> Cleanup some tool tips when editting locally

- libs/game/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/963
> don't return undefined for tile outside map

- libs/accelerometer/accelhw.cpp
Silently fail when we are unable to communicate with the accelerometer, instead of hard crash.
> don't crash when accelerometer is broken

- libs/game/particleeffects.ts
- libs/game/particlefactories.ts
fixes https://github.com/microsoft/pxt-arcade/issues/976
A handful of the particle effects were being positioned on the screen solely off of their position, rather than respecting the camera position. (For the clouds this was intentional to make them move across the screen ignoring the relative change in position of the player, but that behavior is a bit wonky / messes things up when it's in the tilemap).
Also changes a handful of default rates to make the effects look a bit nicer
> fix positioning of particles when using tilemap

- libs/game/systemmenu.ts
(also remove redundant mins/maxes as that's handled in setBrightness)
> keep volume aligned to 32 when using systemmenu

- libs/light/neopixel.ts
fixes https://github.com/microsoft/pxt-adafruit/issues/1037
Should probably just remove the block for this, or remove the easing param, as it doesn't decompile and requires the handler as is - wanted to check if it's needed anywhere @pelikhan?
> hide setGradient block

- libs/mixer/melody.cpp
- libs/mixer/melody.h
- libs/mixer/melody.ts
This allows for you to ramp the frequency of a sound over time. 
Adds the ```^``` operator which is followed by which frequency the sound should end at. For example,
```
music.playSound("!1300,200^50")
```
will play a sound that starts at 1300 hz, but ramps down to 50 hz over the course of 200 ms.
> Add ability to ramp frequencies of sounds

- libs/base/core.cpp
- libs/base/gc.cpp
- libs/core---samd/platform.cpp
- libs/core---stm32/platform.cpp
- libs/core/pxt.h
Skip jacdac if ndef CODAL_JACDAC_WIRE_SERIAL
> guard jacdac build in linux

- libs/edge-connector/pxt.json
The edge-connector packages also loads in the "serial" package (micro:bit compat)
> Edge serial

- libs/jacdac/jacdac.cpp
Don't try to compile jacdac if CODAL_JACDAC_WIRE_SERIAL is missing.
> Guard jacdac

- libs/game/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1015
> fix null dereference if TileMap not set

- libs/light/neopixel.ts
Restore animation behavior (broken while trying to handle longer strips in fashion)
See https://github.com/microsoft/pxt-common-packages/blame/2cc52cf710412941a0c496b52d669511be824d6b/libs/light/neopixel.ts#L1317
> fix animation of rainbow in Adafruit

- libs/light/onboardstrip.ts
Adds a check to make sure there actually is any dot star leds before making the onboard strip an apa102 strip.
Is the same fix and is just a back-port of microsoft/pxt-adafruit#1059
> Add check for dot star leds before making APA102 strip

- libs/base/core.cpp
This no longer prints `1233.99999999999` instead of `1234`.
Fixes https://github.com/microsoft/pxt-microbit/issues/2019 - to be cherry-picked to master if everything works out
Tested on following numbers:
```
13.7, 1234.56789, 1073741825,
10737418250,
107374182500,
2000000001, 1, 0.1, 0.00001,
1e101, 1.23456789e90
```
> Better double->string conversion

- libs/controller/controller.ts
- libs/controller/pxt.json
- libs/game/controller.ts
fix https://github.com/microsoft/pxt-arcade/issues/1064; leave the functionality in typescript, and move the block to the controller extension with other advanced behaviors
> move block for repeat event defaults to controller extension

- libs/core/light.cpp
Fixes https://github.com/microsoft/pxt-arcade/issues/1047
There was already neopixel support in codal-stm32 contributed by Riven from Kittenbot. It seems to just work. It will break if we run at higher frequency, but we can fix it when we have these.
> Enable neopixel support on STM32F4

- libs/game/spritekind.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1078; backwards compat, and allow for hardcoded user kinds without conflicts
> set projectile to always be 1, and raise other initial kinds

- libs/base/sim/control.ts
- libs/core---linux/control.cpp
- libs/core---samd/shims.d.ts
- libs/core/shims.d.ts
- libs/core/usb.cpp
- libs/power/power.ts
> Don't sleep on USB

- libs/game/scene.ts
Use an object with numeric indexing instead of an array; this way only the indices used will actually be stored. This only really matters when kinds are arbitrarily high, which was previously rare (but now the norm).
On current master this doesn't cause crashes in most cases as there's enough memory in the devices to store 1000 empty indices, but if you raise the initial spritekind to 10000 it will immediately crash (on jumpy platformer at least), and currently is just taking a huge chunk of memory unnecessarily.
I felt like I was forgetting something since about an hour after merging https://github.com/microsoft/pxt-common-packages/pull/869, glad I figured it out before going to bed :)
> use an object to store spritesByKind instead of an array (low density)

- libs/game/sprite.ts
Just noticed the z index was messed up for all sprites if you don't explicitly set them to something non zero - e.g. in https://makecode.com/_hyW4WRR1eVaD the hero should be on top of any spawned shapes rather than behind them, because it has a z index of 5.
This is because the constructor is explicitly setting the _z field to 0, rather than passing it through the setter function for z which tells the scene to sort the sprites. So when a new sprite is created, it will be overlayed on top of all other sprites until the z index for another sprite is changed (to a new value - explicitly setting them to 0 won't work as it will be the same as the one set in the constructor and ignored). 
Maybe worth taking as a patch to the live site? Not a regression from the old one but it's a really simple …
> fix sprite z index sorting

- libs/animation/animation.ts
- libs/game/game.ts
- libs/game/info.ts
- libs/game/physics.ts
Clean up info and animations state so they stay relative to the scene
fixes https://github.com/microsoft/pxt-arcade/issues/1101
also makes the game on push and and pop handlers pass the old scene, so that can be used when relevant
Will test this a little bit more before merging, as it seems pretty easy to break things here
https://makecode.com/_9FbM8q7mDW8w
```typescript
info.setScore(0)
info.setLife(3)
info.changeScoreBy(1)
info.startCountdown(1)
info.onCountdownEnd(function () {
info.changeScoreBy(1)
})
pause(2000)
game.pushScene()
info.changeScoreBy(15)
info.startCountdown(1)
info.onCountdownEnd(function () {
info.changeScoreBy(15)
})
pause(2000)
game.popScene()
pause(1500)
info.onLifeZero(function () {
info.changeScoreBy(200)
})
while (true) {
info.changeLifeBy(-1)
pause(750)
}
``` …
> Scenify info and animations

- libs/base/pxt.cpp
- libs/base/pxtbase.h
- libs/core---vm/vmcache.cpp
This also makes sure to interface with GC correctly in Object.keys() (though this wasn't the cause of the crash)
@jwunderl this fixes your 843
> Fix crash in Segment::setLength manifesting in Object.keys()

- libs/game/physics.ts
- libs/game/sprite.ts
Make small adjustments in position respect the tile map; this makes it so behaviors like this don't cause the sprite to ignore the tile map:
Also reorders the tile collision handler detection; it would overwrite the change if you tried to change position in the event handler, which is invoked from ``sprite.registerObstacle``, making the end position incorrect if you e.g. change the scene and move the sprite to the beginning of the level. (I think I want to change this to behave like sprite overlap events, with the 'run in parallel but drop when running' behavior, though - I'll add that change here in a second unless anyone strongly opposes it, as it feels very weird to have different behaviors between the two main types of 'collisions')
> Make small position adjustments respect tile map

- libs/base/console.ts
make ``console.log`` accept ``any`` like the dom version. Possibly noteworthy that ``text.shadowOptions.toString=true`` makes the blocks version already behave like this, except the string coercion shows up in the javascript after decompiling instead of just being part of log
@mmoskal are there any potential perf / object size issues that would block this?
> make console log take any to match browser

- libs/screen/image.cpp
Fixes https://github.com/microsoft/pxt-arcade/issues/1133
> Fix memory mgmt in Image.doubled()

- libs/game/console.ts
splits up lines so multi line strings fit nicely into the console overlay; e.g. this:
instead of this:
this was annoying with https://github.com/microsoft/pxt-common-packages/pull/886, as the pretty printing wasn't that pretty due to everything overlapping
Also add optional parameter to to ``.setVisible``, so that people can set the color if they want to
https://makecode.com/_1y3W2ceD8C3J
> handle multi line strings in console overlay

- libs/game/game.ts
- libs/game/textDialogs.ts
-  [x] Fix splash dialogs to support unicode
-  [x]  deprecate "dialogfont" as the font as to be computed based on the text
```
game.splash("你好", "世界")
game.ask("你好")
game.showDialog("你好", "你好")
game.showLongText("你好", DialogLayout.Bottom)
```
> Splash loc

- libs/game/physics.ts
extend the bounds checking slightly when checking collisions to the left and up, to more consistently identify these collisions. (this matches the behavior when moving rightwards / downwards; that was added in a commit saying it was to fix an off by one bug, so matching the reasoning here). Easiest way to see the difference is to put logs inside the ``tm.isObstacle`` check below these changes, and shove the sprite into the wall (e.g. with the discord game below); collisions to the right happen at a rate of about ~10/s, where collisions to the left occur at about ~4-5/s (with this change they're equal rates)
The bug is easy to see in this game from discord: https://makecode.com/_dui0MTYamRjk (might need to use beta for it to work); try running into the left wall / jumping off it vs the …
> fix off by one bug for tile collisions in left / top

- libs/base/console.ts
re: discussion in https://github.com/microsoft/pxt-common-packages/pull/885
~Had to work around minor bug: https://github.com/microsoft/pxt-arcade/issues/515~
Noticed that the default toString for objects is ``[Object]`` on pygamer in arcade, rather than ``[object Object]``; could fix that I suppose, as it looks like it's defined here https://github.com/microsoft/pxt-common-packages/blob/68c76b90636c9dcd9ec3de0774a06e5d58ec0316/libs/base/core.cpp#L408
Also, the ``console overlay`` doesn't handle new lines nicely (it just offsets by a single line per console.log rather than by how many lines it takes up), will fix that separately
here's the test I used: https://makecode.com/_9vd7opftoaqP
```typescript
game.consoleOverlay.setVisible(true)
const myObj = {
a: "a",
b: "b",
c: "c",
d: "d",
e: …
```
> Console inspect and pretty printing for objects / arrays in console.log

- libs/game/physics.ts
fix https://github.com/microsoft/pxt-arcade/issues/1143
behavior is effectively the same unless a tile collision event accesses or updates velocity in the same axis as the collision; in that case:
* if just reading, the event will have access to the velocity as it collides, rather than the velocity that will be applied after the collision
* if changing the velocity, the event get priority over the default collision handling - bounces and stopping won't occur (useful if you only want it to e.g. make the ball only bounce on certain tiles). If the speed has changed but is still moving in the same direction as the collision, it will stop moving (to prevent retrigger tile collision); otherwise it will update trajectory here on the next step: …
> defer tmap velocity changes until after overlap events; allow override

- libs/mouse/mouse.cpp
The left/right button mapping got fixed in CODAL -> https://github.com/lancaster-university/codal-core/blob/master/inc/drivers/HIDMouse.h#L35
> fix swapped left/right mouse buttons 

- libs/game/numberprompt.ts
Modify @ChaseMor's commit to allow `game.askForNumber` prompt to span the width of the screen, rather than restrict it to the width of the number pad.
Before:
After:
> Allow game.askForNumber prompt to span screen width

- libs/game/basesprite.ts
- libs/game/particles.ts
- libs/game/renderable.ts
- libs/game/sprite.ts
Quick patch for https://github.com/microsoft/pxt-common-packages/pull/917 that I noticed after merging and testing again; I made a typo of having the namespace as ``sprite`` instead of ``sprites``, which causes some params for event handlers to be renamed unnecessarily on compilation / could conflict with any top level variables named sprite.
> switch BaseSprite namespace from sprite to sprites

- libs/game/particles.ts
re: https://forum.makecode.com/t/possibly-bogus-compilation-errors-from-beta-beta-makecode-arcade/431; just checked my old branch and I had removed it there but not pushed by accident :(
issue is that duplicate fields with the base class are failing to compile for hardware but succeed in sim; here ParticleSource had the id field redeclared accidentally
> remove id field conflicting with base class

- libs/core---samd/platform.cpp
CPX has SWD pin mapped to PIN_SPEAKER_AMP. Debugger needs to be enabled with:
```
namespace userconfig {
export const SWD_ENABLED = 1
}
```
(similar on metro-m0, where the SWD is on neopixel)
this code comes from core/platform.cpp which was used with cpx mbed target
> Add SWD remapping code to core---samd

- libs/core---samd/platform.cpp
Note that the JACDAC timer on TC4-5 will conflict with PWM on A6, A7.
A2, A3 have PWM on TCC1, so should be fine.
@jamesadevine can jacdac use 16 bit timer? TCC2 or TC5 would be good.
> Move lowTimer on SAMD21 from TC3 to TCC0 to avoid conflict with DAC

- libs/core/spi.cpp
Requires https://github.com/microsoft/pxt/pull/5821 to function, but won't break build anyways
> Allow null as either argument to spi.transfer()

- libs/core---samd/platform.cpp
now PWM, jacdac, and IR should all work at once
Still, the A6/A7 should be able to do PWM (with TC4), but it seems to mess up TC5; not a regression there though.
> Move timers to accomodate jacdac, IR, PWM

- libs/cable/cable.cpp
- libs/core---samd/platform.cpp
- libs/infrared/ir.cpp
Move second IR timer to TC4 (because TCC2 is also used by jacdac)
Test program
```
input.buttonA.onEvent(ButtonEvent.Click, function () {
network.infraredSendNumber(Math.randomRange(0, 10))
})
input.buttonB.onEvent(ButtonEvent.Click, function () {
music.baDing.play();
})
network.onInfraredReceivedNumber(function (num) {
light.graph(num, 10)
})
forever(function () {
basic.pause(1000)
pins.LED.digitalWrite(true)
basic.pause(1000)
pins.LED.digitalWrite(false)
})
```
> Fixes Adafruit IR

- libs/light/defaultlights.ts
- libs/light/neopixel.ts
Not sure there's an easy way to add a different color for endColor? .defl / eg / etc don't work immediately, seems like it would need either an extra color picker https://github.com/microsoft/pxt/blob/33806faf215ce233b4cf946f0ce8f750f5f924a6/libs/pxt-common/pxt-helpers.ts#L468, or something of the sort. Will look into that separately
> fix neopixel light gradient

- libs/base/pxtbase.h
- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
This makes get/setCore non-inline, but the stuff they call is now inline
Now also adds Image.blitRow method which scales a copies a row of pixel from one image to another, for example to speed up this: https://makecode.com/_KgyAkARse6Hm
> Add Image.blitRow and optimize get/setPixel

- libs/game/controller.ts
- libs/game/game.ts
- libs/game/scene.ts
- libs/game/spriteevents.ts
Make some interfaces into classes for minor performance gains / memory efficiency; shouldn't make too much of a difference, but some of these end up being used each frame (ControlledSprite, GameForeverHandler) / in parts that may be perf-sensitive (SpriteHandler and OverlapHandler are used in physics), and there tend to be a decent amount of these in larger programs
> Classify some interfaces

- libs/screen/image.cpp
- libs/screen/image.d.ts
- libs/screen/image.ts
- libs/screen/sim/image.ts
needed to be able to compare images to make new animations be able to continue properly when you play the same one over again
I think https://github.com/microsoft/pxt/pull/5791 might be causing an issue compiling (to meowbit at least, I would assume all hw) now? Had to checkout a commit before to test this on hw, just giving a generic error: ``error: main.ts(1,1): error TS9200: Assertion failed``. Fun fact though, compilation is fast enough that it's actually pretty hard to read output.txt when it gets overwritten; need to stop the auto-re-running after pressing download so that it won't clobber the output I guess.
> Add Image.equals(otherImage)

- libs/game/scene.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
add a block for making a sprite follow another one
~Had a version where turnRate was in degrees, but it slowed things down pretty significantly; this version the turnRate is very much arbitrary, but it has a pretty decent range of behaviors as written between 'orbit around player a bit before hitting' at 0.1 and 'immediately turn towards player' at ~ 5+; not sure that behaviors worth exposing, maybe better to just set it as a constant for now and revisit / add a parameter later. I guess it could also just use an enum (TurnSpeed.VerySlow, ...) and still be able to adjust it later~ dropping turnRate from the block, leaving as a javascript only option and we can adjust it later if we want to give it some more meaningful value
Couple quick examples
https://makecode.com/_JbWix6U3e2du …
> Add block to make one sprite follow another

- libs/game/game.ts
@riknoll was right
make game.forever (used in arcade to tie forever to the game loop)'s timeout match the default of loops.forever
> fix forever timeout to match loops.forever

- libs/core---stm32/platform.cpp
- libs/settings/SAMDFlash.cpp
Accelerometer on meowbit locks up after a while. Sometimes. Better not use it unless requested.
Also, add forgotten call to reanable flash on samd (without cache SAMD is about 3x slower)
> Disable seeding PRNG from accelerometer

- libs/mixer/docs/reference/music/play-melody.md
- libs/mixer/melody.ts
Add a page for the new **playMelody()** function.
RE: https://github.com/microsoft/pxt-adafruit/issues/1118, https://github.com/microsoft/pxt-arcade/issues/1276
> Add 'play Melody' reference page

- libs/game/textDialogs.ts
- libs/screen/fieldeditors.ts
add some filters; make dialog frame and tile blocks only show frames / tiles in gallery, and exclude those from the create sprite gallery (except for the ones that make sense to have in both, e.g. rocks  / trees / flowers)
> add filters for a few image types

- libs/game/controller.ts
- libs/game/sprite.ts
Tweak colors of blocks to align them with WCAG 2.0 Level AA standards to address accessibility concerns.
Additional details can be found in https://github.com/microsoft/pxt-arcade/pull/1288
> Adjust block colors to align with WCAG 2.0 Level AA standard

- libs/game/particleeffects.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1254
won't do anything without https://github.com/microsoft/pxt/pull/5871, but that should be in whatever bump this gets included in anyways
> make clear particle effects allow sprites in blocks

- libs/game/particleeffects.ts
This reverts commit d7f76f0a8f91cead5c0388e73b6a31c62ab613ae from #960.
Seems to be exposing a weird compilation bug when targeting hardware, reverting until that is identified / fixed. Will unfix https://github.com/microsoft/pxt-arcade/issues/1254 for now
> Revert "make clear particle effects allow sprites in blocks"

- libs/game/particleeffects.ts
cherry picking to stable branch
This reverts commit d7f76f0a8f91cead5c0388e73b6a31c62ab613ae.
> [stable6.15]Revert "make clear particle effects allow sprites in blocks (#960)"

- libs/game/particleeffects.ts
This reverts commit d7f76f0a8f91cead5c0388e73b6a31c62ab613ae.
cherry picking https://github.com/microsoft/pxt-common-packages/pull/961 to stable
> [stable6.15] Revert "make clear particle effects allow sprites in blocks"

- libs/game/physics.ts
fixes  https://github.com/microsoft/pxt-arcade/issues/1242 
Issue was that it was hitting the same tile in some circumstances in both corner checks; this makes it so we only trigger collision events once per tile type per direction per frame (which has a more consistent behavior if you're e.g. standing on lava, as it won't trigger collisions with the two separate lava tiles)
test case https://makecode.com/_9UaUkePyTDhe
> only collide once in each direction per tile color

- libs/game/particleeffects.ts
clear only the effects attached to the given sprite, rather than any attached to an anchor at the same position. Fixes situations like https://makecode.com/_2fffuuL8PWpf, where the clear effect accidentally destroys the background, too
> only clear particles explicitly attached to sprite / anchor

- libs/game/camera.ts
Fix issue where ``centerCameraAt`` breaks when used in events with tile maps. 
In my case, an `on game update` event that was being used to move the camera between sprites smoothly caused the screen to flash seemingly randomly / things to be positioned incorrectly as the 'fix' with respect to the tile map was being deferred to the next update and immediately getting overwritten with the un-tilemapped value each frame.
It seems kind of not-ideally set up currently, though; can't call the setters from the constructor as it will result in a stack overflow when the scene is created (and similarly, if the scene constructor were to try to set an offset it would break). Maybe camera should store the current tile map explicitly as a field  to not have the weird lookup behavior?
> fix center camera at / setting camera offsets issue with tmaps

- libs/base/gc.cpp
844 happens on microbit where the first block is 7k or so, but the rest are much smaller. This really means out of memory, so let's use 021.
> Use 021 not 844 for allocations not fitting in a block

- libs/game/sprites.ts
projectile from side should always send project from the side, not just from original screen width / height
fix game like https://makecode.com/_2fcbJC5Mabh6
(they still zoom off screen immediately as the speed is not relative to the player, but it works. Here's a slightly more complicated version that works slightly more nicely: https://makecode.com/_YURWqhEwfEfz)
> make projectile from side respect camera offset

- libs/game/spritemap.ts
fix collisions for this game https://makecode.com/_HXL1Tc7YJeik
But really just any game with camera follow sprite that isn't in a tile map.
I could keep the OOB checking and constrain to just the visible screen instead of hardcode , but that's inconsistent between tilemap and no tile map (all collisions are checked if there is a tile map, otherwise just in the screen) and just have inconsistent behavior.
Maybe we can revisit this file as a whole at some point and clean it up a bit, for example I don't think sprite.layer has ever been used. It might also be good to base the key off of the screens current position, so it will be more likely to have things around the action in different chunks
> don't ignore collisions of sprites that move off screen

- libs/game/controller.ts
A,B already used in melodies. Leads to confusing translations.
> use identifier for A/B buttons

- libs/edge-connector/pxt.json
Fix for https://github.com/microsoft/pxt-arcade/issues/1406. serial not impl on stm
> do not automatically use serial with edge connector

- libs/core/leveldetector.ts
Beefing up our level detector class to support analog dpad for arcade.
> On neutral in level detector

- libs/animation/animation.ts
- libs/game/game.ts
- libs/game/scene.ts
- libs/game/textDialogs.ts
Make it so you can set a scene as 'see through' - if set, it will render the scene below it as the background instead of using a normal background.
This lets you create scenes 'on top' of other scenes (menus, splash screens, other temporary overlays like tutorials) without explicitly managing a snapshot of the image from the previous scene as the background image.
> add 'see through' scene flag

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
- libs/game/tilemap.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1393
fixes issue reported on discord: https://makecode.com/_bhqJj74qjY0J has sprites moving only vertically, but they should have vx too (they were hitting the bounds of the tmap)
fixes https://github.com/microsoft/pxt-arcade/issues/1104
fixes https://github.com/microsoft/pxt-arcade/issues/1323
also fixes a few minor things in projectiles / sprites
* actually use the velocity that is chosen when randomly picking
* only set position once, to get rid of some unnecessary tilemap interactions
* defer setting position to ~sprites.create~ and Tile.place (same reason)
If a sprite is created or is moved more than a single step away, and the new position for the sprite is a wall, this disables tilemap interactions with that sprite (clipping and …
> fix some projectile + tilemap interactions

- libs/game/controller.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1327
Matches the current behavior of the any button which only cares about player 1
> Fix isPressed for the 'any' button

- libs/game/sprite.ts
and make the turnRate variable meaningful / scale properly
Now the default behavior will handle momentum a bit more accurately; from a dead stop (with turnRate = 100) it will hit max speed after .5 seconds, if you double the turnRate (200) it will take .25 seconds, etc.
> make sprite.follow(sprite) follow more accurately

- libs/game/controller.ts
fix https://github.com/microsoft/pxt-arcade/issues/1421
I just did atan2 + sin / cos at first, but then I thought about it for a minute and remembered my [unit circle](https://www.google.com/search?q=unit+circle&sxsrf=ACYBGNTs9VZs9a1vjRh2TWNtEE8WhP8avg:1571952022606&tbm=isch&source=iu&ictx=1&fir=Oeo5GOQ0YHmFvM%253A%252CQG4XqAmcN5dozM%252C_&vet=1&usg=AI4_-kT2bBY3Gkqh_5Z0n1oh3ZmIvjXZOQ&sa=X&ved=2ahUKEwi5gaXP6bXlAhVJJzQIHWlvDL0Q9QEwAHoECAUQAw#imgrc=Oeo5GOQ0YHmFvM:) instead of doing those relatively expensive operations
> don't let player go faster by moving diagonally

- libs/game/particleeffects.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1254
reverts https://github.com/microsoft/pxt-common-packages/pull/961, which fixed a random break in the compiler at the time (but unfixed another problem).
This no longer seems to be broken, which would indicate either the underlying bug got fixed in one of the many recent compiler changes, or it was a random break at the time along the lines of https://github.com/microsoft/pxt-arcade/issues/1118 and enough of the surrounding code has changed to make it not break anymore.
> Revert "Revert "make clear particle effects allow sprites in blocks""

- libs/animation/animation.ts
- libs/animation/docs/reference/animation.md
- libs/animation/docs/reference/animation/run-image-animation.md
- libs/animation/docs/reference/animation/run-movement-animation.md
- libs/animation/docs/reference/animation/stop-animation.md
Add the pages for the new style animation APIs.
RE: https://github.com/microsoft/pxt-arcade/issues/1350
Notes:
* **stopAnimation()** seems to have trouble decompiling back into blocks
*  why is ``sprite`` set as the second param in **stopAnimation()**?
> Update 'animation' ref pages

- libs/game/sprite.ts
Fix sprite say - e.g. https://makecode.com/_ReT0YeYVcHhe has it trailing / not following right away. It needs to update position continuously, not just when it needs to be redrawn
> Fix sprite say positioning

- libs/game/docs/reference/scene/camera-left.md
- libs/game/docs/reference/scene/camera-top.md
- libs/game/docs/reference/sprites/sprite/set-flag.md
- libs/game/physics.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
Adding two new blocks for getting camera left/top and a new sprite flag for HUD elements.
This is in response to https://forum.makecode.com/t/overlay-help/807/3 and https://forum.makecode.com/t/hud-and-inventory-for-large-tile-maps/644
> Adding a camera sprite flag and getters for the camera position

- libs/base/fixed.ts
- libs/screen/image.ts
`Fx.oneFx8` was 1/256 (0.004 or so), and two was 2/256.
The circle drawing algorithm was relying on it. This switches it to an integer, faster version.
The picture shows after/before
> Fix oneFx8 and twoFx8 values

- libs/game/sprite.ts
fix https://github.com/microsoft/pxt-arcade/issues/1505; make the default turn rate faster so that it turns around at a rate close to that in the live site.
> make default follow acceleration faster

- libs/mixer/docs/reference/music.md
- libs/mixer/docs/reference/music/beat.md
- libs/mixer/docs/reference/music/change-tempo-by.md
- libs/mixer/docs/reference/music/composing-sounds.md
- libs/mixer/docs/reference/music/note-frequency.md
- libs/mixer/docs/reference/music/play-tone.md
- libs/mixer/docs/reference/music/rest.md
- libs/mixer/docs/reference/music/ring-tone.md
- libs/mixer/docs/reference/music/set-tempo.md
- libs/mixer/docs/reference/music/set-volume.md
- libs/mixer/docs/reference/music/stop-all-sounds.md
- libs/mixer/docs/reference/music/tempo.md
Bring over the older `music` reference pages to match corresponding APIs in `mixer`.
Fixes https://github.com/microsoft/pxt-arcade/issues/1460
> Pull legacy 'music' docs into 'mixer'

- libs/game/controlleroverrides.ts
make the single player buttons have the same annotations as the multiplayer buttons, so they don't get translated differently. Requires https://github.com/microsoft/pxt/pull/6303 or an equivalent fix to show up properly.
> fix translations for single player buttons

- libs/game/physics.ts
- libs/game/tilemap.ts
fix https://github.com/microsoft/pxt-arcade/issues/1518
I used an extra closure for each case (up / down / left / right) to try to make it extra clear that they're four distinct cases / four distinct offsets. By default this will move the sprite up to 4px in a single direction to avoid clipping.
Tested on sim and pygamer.
sample game: https://makecode.com/_2Um08FgJeJUP - move sprite into the horizontal wall and press a to fire to the right and see that the sprite is offset, and do the same with the vertical wall and b.
> resolve clipping when possible by bumping sprite to other tiles

- libs/accelerometer/accelhw.cpp
Fix for https://github.com/microsoft/pxt-arcade/issues/1190
> fix y orientation in acceleremeter readins

- libs/core---samd/platform.cpp
- libs/game/systemmenu.ts
- libs/screen---st7735/screen.cpp
This makes the API no-op and removes buttons from the menu.
This also removes buttons from the menu in simulator. Any objections to that?
> Disable screen brightness setting on Kitronik

- libs/game/tilemap.ts
- libs/screen/fieldeditors.ts
The annotation we always forget to add to all image arguments. This is part of the fix for https://github.com/microsoft/pxt-arcade/issues/1575
> Adding decompiler annotation to tile arguments

- libs/color-coded-tilemap/tilemap.ts
- libs/game/tilemap.ts
fix https://github.com/microsoft/pxt-arcade/issues/1578 - bring back behavior of restricting tile size to the scale of the tilemap.
(slightly smarter than the old version; it only creates new images when the tile is smaller than the image, not larger)
https://makecode.com/_0bbE9xfkqfCJ
> restrict tiles to only show up to the current tile size

- libs/game/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1625
Obviously this has memory tradeoffs. I was hoping to only make it writable if the user calls the set tile API, but I can't see a way to check it in the TS. @mmoskal is this okay do you think? Tilemaps are one byte per pixel.
> Make buffer writable for tilemap data

- libs/color-coded-tilemap/tilemap.ts
- libs/game/tilemap.ts
We can take this if there is a need, or drop it. I did this to try and fix https://github.com/microsoft/pxt-arcade/issues/1622, but it seems like that issue is unrelated.
Anyways, this at least gets rid of the legacy code in the new tilemap implementation.
> Resurrect old tilemap

- libs/game/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1618
Just a missing null check from https://github.com/microsoft/pxt-common-packages/pull/1041
> Adding missing null check

- libs/game/scenes.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1648
This is *technically* a breaking change but it's an API we never told anyone about and never shipped.
> Respect scale of tilemapdata

- libs/color/colorbuffer.ts
crash in nfl game from this: https://github.com/microsoft/pxt-kickoff/blob/master/team.ts#L37 -- colorbuffer taking the buffer in directly risks a crash now if using a static buffer
> don't crash on .fromBuffer(hex, ...)

- libs/color/colorbuffer.ts
for nfl game, integrating #1054
> [stable6.17] don't crash on .fromBuffer(hex, ...)

- libs/microphone/docs/reference/input/on-loud-sound.md
- libs/microphone/docs/reference/input/set-loud-sound-threshold.md
- libs/microphone/docs/reference/input/sound-level.md
- libs/microphone/microphone.cpp
Looks like loud threshold max should be `255` instead of `100`. Otherwise, maybe use another scale factor to make a range of `0` - `100`.
Closes https://github.com/microsoft/pxt-adafruit/issues/1149
> Match loudness range for sound threshold

- libs/game/particleeffects.ts
- libs/game/particles.ts
- libs/game/sprite.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1700
This does not update particle effects after they are created because they don't keep a reference to sprites and it would have been too big a refactor. I think it's a pretty niche scenario anyways.
> Particle effects and say sprites should respect relativeToCamera

- libs/screen---linux/screen.cpp
This setting enabled 1x scaling and image in the top-left corner, so it can work with LED screen controllers. You can also try LED_SCREEN=2 for 2x scaling. 3x will probably not work
> Add arcade.cfg:LED_SCREEN=1

- libs/base/console.ts
- libs/game/sprite.ts
make sprite say take `any`. `sprite.say` doesn't play too nicely with `\n`'s at the moment; I just worked around it for now by replacing them with spaces, but I think supporting multi line `say`s  nicely would be a nice feature? Can see how much effort that would be if we want, but I'm not sure how that would end  up looking -- conflicts with the basic scrolling.
Noticed that we probably should add string.replace and string.replaceAll (non regex versions of course) to the string 'prototype' in pxtlib
(Also, took an extra few minutes to debug what was wrong with the first commit; pretty subtle error that feels very hard to catch)
> make sprite.say take any

- libs/buttons/buttons.cpp
- libs/core/pxt.h
- libs/game---hw/controllerbuttons.cpp
- libs/game---hw/pxt.json
- libs/game/controller.ts
- libs/game/controllerbuttons.cpp
- libs/game/controlleroverrides.ts
- libs/game/pxt.json
This cuts a level of indirection from our button handling - they are now directly in game---hw - this unifies handling of buttons between simulator, RPi and Cortex targets (ie `input.left` etc are no longer available in Cortex, as they were not available in RPi/sim).
> Move Arcade button handling from buttons to game---hw

- libs/color/colorbuffer.ts
- libs/color/colors.ts
- libs/palette/palette.ts
currently slice is returning a  0 length ColorBuffer when you try to copy one due to `length = Math.min(length | 0 /**  16 **/, this.length - length - start /** 16 - 16 - 0 **/);`
Also add a way to get the current color palette
> ColorBuffer slice fix, palette.getCurrentColors

- libs/game/info.ts
reset the gameEnd / timer for countdown before invoking the game over / countdown end handler, so that user can choose to reset timer in their handlers (e.g. a 'need more time' screen that pops back up with a few more ms)
> allow resetting countdown in 'on countdown end'

- libs/radio/sim/state.ts
Register radio state to receive packets. Will do a deeper PR to formalize the interfaces for message passing between simulator states.
> Radio sim registration

- libs/buttons/shims.d.ts
- libs/core---samd/shims.d.ts
- libs/core/pinsPWM.cpp
- libs/core/shims.d.ts
- libs/core/sim/edgeconnector.ts
- libs/core/sim/microservo.ts
- libs/core/sim/pins.ts
- libs/microphone/shims.d.ts
- libs/radio/shims.d.ts
- libs/serial/shims.d.ts
- libs/servo/servo.ts
Keeps track if the servo is used as a continuous servor (a motor) and update the simulator rendering accordingly.
+ regen of shims
> support for continuous servo in sim

- libs/base/docs/reference/control/on-event.md
- libs/base/docs/reference/control/raise-event.md
- libs/base/docs/reference/control/run-in-parallel.md
- libs/base/docs/reference/control/wait-for-event.md
- libs/base/docs/reference/loops/forever.md
- libs/base/docs/reference/loops/pause.md
Not all targets include "light" pixel support. Make the examples in the base reference more generic.
> Remove pixel functions from base examples

- libs/base/core.cpp
along with https://github.com/microsoft/pxt/pull/6825 fix https://github.com/microsoft/pxt-microbit/issues/2664
fix some parsefloat mismatches with js; allow any whitespace chars (not just spaces), return value up to given point if values after first digit are non-numeric (`1f` => 1, `f1` => NaN), handle trailing e that is not followed by a number (`1ef` => 1), don't ignore spaces after first digit (`123 456` => 123). Also drop auto conversion to hex for parsefloat (js doesn't) (this makes the change require https://github.com/microsoft/pxt/pull/6825 or equivalent to keep hex parsing in parseInt)
isspace was used in a decent number of other places so I left it as is and added one to check if character is whitespace; can check if the other places should actually be checking for any …
> align c++ parsefloat with js

- libs/core/i2c.ts
Helper function to migrate cpy scripts. Send receive data in i2c + fix i2cdevice to support non-standard i2c devince.
> I2ctransfer

- libs/keyboard/keyboard.cpp
- libs/keyboard/keyboard.ts
- libs/keyboard/shims.d.ts
- libs/keyboard/sim/keyboard.ts
- libs/microphone/test.ts
This also requires a fix in codal https://github.com/lancaster-university/codal-core/commit/281838f68737771482638a480f02a8b11dc5167f
> cleanup keyboard implementation

- libs/animation/animation.ts
fix issue we ran into on stream today; the animation does not apply until the first interval has passed, so it's always delayed when using with walking animations / etc. This makes it so the leading is frame is shown immediately
e.g. fixes https://makecode.com/_6aPCLTH8DJCz so that the pink circle immediately shows up when you press A, rather than after 500ms
> apply first frame of animation immediately

- libs/serial/enums.d.ts
- libs/serial/serial-common.h
- libs/serial/serial.ts
The previous fix did take into account that a Delimiters enum was already in C++.
> serial enum fix

- libs/mixer/docs/reference/music/melody-editor.md
- libs/mixer/melody.ts
Create a doc page for the `melodyEditor()` function. This provides a context help destination for the **melody** parameter in `playMelody()`.
Closes https://github.com/microsoft/pxt-microbit/issues/3087
> Make a doc page for 'melodyEditor'

- libs/game/sprites.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1899
fixes https://github.com/microsoft/pxt-arcade/issues/1897
two main changes here:
1. defaulting velocity for new projectiles to be vx = 50, vy = 50 to match default sprite velocity
2. Not setting a random velocity on projectiles who have 0 velocity set
> Change projectile blocks default behavior

- libs/game/camera.ts
- libs/game/docs/reference/scene/camera-left.md
- libs/game/docs/reference/scene/camera-property.md
- libs/game/docs/reference/scene/camera-top.md
- libs/game/docs/reference/scene/get-camera-property.md
- libs/game/scenes.ts
Original description:
> camera-right: Returns the x coordinate of the camera's right edge (right edge of the screen).
> camera-bottom: Returns the y coordinate of the camera's bottom edge (bottom edge of the screen).
New description:
Added a new block to get camera properties: `left`, `top`, `right`, `bottom`. Deprecated corresponding `camera-left` and `camera-top` blocks.
Resolves https://github.com/microsoft/pxt-arcade/issues/1836
> Add dropdown block for camera properties

- libs/game/physics.ts
re: https://forum.makecode.com/t/ghost-flag-not-sync-between-multiple-simultaneous-overlap-event-fire/2459
In the game https://makecode.com/_6Yd0KYLcoRJV , if you press `a` twice to spawn two enemies and then press `b` to place the sprite on top of them you can see the issue; the overlap event sets the sprite to be a ghost, so that you get some invincibility frames, but it doesn't work here because the overlap events are spawned synchronously but they run asynchronously, and the two sprites both overlap within the same frame.
This makes it bail out before the handler if a previous event has changed the state of one of the sprites such that the overlap is now invalid (i.e. sprite is now destroyed or a ghost).
> check that sprite can collide before running async on overlap handler

- libs/game/sprite.ts
fix issue where you end a follow and the sprite keeps moving with it's last 'momentum'; e.g. https://makecode.com/_7fvLjU4hD7ri
> stop sprite when sprite following is invalidated

- libs/game/sprite.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1714
Update the x and y first, and correct the position afterwards
> Adjust sprite say bubble position after update

- libs/animation/animation.ts
fix https://github.com/microsoft/pxt-arcade/issues/2033
fix https://github.com/microsoft/pxt-arcade/issues/2052
I didn't look for the pr, but if I remember right I broke this a while ago while fixing another bug, oops :(
(issue is that the ev handler was checking destroyed state based off the sprite the first animation was init'd with, not the sprite attached to the animation)
> fix animations 'sprite destroyed' check

- libs/game/sprite.ts
Give the say bubble a z index 1 higher than whatever it's attached to, so that it is always visible against equivalent sprites.
re: https://forum.makecode.com/t/speech-bubble-z-depth/2662
worth noting, the z only changes if the parent sprite's z index was changed, so this shouldn't incur any performance penalty with regard to sorting the sprite list: https://github.com/microsoft/pxt-common-packages/blob/master/libs/game/basesprite.ts#L31
e.g. in snippet below, both sprites are at same index, so say bubble should show up above them
```typescript
let mySprite = sprites.create(img`
. . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . .
. . . . . . . . . . . . . . . .
. . . . 3 3 3 3 3 3 3 3 3 3 . .
. . . 3 . . . . . . . . . 3 . .
. . . . 3 . . . . . . …
```
> give say bubble a z index 1 higher than the sprite it's attached to

- libs/game/physics.ts
- libs/game/tilemap.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1772
Here is a test program that demonstrates the bug:
https://makecode.com/_D497oY0yViu2
The fish should hit the red orb, teleport to the green orb, and then instantly teleport to the top-right corner. I'll check this program into arcade once this is merged and bumped.
> tile overlaps should handle overlaps not in the direction of movement

- libs/game/sprite.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/1702
Return floats, not ints!
> Convert to floats for sprite properties

- libs/color-coded-tilemap/tilemap.ts
- libs/game/physics.ts
- libs/game/sprite.ts
- libs/screen/image.cpp
- libs/screen/image.d.ts
- libs/screen/sim/image.ts
- libs/screen/sim/state.ts
Also removes the "dirty" property and always renders the screen image.
Build: https://arcade.makecode.com/app/7379a2aa01b069ee05aa1e1746df57004002823b-4be123dca1
Test program: https://makecode.com/_UftW2pLMt41k
Fixes https://github.com/microsoft/pxt-arcade/issues/1892
> Expose isStatic on RefImages, recalculate sprite hitbox for non-static images

- libs/screen/image.d.ts
Not fully certain best wording, but to start:
Maybe can drop 'image' from the text, but could see someone being confused if they variables in and things 'randomly' break with an equals block.
Doesn't really fit in Drawing / Create / Transformations so I put it in it's own "Compare" group
> add image equals block

- libs/game/sprite.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2115
Minimal repro (image with odd-numbered dimension): https://makecode.com/_gCA8PWYaoFR1
> Convert sprite x/y setters to floats

- libs/game/physics.ts
fix https://github.com/microsoft/pxt-arcade/issues/2153
When friction was added the acceleration was moved into an if, but the constrain always needs to occur. This was allowing unbounded speed when the speed change is applied outside physics (in this case, the repeat was adding 30vy every frame, and since the physics engine thought the max was 500 it didn't handle it well when speeds got to around a few thousand)
As a side note, I'm pretty happy I got to make a branch named 'fixSpaceMan' and have it be an accurate name
> constrain speed changes applied outside physics calc

- libs/base/console.ts
re: https://forum.makecode.com/t/debug-function-in-arcade-game/2750/3?u=jwunderl, it's confusing that `console.log` takes any but `console.logValue` only takes numbers for the `value` field. Block still looks the same, but now you can drop whatever you want in each slot:
> allow console logValue to take any for value param

- libs/game/systemmenu.ts
Just like volume, save brightness modified through the settings menu. It's already capped to 10-100
> save screen brightness modified in settings

- libs/game/tilemap.ts
**The problem**
In the JS editor, typing `tiles.createTilemap(` and tab to autocomplete fills in a scale of `TileScale.Eight`, but it should be `TileScale.Sixteen`.
**My solution**
I wasn't able to find a way to have it explicitly become `TileScale.Sixteen`, but making it the default value is an improvement, I think. Curious what others think, and if there's a better solution.
Fixes https://github.com/microsoft/pxt-arcade/issues/2112
> createTilemap: Default scale to TileScale.Sixteen

- libs/game/tilemap.ts
When we do place on random tile, it creates an array of all of the tiles of that type; that's fine a lot of the time, but VERY BAD when that tile is the base of a big level (e.g. the standard floor in a ~80x80 tilemap)
This adds a helper to get an n-length random sample from the tiles of the given type w/ a [reservoir sample](https://en.wikipedia.org/wiki/Reservoir_sampling) (Yay for all the times I had to help students with interview questions prep!).
test that it's actually random (I tried a handful of different lengths / tile arrangements, just need to draw on tilemap): https://makecode.com/_5tx7bz2ua59o
w/ two quick runs:
fixes issue with Sonia's game (see teams)
> dont crash when using place on random tile when tile count >>> big number

- libs/game/sprite.ts
Move the logic of "not changing the hitbox if it's a small change" out of setImage() and into setHitbox() so we can use it if the sprite has its image manipulated.
> Run "small hitbox change" logic on image manipulation

- libs/game/docs/reference/images/image/get-pixel.md
- libs/game/docs/reference/scene/background-color.md
- libs/game/docs/reference/scene/set-background-color.md
Include some hints to help clarify what the color numbers are.
Closes https://github.com/microsoft/pxt-arcade/issues/2135
> Add info for color number to bkgnd ref pages

- libs/game/textDialogs.ts
Font height / width is used in chunking text, setting it before chunking allows dealing with non-latin characters.
https://github.com/microsoft/pxt-arcade/issues/2270
> set font before chunking texts

- libs/game/docs/reference/sprites/sprite/set-velocity.md
- libs/game/sprite.ts
Add the missing reference page for `sprite.setVelocity()`.
Closes https://github.com/microsoft/pxt-arcade/issues/2252
> Ref page for sprite 'set-velocity'

- libs/core/hf2.cpp
- libs/core/hf2.h
This completely removes support for control-pipe HF2 transport (already disabled on all targets), simplifies sending flow and thus improves reliability (esp. atomicity of send).
> reliability updates for HF2

- libs/screen/sim/image.ts
I was using this during our hackathon project to half image size when sending messages, and the screen was messed up on the other end - when unpacking it is placing them offset by [w](https://github.com/microsoft/pxt-common-packages/blob/f5c1827799d13688b95f78f7cfc948cbc88b6c09/libs/screen/sim/image.ts#L738) instead of 1
> pxsim.image.toBuffer match pxsim.image.ofBuffer

- libs/game/sprite.ts
fix https://github.com/microsoft/pxt-arcade/issues/2331; we still want it to bail out on null, undefined, and "" (as that's commonly used as 'clear say' in games)
> fix sprite.say(0)

- libs/game/tilemap.ts
And fixing an annotation that I accidentally left out of https://github.com/microsoft/pxt/pull/7360
These literals are all exactly the same as `tilemap` at runtime, but they will make it so that the tilewidth is correct when you create a new tilemap from monaco. Eventually we can deprecate once we have an asset editor.
> Adding literals for different tile widths

- libs/base/eventcontext.ts
- libs/game/systemmenu.ts
- libs/screen/sim/state.ts
re: https://github.com/microsoft/pxt-arcade/issues/2323, I remembered this got dropped at some point and stopped working in the sim (probably when it got set so it was drawn at the bottom of the screen on hardware?). These are the stats that are set when `game.stats == true` / you turn on the setting in the menu. https://makecode.com/_LfW3FAWALKHt
fixes https://github.com/microsoft/pxt-arcade/issues/1645 and fixes https://github.com/microsoft/pxt-arcade/issues/1306
the portion in EventContext is to stop it from always starting off with a big "undefined" until the first fps is identified.
images below are with a few styling changes in a separate sim pr to make it fit in with the sim again
> reattach stats so users can see in sim too

- libs/game/docs/reference/controller/dy.md
- libs/game/docs/reference/sprites/create-projectile.md
'Vertical' isn't keyboard friendly.
Fixes https://github.com/microsoft/pxt-arcade/issues/2082
> Fix a couple of 'vertical' typos

- libs/game/docs/reference/sprites/create.md
Sprite kind was null in Sprites.create() reference page. Added a default kind to snippets and noted use of **kind**.
Fixes https://github.com/microsoft/pxt-arcade/issues/2372
> Set sprite kind in Create ref page

- libs/mixer/melody.cpp
fixes https://github.com/microsoft/pxt-arcade/issues/2423
@klausw - this also fixes an issue with volume (it only worked if endVol==startVol)
> Allow playing of read-only buffers and fix volume sliding

- libs/mixer/melody.cpp
- libs/mixer/melody.h
Instead of a 512-byte lookup table, use Bhaskara's approximation
formula, with some rescaling to match the input and output ranges.
The maximum error is 54/32767 = 0.00165 which should be good enough
for sound generation purposes, especially on target devices with
small non-HiFi speakers.
> Replace sineTone lookup table with approximation

- libs/animation/legacy.ts
AddAnimationFrame had a bad help path.
Also, https://github.com/microsoft/pxt-arcade/issues/2040 mentions missing help for the enum args. This is the case across all game/animation api's. Will the enum shims link the help path when clicked in the Toolbox? If so, I could add pages for those.
Fixes https://github.com/microsoft/pxt-arcade/issues/2040
> Animation missing help

- libs/game/sprite.ts
fix https://github.com/microsoft/pxt-arcade/issues/2448
When we get to the point that we say we're 'close enough' and stop moving in a follow, snap to target location so the positions match exactly.
cc: @cosmoscowboy
> snap to target location when on top of sprite in follow

- libs/base/gc.cpp
- libs/base/pxtbase.h
- libs/core/codal.cpp
- libs/core/pxt.h
This was for ELL compiled models; it was broken.
(I now use it for EdgeImpulse models)
> Fix handling of assembly .comm directives

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
for https://forum.makecode.com/t/sprite-move-through-tile-map-walls/3985/13
example: jumpy platformer where the bats can move through walls and you get a cheat mode where you don't touch sprites if you hit 'b' https://arcade.makecode.com/app/09cfd1c8063b0d69ce25e7703281edb2efb1b0dc-b3db6078b4#pub:_ftk7vCXPUFWF
> add separate options for no collisions / overlaps

- libs/base/controlmessage.ts
- libs/base/sim/controlmessage.ts
So it can just go to the parent, instead of creating a second simulator each time.
I don't see how the cpp side of things works here, so not sure if anything would be needed there? The only use of it I've seen right away is [here](https://github.com/microsoft/pxt-jacdac-services/commit/7cdcf8e2e78bed0f3ca14a7e40b7d190e2f8aba1#diff-52838880e988354f72feddfcd58faddb78dc93e73f050139f97cd377405cb2d7R15), is the behavior just that this shim only applies on hardware so the simulator goes through the function body / calls this api?
For reference, I was looking at using this here: https://github.com/jwunderl/arcade-tick-event/blob/master/main.ts#L48
> add flag to disable msg broadcast in simmessages

- libs/serial---linux/serial-target.cpp
typo in https://github.com/microsoft/pxt-common-packages/pull/1193 breaking arcade serve; I don't think this would need to be ported to microbit/stable as it's just part of the linux build
> fix typo breaking arcade build

- libs/mixer/melody.ts
If a melody is stopped and restarted while playing, it must
not be unregistered by the playCore handler to avoid keeping
unstoppable melodies running in the background.
Fixes microsoft/pxt-arcade#2541
> Don't unregister melody if stopped and restarted

- libs/base/configkeys.h
on behalf of @lalauria2000.  Part 1 of 2.
See: https://github.com/microsoft/pxt-maker/pull/324
> Update configkeys.h to include new pins for Adafruit Grand Central M4

- libs/game/physics.ts
Fix https://github.com/microsoft/pxt-arcade/issues/2320
fix https://github.com/microsoft/pxt-arcade/issues/2744
When there's a lot of lag and sprites have high speeds, it's possible to overflow fx8 in this calculation (or underflow it when the calculation is flipped). Replaces this one with a normal floating point normal mul / divide so that doesn't happen
> sprites shouldn't float due to lag

- libs/game/physics.ts
When I was testing https://github.com/microsoft/pxt-common-packages/pull/1209 I noticed that using Fx8 for time here is actually slowing things down slightly, as `Fx.mul` has an extra operation vs `Fx.imul` (and same for `Fx.div` & `Fx.idiv`): https://github.com/microsoft/pxt-common-packages/blob/master/libs/base/fixed.ts#L30-L35
Anyway, VERY minor change in speed (~1/4 the time difference referenced in the linked pr, so on the order of ~~1e-3 ms), but a bit easier to reason about time without it being trimmed / etc
> use number for time instead of Fx8 (imul / idiv is faster than mul/div)

- libs/game/docs/reference/sprites/on-created.md
fix https://github.com/microsoft/pxt-arcade/issues/2621
This had the super old / removed 'spritetype' instead of spritekind, so fixed that.
Also ran them back through compiler to clean up generated code, and make sure `onCreated` came before `on start`; as written the on created wouldn't apply as the sprite was created before the event was being registered
> fix kinds in on-created docs

- libs/game/assetTemplates.ts
Define the blockIdentity for animations so they decompile properly for the docs svgs (instead of just being gray blocks). re: https://github.com/microsoft/pxt/pull/7784
As far as I can tell this was left off because the block is in an extension, but that would just mean it fails out to a gray block here https://github.com/microsoft/pxt/blob/0beaeb3e7690664ec50e571a5591edca75561878/pxtcompiler/emitter/decompiler.ts#L3410 instead of the check before when the animations extension isn't loaded, which seems fine.
> define animation blockIdentity so animations temp strings decompile in docs

- libs/game/sprites.ts
Remove from "Arrays", move to "Sprites"
fixes https://github.com/microsoft/pxt-arcade/issues/1815#issuecomment-763854627
> Move array of sprites of kind block to Sprites

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/sprites.ts
A decent amount of the changes are whitespace, I'll add some annotations where I made actual changes & here's an 'ignore whitespace' view: https://github.com/microsoft/pxt-common-packages/pull/1219/files?diff=unified&w=1
Separate ghost flags even more, so walls and tile overlaps are handled by separate flags. @riknoll @shakao @livcheerful question on behavior for an edge case; if a sprite is set to 'ghost through walls' and has an 'on overlap tile' event, if it overlaps a wall should that trigger? Currently we don't trigger overlap events with walls (as you shouldn't overlap with a wall / it should push you back), but I'm leaning towards making it so when you're a wall ghost you can overlap those when you can walk through them. (this commit is the change for this behavior: …
> Split wall & tile flag, add top level blocks for flags in tutorials

- libs/game/sprite.ts
Not a recent regression, but simple fix / I've seen it happen a lot before (don't think anyone's made explicit note of it that I've seen?)
in drawTransparentImage any decimal points are lopped off / treated as ints - sim side this is handled with an | 0 on each, hardware side it's just part of the ts->cpp layer. This causes any sprites whose positions have fraction components to be offset differently when those positions are positive vs negative, as `| 0` rounds towards 0. E.g. move to the right in this game and see the rectangles get offset when they are slightly off screen: https://makecode.com/_fwphzuhAxMjC
re: behavior not noted before, just read through the latest comment in https://forum.makecode.com/t/strange-recent-behavior-with-setposition-method/5615/6?u=jwunderl from them and …
> round sprite rendering consistently (floor instead of |0)

- libs/game/sprites.ts
fix https://github.com/microsoft/pxt-arcade/issues/3004
The `aliasFor` makes it so it compiles down to `sprites.create` instead of as a separate function
> add standalone / non-blockSetVariable sprites.create

- libs/game/docs/reference/sprites.md
- libs/game/docs/reference/sprites/create-projectile-from-side.md
- libs/game/docs/reference/sprites/create-projectile-from-sprite.md
Add new reference pages for **createProjectileFromSide** and **createProjectileFromSprite**.
Closes https://github.com/microsoft/pxt-arcade/issues/2730
> Update projectile ref pages

- libs/screen/sim/image.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/3344
Makes the logic match the c++ implementation:
https://github.com/microsoft/pxt-common-packages/blob/master/libs/screen/image.cpp#L277
> Fix sim implementation of fillrect

- libs/screen/sim/image.ts
My fix to the simulator implementation of fillRect:
https://github.com/microsoft/pxt-common-packages/pull/1240
> Cherry pick #1240 to stable8.8

- libs/game/textDialogs.ts
We have a problem right now when rendering text dialogs that are very large (bigger than 36x36). You can see it with the big leaf frame:
This fix just makes it so that we bleed into the border in this case instead of doing this. We have a bunch of big frames coming in soon
> Handle very large dialog frames

- libs/game/sprite.ts
fix https://forum.makecode.com/t/sprites-still-overlap-after-being-destroyed/7668
> destroyed sprites cannot collide with other sprites

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/tilemap.ts
* port https://github.com/microsoft/pxt-common-packages/pull/1246 -- fix a few issues we ran into on stream which was making it tedious to subclass physics by exposing a few extra things
* port https://github.com/microsoft/pxt-common-packages/pull/1251 -- fix an issue with the boolean 'sprite overlaps with otherSprite' block (re: https://forum.makecode.com/t/sprites-still-overlap-after-being-destroyed/7668)
> [stable8.8] Minor arcade ports

- libs/core/usb.cpp
- libs/screen/image.cpp
- libs/settings/NRF52Flash.cpp
ble_running is defined by MicroBitDevice.h and everything compiles successfully. For other boards with softdevice, ble_running is now defined here.
> define ble_running for non-microbit NRF-based boards

- libs/game/physics.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/2053
> Check if a sprite was destroyed before registering another obstacle

- libs/game/info.ts
When the user explicitly sets info.showLife(false) (or info.showScore(false)), don't override it the next time the life is changed.
This is for an extension I'm writing that kiki wanted, so would be good to get in for tomorrow ~
(also minor typo fix, visilibity -> visibility)
> when user explicitly sets showLife / showScore, don't override it

- libs/azureiot/azureiot.ts
- libs/base/control.ts
- libs/base/poll.ts
- libs/core---esp32/crypto.cpp
- libs/core---esp32/usb.cpp
- libs/mqtt/mqtt.ts
- libs/net/netutil.ts
- libs/net/pxt.json
- libs/net/requests.ts
- libs/tsconfig.json
- libs/wifi---esp32/controller.ts
- libs/wifi---esp32/sim/tsconfig.json
- libs/wifi---esp32/sim/wifisockets.ts
- libs/wifi---esp32/socket.cpp
- libs/wifi---esp32/wifi.cpp
* twin and SAS token support in azureiot; general fixes there
* add `control.allocateEventSource()` (as opposed to `control.allocateNotifyEvent()` which should be the second argument to `raiseEvent()`)
* mqtt fixes
* add `net.url(en|de)code()`
* add simulator support for iot-hub and https-req sockets (heavily restricted now)
> azure iot hub fixes/extensions

- libs/animation/docs/reference/animation/create-animation.md
- libs/core/docs/reference/pins/pulse-duration.md
- libs/game/docs/reference/animation/run-movement-animation.md
- libs/game/docs/reference/info/has-life.md
- libs/music/music.ts
> typo: milleseconds -> milliseconds

- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
**For your consideration.** When working in JavaScript I often want to write directly to the screen rather than use the Sprite system, and have found myself implementing this `blit` method multiple times. The method implemented here is modeled after the WinGDI's venerated [`StretchBlt`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-stretchblt).
This `blit` method copies an image from a source rectangle to a destination rectangle, stretching or compressing to fit the dimensions of the destination rectangle, if necessary.
If we think this is a useful addition to the runtime, then I'll implement the cpp side.
> add image blit method

- libs/game/assetTemplates.ts
- libs/game/physics.ts
- libs/game/scenes.ts
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/sprites.ts
- libs/game/tilemap.ts
This PR does a few things:
1. Ports several blocks from the tilemap extension into the scene category
2. Reorders the scene groups. Mostly just swapped the "Camera" and "Effects" groups
3. Reordered the blocks in the "Camera" group. We never organized them in the first place; they were in random order. Now "camera follow sprite" is on top
4. Created some new groups for the tilemap-related blocks. They are "Tilemaps", "Operations", and "Locations"
5. Adds "destroy all sprites with effect" to the sprites category
6. Deprecates the old "set tilemap to" block and replaces it with a new one with a shadow block
None of these changes require upgrade rules.
There is one "gotcha" if you use this with the existing tilemaps extension where the tilemap shadow blocks from that extension are not …
> Add new tilemap blocks and reorganize the scene category

- libs/game/docs/reference/scene/place-on-random-tile.md
This is a typo fix for https://github.com/microsoft/pxt-arcade/issues/3881 along with a some updates for the new api. This really should be part of the fixes need later for https://github.com/microsoft/pxt-arcade/issues/2728.
**Note:** The "See also" link is stale but I'll leave it in until the new 'set' and 'place' ref docs are in.
Fixes https://github.com/microsoft/pxt-arcade/issues/3881
> Update 'placeOnRandomTile' ref page

- libs/game/docs/reference/scene.md
- libs/game/docs/reference/scene/get-tile-location.md
- libs/game/docs/reference/scene/is-hitting-tile.md
- libs/game/docs/reference/scene/on-hit-wall.md
- libs/game/docs/reference/scene/on-overlap-tile.md
- libs/game/docs/reference/scene/place-on-tile.md
- libs/game/docs/reference/scene/set-tile-at.md
- libs/game/docs/reference/scene/set-wall-at.md
- libs/game/docs/reference/scene/tile-at-location-equals.md
- libs/game/docs/reference/scene/tile-kind-at.md
- libs/game/sprite.ts
- libs/game/spriteevents.ts
- libs/game/tilemap.ts
This adds/updates ref pages to the current tilemap exposed API. Exceptions are 'setTilemap()` and the "Tilemap" overview page which will come in a follow-on PR.
The pages are currently grouped under `./scene` to match the block namespace.
Finally getting the bulk of changes for https://github.com/microsoft/pxt-arcade/issues/2728 filled in.
RE: #1301
> Tilemap ref page updates part 1

- libs/game/docs/reference/scene.md
- libs/game/docs/reference/scene/set-tilemap.md
- libs/game/tilemap.ts
Second part of updating the tilemap ref pages. This contains a new page for `setTilemap()` , an update to the `scene` card page, and the help path.
I was going to do a tilemap overview page in here but I thought that would work better in the target doc set (tilemap editor discussions, etc.) if it's even necessary due to similar coverage in the courses content.
Closes https://github.com/microsoft/pxt-arcade/issues/2728
> Tilemap ref page updates part2

- libs/game/docs/reference/scene/set-tile-at.md
- libs/game/docs/reference/scene/tile-at-location-equals.md
Some parameter order errors in a couple of tilemap reference pages. Corresponds to fixes in #1305.
> Fix parm errors in tilemap ref pages

- libs/game/hitbox.ts
- libs/game/sprite.ts
- libs/game/spritesay.ts
- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
- libs/sprite-scaling/README.md
- libs/sprite-scaling/pxt.json
- libs/sprite-scaling/scaling.ts
- libs/sprite-scaling/targetoverrides.ts
- pxtarget.json
Adds scale properties to Sprite class:
- `sx (scale x)`
- `sy (scale y)`
- `scale` (returns greater of sx and sy)
Adds a few built-in basic scaling blocks:
And adds additional blocks for advanced scaling in an extension:
> Add sprite scaling support

- libs/sprite-scaling/scaling.ts
Moved to own **Sprite Scaling** category, under **Advanced**.
Color is:
> Scaling extension: move blocks to own category

- libs/base/fixed.ts
- libs/game/hitbox.ts
- libs/game/sprite.ts
Sprite's `left` and `top` accessors each return a float. When the sprite is rendered, these values are floored to get the sprite's pixel coordinates. This wasn't happening in the hitbox calculation, which doesn't matter much at scale=1, but at larger scales it becomes noticeable. I fixed the issue by correspondingly flooring the left and top values passed to the hitbox.
Other changes in this PR:
- Account for scale in a few places where I wasn't, but should have been
- Changed Sprite `width` and `height` to return float rather than int. This seems more correct (again, it didn't matter so much at scale=1)
- Changed Sprite serialize to write scale values as float rather than int
Tagging @mmoskal for the `fixed.ts` additions and Sprite serialization changes
Fixes …
> Ensure hitbox pos matches scaled sprite pos

- libs/game/sprite.ts
- libs/sprite-scaling/scaling.ts
Also, show scaling extension in main toolbox.
Fixes https://github.com/microsoft/pxt-arcade/issues/4547
> Fix for drift when scaling sprite

- libs/game/docs/reference/sprites.md
- libs/game/docs/reference/sprites/sprite/change-scale.md
- libs/game/docs/reference/sprites/sprite/fx.md
- libs/game/docs/reference/sprites/sprite/fy.md
- libs/game/docs/reference/sprites/sprite/scale.md
- libs/game/docs/reference/sprites/sprite/set-scale.md
- libs/game/docs/reference/sprites/sprite/sx.md
- libs/game/docs/reference/sprites/sprite/sy.md
- libs/game/sprite.ts
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-by-percent.md
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-by-pixels.md
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-to-percent.md
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-to-pixels.md
- libs/sprite-scaling/scaling.ts
Sprite scaling reference pages:
Closes https://github.com/microsoft/pxt-arcade/issues/4562
RE: https://github.com/microsoft/pxt-arcade/issues/4590
> Sprite scaling reference pages

- libs/game/docs/reference/scene/get-neighboring-location.md
- libs/game/docs/reference/scene/get-tile-location.md
- libs/game/docs/reference/scene/location.md
- libs/game/docs/reference/scene/tile-at-location-equals.md
- libs/game/docs/reference/scene/tile-at-location-is-wall.md
- libs/game/docs/reference/scene/tile-image-at-location.md
- libs/game/docs/reference/scene/tilemap-location.md
- libs/game/docs/reference/sprites/destroy-all-sprites-of-kind.md
- libs/game/docs/reference/sprites/sprite/scale.md
- libs/game/docs/reference/sprites/sprite/sx.md
- libs/game/docs/reference/sprites/sprite/sy.md
- libs/game/sprites.ts
- libs/game/tilemap.ts
Put in the missing reference pages for tilemap and sprites API updates.
**Note:** A new page is included for `tiles.Location` but there is no way to link context help for it to this block-
This is the same as the situation with the sprite properties too.
Closes https://github.com/microsoft/pxt-arcade/issues/4590
> Fill in some missing tilemap location reference pages

- libs/game/tilemap.ts
This is correcting something we did wrong back in the day: making it so that you can access the current tilemap.
I do not remember why we ever restricted this, but I don't think there is any reason to do so now. Right @jwunderl?
> Make tilemap data public

- libs/game/scenes.ts
- libs/game/tilemap.ts
Fixing a dumb bug that I made when I was refactoring this code. We don't need to check if map is defined to fire the unloaded event.
Also fixes the scale being wrong during the tilemap load event
> Fix unload not working when map is undefined

- libs/game/scenes.ts
- libs/game/tilemap.ts
Cherry picking a couple of bug fixes I made while implementing the new tilemap extension
> [Stable 9.4] Fix unload not working when map is undefined (#1328)

- libs/game/docs/reference/sprites/sprite-kind.md
- libs/game/sprite.ts
- libs/game/spritekind.ts
The object helpers of `sprites._spriteKind()` and `sprite.image()` are visible blocks but don't have doc pages. They are added in here. The `image` property doc page exists already but the `image` property is set as it's own block so I just linked the help attr to that page.
> Add missing ref pages for 2 sprite blocks

- libs/game/docs/reference/tiles/set-current-tilemap.md
- libs/game/docs/reference/tiles/set-tilemap.md
- libs/game/docs/reference/tiles/tilemap.md
- libs/game/tilemap.ts
Needed to update the 'set' tilemap pages and move them to `./tiles`. Also, I added a `tilemap` object reference page in order to link it from the other pages. I think we'll migrate the other tile docs from the `./scene` to folder to `./tiles`  in a follow on PR.
> Update the base 'tilemap' ref pages

- libs/game/docs/reference/tiles/get-neighboring-location.md
- libs/game/docs/reference/tiles/get-tiles-by-type.md
- libs/game/docs/reference/tiles/location.md
- libs/game/docs/reference/tiles/place-on-random-tile.md
- libs/game/docs/reference/tiles/place-on-tile.md
- libs/game/docs/reference/tiles/set-tile-at.md
- libs/game/docs/reference/tiles/set-wall-at.md
- libs/game/docs/reference/tiles/tile-at-location-equals.md
- libs/game/docs/reference/tiles/tile-at-location-is-wall.md
- libs/game/tilemap.ts
Migrate the reference pages for the `tiles` namespace into the `./tiles` folder. Update the API help paths.
This is additive such that the similar pages remain in `./scene` until there's a release that contains the `tilemap.ts` with the new help paths. A later PR should then remove the similar pages from `./scene`.
RE: #1332
> Tiles reference pages migrate

- libs/game/keymap.cpp
- libs/game/keymap.ts
- libs/game/pxt.json
- libs/game/sim/keymap.ts
This PR adds support for remapping player inputs at runtime. This makes it possible for [Makey Makey](https://makeymakey.com/), for example, to create an extension that would define a block to remap the simulator for their board's input scheme. The extension might look like this:
```ts
namespace MakeyMakey {
//% blockId=set_makeymakey_controls
//% block="Remap simulator keys to Makey Makey defaults"
export function setMakeyMakeyInputs() {
// Configure input for player 1
keymap.setPlayerKeys(
1,
keymap.KeyCode.UpArrow,
keymap.KeyCode.DownArrow,
keymap.KeyCode.LeftArrow,
keymap.KeyCode.RightArrow,
keymap.KeyCode.MouseLeftButton,
keymap.KeyCode.Space);
// Configure input for player 2
keymap.setPlayerKeys(
2,
keymap.KeyCode.W,
keymap.KeyCode.S,
keymap.KeyCode.A,
keymap.KeyCode.D, …
```
> [common] Support for remapping keyboard input

- libs/settings---files/settings.cpp
fclose(NULL) has undefined behavior and might in some case lead to segfault and crash.
This PR simply test before calling fclose inside the _exists code for files based settings.
Should fix https://github.com/microsoft/pxt-arcade/issues/3812 and allow to use settings.exists on RPi Zero.
> Fix fclose(NULL) in settings---files that might cause crashes

- libs/game/sim/keymap.ts
I could swear I tested this, but the keymaps were indeed incorrect.
> Fix incorrect key mappings

- libs/game/sim/keymap.ts
Cherry-pick keymap fix: https://github.com/microsoft/pxt-common-packages/pull/1349/commits/b99df4587660566cdb94aab68b9663ac3ae6ec5d
> Cherry-pick keymap fix to stable9.4

- libs/radio-broadcast/docs/reference/radio-broadcast.md
- libs/servo/docs/reference/servo.md
A couple of top level API pages as destinations for the `radio-broadcast` and `servo` extensions that are 'built-in'.
RE: https://github.com/microsoft/pxt/pull/8914 and https://github.com/microsoft/pxt-microbit/issues/4752#issuecomment-1157010721
> Patch in pages for built-in extension "Learn More" links

- libs/game/sim/keymap.ts
Will want to port this for the arcade cabinets we're making. This was made even quicker than I thought by Eric's last change :)
Set the 'Backtick' key on the keyboard for 'Menu' and the 'Backspace' key on the keyboard for 'Reset'
closes https://github.com/microsoft/pxt-arcade/issues/4777
closes https://github.com/microsoft/pxt-arcade/issues/3491
> add keyboard shortcut for menu (1) and reset (2)

- libs/game/hitbox.ts
- libs/game/sprite.ts
fix https://github.com/microsoft/pxt-arcade/issues/4864
We were missing updating the hitbox here when it becomes invalid. 
Also update hash generation for sprite hitbox / img, I think this should be fine as written? issue before is that this._image.revision() starts off at 0, so multiplying it would be.. not ideal as it would just ignore the different scaling of _x _y for static images
build w/ stable table: https://arcade.makecode.com/app/e8fdc2c613b1610dd6c807e09d6305d9af5bdcc0-c92540148b#pub:_V2KJKPadDRJu
https://arcade.makecode.com/app/e8fdc2c613b1610dd6c807e09d6305d9af5bdcc0-c92540148b#pub:_Tfaaewgmkig2 is another one you can check / the minimal repro I listed in that pr
> Fix stable table regression

- libs/game/temp.d.ts
- libs/game/tsconfig.json
no user side changes, just gets rid of a lot of red squiggles when you're making changes in vscode. Many of them came from https://github.com/microsoft/pxt-common-packages/blob/fewerErrorsInVSCode/libs/game---light/pxt.json giving a few duplicate class definitions when the default tsconfig is which just grabs defs for all files in the repo
> get rid of spurious errors in vscode for game pkg

- libs/mixer/melody.ts
- libs/mixer/pxt.json
- libs/mixer/sim/music.ts
- libs/mixer/soundEffect.ts
- package.json
Adds the sound effect field editor to pxt-common-packages using the mixer sound engine instead of the codal one.
The "randomize" block is the same as pressing "generate similar sound" in the field editor
> Add sound effect blocks to pxt-common-packages

- libs/screen/sim/image.ts
When we reset the height field at the end of each "row", we should actually set it to 1 instead of 0, since the code expects it to have been incremented once already at this point.
Fixes https://github.com/microsoft/pxt-arcade/issues/4690
Using the sample from the above bug, without fix:
With fix:
> Fix Off-by-One Error Traversing Image Rows

- libs/game/physics.ts
- libs/game/sprite.ts
This change switches "Stay in Screen" and "Bounce on Wall" checks to use the sprite's Hitbox instead of the left, right, top, and bottom fields. Left, right, top, and bottom do not account for transparency around the sprite, so a sprite with a transparent border would look like it could never actually reach the edge (see https://github.com/microsoft/pxt-arcade/issues/4846 for an example). By using HitBox, we ensure the sprite will not stop/bounce until a non-transparent section of the sprite intersects with the edge.
I've also moved this check into the PhysicsEngine, which seems like a more natural place for it.
Fixes https://github.com/microsoft/pxt-arcade/issues/4846
> Respect Transparency for Screen Edge Collisions

- libs/screen/sim/image.ts
We don't support non-integer image sizes, so truncate any width and height values passed into `create()`.
Fixes https://github.com/microsoft/pxt-arcade/issues/4726
> Truncate dimensions when creating an image

- libs/game/info.ts
Added two blocks so that users can get the current countdown of their game and also change the countdown by negative or positive seconds. Negative makes it so there is less time left on the countdown, positive makes it so there is more time on the countdown. 
**Quick Demo:** 
https://user-images.githubusercontent.com/49178322/194131975-ac438c6c-afd5-4234-a06f-e951f82faf48.mp4
**The Blocks** (the two new are at the bottom of the screenshot)
Closes https://github.com/microsoft/pxt-arcade/issues/2248
**The target:** https://arcade.makecode.com/app/bf585e360f8e57bd8312ad0b0ea40b6f706ddba7-421bc06f42#editor
> Added: getCountdown, changeCountDownBy blocks

- libs/game/sim/multiplayer.ts
It felt like way too many messages were going through so I poked around for a bit, due to some pretty weird lifecycle stuff in simdriver we actually end up initializing multiple times (I didn't look too closely but it appears to be a bit of a race -- e.g. when I just logged out I saw upwards of 4-5 calls to init like this but when I set breakpoints I only saw it repeat once or so), and this setInterval was getting recreated multiple times and sending upwards of 100 frames / a second.
The frame sending logic is independent of the individual sim runtime either way, so limit to a single setInterval in the scope of the frame
> fix rate at which multiplayer images are sent to 20fps

- libs/game/sim/keymap.ts
- libs/game/sim/multiplayer.ts
setButton basically just calls handleKeyEvent, and is the location at which I'm rejecting buttons from players 2+ in multiplayer sessions, so just bypassing that.
Also minor typings fix to get rid of red squiggle, and fix usage of safe navigation operator not supported in ts2.6
part of fix for https://github.com/microsoft/pxt-arcade/issues/5138
This should go in at same time as or just before arcade sim side change, it's safe to be on it's own.
> Multiplayer fix host can pretend to be all players

- libs/game/multiplayer.cpp
- libs/game/multiplayer.ts
- libs/game/scene.ts
- libs/game/sim/multiplayer.ts
- libs/screen/sim/state.ts
- package.json
two main things:
* Send the screen from within the game engine, after the screen update step. Currently, we just send it at a random time in the loop, causing things to occasionally be misrendered / missing if they are done part way through the render (that is, it's not uncommon to see screens that are supposed to have a dialog flash the scene behind it without the dialog)
* Patch on palette to the messages that go between sim <-> host frame -- tested on the sending side, not on the consuming side yet. Have to check with Eric on how we want to format this in the --multiplayer <-> backend communication where it's binpacked -- it's currently a 48b uint8array, we can safely chop off the first 3 bytes if we want as those are always 0x00000 (transparency) -- even if someone tries to set it we …
> only post screen when at end of render, incl palette in sim<->host messages

- libs/game/controller.ts
- libs/game/info.ts
PR 2 of 3 for automatically detecting if a game is multiplayer at compile time.
This adds the multiplayer part to all of our multiplayer APIs. Additionally, I refactored the code a bit so that all of the APIs with the multiplayer part are not referenced internally for our "global" score and controller apis. This is necessary to prevent those parts from being drawn in when the user isn't actually referencing the multiplayer versions in the code.
> Add parts annotation to multiplayer APIs and refactor

- libs/game/camera.ts
- libs/game/scenes.ts
fix https://github.com/microsoft/pxt-arcade/issues/5440
here's a build for it as it's easiest to just test it https://arcade.makecode.com/app/708640d9e59404f6d619b6d9e551c9854dfa2596-d43654d8b7
This makes it so we basically pass through to the sprites position when grabbing camera state - so the pause(0) hack we did is no longer necessary, and it's fine bumping the code out of the `run code after game engine updates the camera` back into an on game update if we want. Here's a version where I did that: https://arcade.makecode.com/app/708640d9e59404f6d619b6d9e551c9854dfa2596-d43654d8b7#pub:_FFLTaRKXePxE
> Fixing camera read loc

- libs/game/physics.ts
Scenario is pretty simple; sprite has stay in screen set & is the sprite the camera is following, and moves off screen within the physics (e.g. as part of a wall hit event). This then causes it to snap to the edge of the screen, as the camera won't be updated at that point. (can occur without following the same sprite as stay in screen is set to, as that's a bit of a arbitrary circumstance, but describing those circumstances is much harder :) )
I'm very happy I did https://github.com/microsoft/pxt-common-packages/pull/1385 earlier this week or I would have been scratching my head a ton trying to figure out what could possibly have gone wrong here.
> fix bug where moving out of screen on followed sprite can break with stay in screen

- libs/game/multiplayer.cpp
- libs/game/multiplayer.ts
- libs/game/sim/multiplayer.ts
- libs/multiplayer/fieldEditors.ts
- libs/multiplayer/mp.ts
final portion of the support, depends on https://github.com/microsoft/pxt/pull/9287 and https://github.com/microsoft/pxt-backend/pull/748 . @eanders-ms if you're not in the middle of a pr I'll just go ahead and swap the `*.multiplayer` namespaces to `*.mp` so that I can remove the hack in `/mp.ts`. Here's a test game that sets the two user sprites + a pizza for slot one: 
https://makecode.com/_XrmfzuFdyLHt
(no blocks for setting icons directly, just the javascript api -- I'll add it to sprite util extension or something unless we decide to include one)
for the javascript apis, there's a possibly slightly tricky 'implicitly set vs explicitly set' state for whether the icon gets sent or not -- this is so we can add the default behavior of 'set / update player icon whenever they …
> pass up player icons & reaction icons to multiplayer page

- libs/game/animation.ts
It's time for another classic "richard sneaks in a change he's been wanting to make forever while nobody is paying attention  over winter break" PR!
This PR refactors the path animation code to improve a few things:
1. Paths are now parsed as they execute instead of upfront, which reduces memory usage
2. Paths now correctly parse floating point arguments (previously, only integers worked)
3. Added some helpful exceptions when there is an error parsing a path
4. Both types of animation (path and image) now use the same delta time that the physics engine uses for timing. Previously, each animation called control.millis() as it updated which caused all of the animations to drift out of sync over time
5. Reduces total compiled code size by 0.1% (tested with …
> Reduce path animation memory and synchronize animations on frame time

- libs/mixer/instrument.ts
- libs/mixer/sequencer.ts
Makes the necessary changes to support the new song encoding from https://github.com/microsoft/pxt/pull/9299
Once again, this is a *breaking change*. All existing songs will no longer work correctly. Hopefully this should be the last change I need to make to the binary encoding before the music editor is released.
The encoding of songs includes a version number, so in the future we'll be able to do backwards compat if we ever need to change the encoding again.
> Update song decoding to new format

- libs/game/physics.ts
fix physics bug we ran into on stream last week (the one we hacked in a fix by adding 1 to vx) -- make it so when a wall collision handler causes a sprite to be unable to collide with walls (newly clipping, ghost, destroyed) we don't 0 out the velocity. If we think destroyed might actually occur and end up with some visual nonsense I can change it to just `SpriteFlag.GhostThroughWalls`~
here's a sample game where it'd apply https://arcade.makecode.com/S79255-37130-89180-31596
> walls shouldn't stop new ghosts

- libs/game/multiplayer.ts
- libs/multiplayer/player.ts
fix https://github.com/microsoft/pxt-arcade/issues/5532
as a sidenote we'll still have two apis in here (multiplayer.init & multiplayer.initServer) but they're internal / not things we'd particularly want users to use anyways
> mv post reaction / presence icon to mp namespace

- libs/game/game.ts
- libs/game/info.ts
- libs/game/textDialogs.ts
Partially addresses https://github.com/microsoft/pxt-arcade/issues/513. One more change coming after this in a separate PR to modify the multiplayer extension.
This change adds new blocks for configuring game over, and adds support for multiplayer scoring.
**use effect**: Set the effect that occurs when the game is over.
**use sound**: Set the music that occurs when the game is over.
**use message**: Set the message that displays when the game is over.
**use scoring**: Set the method of judging the best score for the game.
**game over**: Deprecated the effect parameter on existing block.
**on countdown end**, **on life zero**: removed default sound and visual effect from game over dialog. They can be re-added using the new blocks above.
> Game over updates for multiplayer

- libs/game/particleeffects.ts
I believe this is what you were looking for? This will add it to all effects dropdowns but 🤷, maybe we can make it so this clears all sources to treat it as a proper 'clear all effects' effect (if you wanna try that just making prune call destroy on every other element in the array)
> add 'none' option for particle effects dropdown

- libs/mixer/instrument.ts
- libs/mixer/melody.ts
- libs/mixer/playable.ts
- libs/mixer/pxt.json
- libs/mixer/soundEffect.ts
- libs/music/ns.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5552
This PR unifies all of the various melody/song/tone/effect blocks into a single playback block with different shadows for each type. The playback block has three options for playback: "until done", "in background", or "looping in background". Here's what the toolbox looks with this change:
All of the shadow blocks here have the "duplicate on drag" behavior so you can drag them out of the block to assign to variables or whatever. Not only does this change unify all of the blocks, it also reduces the overall number of blocks in the toolbox.
No upgrade rules are needed. Here's a build link: 
https://arcade.makecode.com/app/9896b4c680b9f43609dfc35cf51de2d68d18f0ba-e997f1cd4e
> Unify all music playback blocks

- libs/game/game.ts
- libs/game/textDialogs.ts
- libs/multiplayer/ns.ts
- libs/multiplayer/player.ts
- libs/multiplayer/pxt.json
Adds this block to the multiplayer extension:
It overrides the active scoring method to explicitly set who won the game.
Resolves https://github.com/microsoft/pxt-arcade/issues/5559
> Add `game over [player]` block to multiplayer extension

- libs/game/game.ts
- libs/game/info.ts
- libs/mixer/melody.ts
- libs/mixer/soundEffect.ts
The game over "use sound" block now takes any playable type.
Also sorted the Game Over blocks as they appear in the toolbox.
> Support playable as game over sound

- libs/game/controller.ts
- libs/multiplayer/player.ts
This change makes it so that if a user sets up button control on a player and then assigns a new sprite to the player, we will move controls to the new sprite and stop controlling the old one.
This change also makes it possible to setup player control before the sprite is assigned, whereas before this would silently fail.
This will always control the most recent sprite assigned to the player:
Resolves https://github.com/microsoft/pxt-arcade/issues/5567
> When reassigning player sprite, reassign button controls as well

- libs/game/sim/multiplayer.ts
Don't drop icon messages when not in host mode, just let parent iframe determine what to do with them
> post icon messages to parent iframe even if not in multiplayer mode

- libs/game/multiplayer.ts
- libs/game/sim/multiplayer.ts
fix https://github.com/microsoft/pxt-arcade/issues/5193
event ids are a little tricky, I guess we just do "roll a dice and hope it doesn't collide" after checking `dal.d.ts` (e.g. https://github.com/microsoft/pxt-common-packages/pull/1119/files#diff-3446560eec31e791faeaee0c3b08bfefebbb06df29fd92a46bd5054576a1c094R3 is the other 'recent' sim only one that comes to mind)
quick test build: https://arcade.makecode.com/app/d83a329c52d33eb16de47b9b06193c1f1db0a87f-e53085d68d--multiplayer?host=_Rkud4LTboCqc, only host really matters for testing / it's fine if guests are just on beta
pxt side over in https://github.com/microsoft/pxt/pull/9332
> hook up player leave / join to multiplayer state

- libs/game/controller.ts
- libs/game/scene.ts
connected / disconnected events are treated like all the other controller events, which only run in the context of the screen. These events 'feel' more global though so this tracks when connection state has changed while the scene was behind in the stack and runs the events when it pops up again.
Super easy repro with this is just to press menu button and disconnect someone in https://arcade.makecode.com/app/d83a329c52d33eb16de47b9b06193c1f1db0a87f-e53085d68d--multiplayer?host=_Rkud4LTboCqc
> raise events for disconnected/connected on scene pop

- libs/game/sprite.ts
- libs/game/sprites.ts
Let's eliminate one of the leading causes of the dread "sim error: failed cast on null".
If this error message were at all helpful, we might choose to leverage it as a teaching moment. But as it stands, it only serves as a blocking condition a beginner will hit and have no recourse but to walk away from Arcade.
> null protection for sprite destroy

- libs/multiplayer/docs/reference/multiplayer.md
- libs/multiplayer/docs/reference/multiplayer/change-player-state-by.md
- libs/multiplayer/docs/reference/multiplayer/game-over-player-win.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-index.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-number.md
- libs/multiplayer/docs/reference/multiplayer/get-player-by-sprite.md
- libs/multiplayer/docs/reference/multiplayer/get-player-property.md
- libs/multiplayer/docs/reference/multiplayer/get-player-sprite.md
- libs/multiplayer/docs/reference/multiplayer/get-player-state.md
- libs/multiplayer/docs/reference/multiplayer/is-button-pressed.md
- libs/multiplayer/docs/reference/multiplayer/move-with-buttons.md
- libs/multiplayer/docs/reference/multiplayer/multiplayer-state.md
- libs/multiplayer/docs/reference/multiplayer/on-button-event.md
- libs/multiplayer/docs/reference/multiplayer/on-controller-event.md
- libs/multiplayer/docs/reference/multiplayer/on-life-zero.md
- libs/multiplayer/docs/reference/multiplayer/on-score.md
- libs/multiplayer/docs/reference/multiplayer/player-selector.md
- libs/multiplayer/docs/reference/multiplayer/set-player-indicators-visible.md
- libs/multiplayer/docs/reference/multiplayer/set-player-sprite.md
- libs/multiplayer/docs/reference/multiplayer/set-player-state.md
- libs/multiplayer/docs/types/player.md
- libs/multiplayer/fieldEditors.ts
- libs/multiplayer/player.ts
Add the reference pages for the 'multiplayer' extension APIs.
Closes https://github.com/microsoft/pxt-arcade/issues/5515
> Reference pages for 'multiplayer' blocks

- libs/game/sprite.ts
- libs/game/sprites.ts
* null protection for sprite destroy
* Update libs/game/sprites.ts
Co-authored-by: Joey Wunderlich <jwunderl@users.noreply.github.com>
---------
Co-authored-by: Joey Wunderlich <jwunderl@users.noreply.github.com>
> (hotfix stable10.3) cherry-pick: null protection for sprite destroy (#1415)

- libs/feather/docs/reference/feather.md
Put in a page for the 'feather' extension as a link destination for the "Learn More" link.
The feather extension has no APIs. It just maps pin IDs.
Closes https://github.com/microsoft/pxt-arcade/issues/5582
> Add an extension page for 'feather'

- libs/sprite-scaling/docs/reference/sprite-scaling.md
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-by-pixels.md
- libs/sprite-scaling/docs/reference/sprites/scaling/scale-to-pixels.md
- libs/sprite-scaling/scaling.ts
Include a reference main page for 'Sprite Scaling' extension. This satisfies the destination for the "Learn More" link.
Also, add some jsDoc that is missing for the API functions.
Closes https://github.com/microsoft/pxt-arcade/issues/5575
> Sprite scaling extension main page

- libs/mixer/instrument.ts
- libs/mixer/melody.cpp
- libs/mixer/sequencer.ts
- libs/mixer/sim/music.ts
- package.json
This PR requires https://github.com/microsoft/pxt/pull/9381
Fixes https://github.com/microsoft/pxt-arcade/issues/5675
This separates playback of songs between hardware and the browser sim. On hardware, nothing changes (except the bug I fixed). The simulator now uses the same sequencer used by the music editor, which has much more accurate timing.
Here is a program that illustrates the issue:
https://arcade.makecode.com/S22715-41600-35351-76629
Try playing that in the sim and then opening the code and playing it in the music editor. The sim is significantly slower and drifts over time.
While I was at it, I also added some events for the browser simulator that I thought would be useful.
Here's an upload target with these changes: https://arcade.makecode.com/app/abc67de31823239df2cb53cc6844fd …
> Better support for playing songs in the browser sim

- libs/game/info.ts
- libs/multiplayer/player.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5725.
Today, if you have multiple "on score" blocks, **the last one wins**. Here, on score 6 never runs because onScore 5 is the last one defined after converting to javascript.
[This is because `PlayerState` only contains a single `ScoreReachedHandler`.](https://github.com/microsoft/pxt-common-packages/blob/054b7c4576147e37c6f2ce823a495349e9ac62cc/libs/game/info.ts#L36)
- `PlayerState` now has an array of `ScoreReachedHandler`s.
- If multiple handlers are added for the same score, last one wins (mimics multiplayer score handler behavior).
There are two places now that handle this "last one wins" behavior. If for some reason we wanted to enable multiple handlers for the same score, we'd need to remember to change two places of code. …
> Multiple score handlers per PlayerState

- libs/mixer/docs/reference/music.md
- libs/mixer/docs/reference/music/create-song.md
- libs/mixer/docs/reference/music/melody-playable.md
- libs/mixer/docs/reference/music/play.md
- libs/mixer/docs/reference/music/string-playable.md
- libs/mixer/docs/reference/music/tone-playable.md
- libs/mixer/docs/types/playable.md
- libs/mixer/melody.ts
- libs/mixer/playable.ts
Add in some reference pages for the new "playable" blocks.
Do we need a page for the Song Editor like micro:bit has for its [Sound Editor](https://makecode.microbit.org/types/sound#sound-editing)?
Closes https://github.com/microsoft/pxt-arcade/issues/5599
> Music 'playable' ref pages

- libs/game/docs/reference/game.md
- libs/game/docs/reference/game/set-game-over-effect.md
- libs/game/docs/reference/game/set-game-over-message.md
- libs/game/docs/reference/game/set-game-over-playable.md
- libs/game/docs/reference/game/set-game-over-scoring-type.md
Add the reference pages for the new 'game over' blocks.
Closes https://github.com/microsoft/pxt-arcade/issues/5549
> Reference pages for new 'game over' blocks

- libs/game/game.ts
See this snippet from one of the MakeCode tutorials
```ts
function startGame() {
// Set the background color to cyan
scene.setBackgroundColor(9);
```
You could plug in numbers to see what happens, but that isn't a good experience. So I added a color enum to make our javascript "onboarding experience" smoother:
cc @riknoll the templates are going to be super helpful, so it'd be nice to update your template project to include the enum when this eventually gets merged.
Tested by running arcade locally
> Add `Color` Enum

- libs/mixer/docs/reference/music/create-song.md
- libs/mixer/docs/reference/music/play.md
- libs/mixer/docs/reference/music/song-editor.md
Add a base doc for the [Song Editor](https://github.com/microsoft/pxt-arcade/pull/5789) page without the images. Also, include links to this page from the `create-song` and `play` pages.
RE: https://github.com/microsoft/pxt-arcade/pull/5789
> Music playable pages linking

- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
I mirrored over the code from the cpp to the sim side in https://github.com/microsoft/pxt-common-packages/commit/9b878f8bf9ded9d9f372269be2e881270a6127b5 and https://github.com/microsoft/pxt-common-packages/commit/45d18049986d57511cb780147e77cf22049284bd + one more coercing out decimal places, left the cpp as is besides a few more nitpicks on spacing that I had missed before. CPP side already reviewed in https://github.com/microsoft/pxt-common-packages/pull/1439
here's richard's pretty test: 
https://arcade.makecode.com/app/7695d0da8f8e68416984aa13f6e208cc78d11849-a60c32b437#pub:S49613-21549-53722-36190
(I haven't actually run the polygon4 one yet as I'm going to make dinner / didn't have a test case handy)
It's not letting me explicitly add you as a reviewer but I'd love it if you …
> Triangle fill / polygon fill from aqeeaqee

- libs/mixer/melody.ts
Requires https://github.com/microsoft/pxt-arcade/issues/5738
This is the authoring change to support multiple tagged templates. This should not be merged until the other one is
> Add second tagged template to song field editor

- package.json
- sim/tsconfig.json
See https://github.com/microsoft/pxt/pull/9492 for details.
Marking this as draft the above PR is merged.
> [pxt-common-packages] Fix deprecation of "out" option in tsconfigs

- libs/radio/radio.ts
Fixes https://github.com/microsoft/pxt-microbit/issues/4849
A while back, when rewriting radio from C++ code to Typescript (https://github.com/microsoft/pxt-microbit/pull/2000/files), we accidentally subtracted 2 instead of 1 from the max payload for sending strings. We only need to adjust by 1 so we have room to store the length. 
I tested this change on hardware as well and everything is working fine.
> Fix radio send string to allow 19 chars

- libs/microphone/sim/state.ts
In order to avoid cluttering the AnalogSensor, @jwunderl helped me create a MicrophoneState for the mic in the simulator to update the functionality to better reflect the hardware.
> New microphone state to keep track of level, etc for simulator

- libs/microphone/sim/state.ts
- libs/screen/sim/image.ts
- libs/shader/pxt.json
- libs/shader/shader.cpp
- libs/shader/shader.ts
- libs/shader/sim/shader.ts
This adds a new package called shader that has some useful functions for shading:
1. mapImage - similar to mapRect except that it remaps colors according to an image. It takes in a buffer of color mappings and each color in the map image will point to a different section of the buffer, allowing you to shade the destination image by different amounts.
2. mergeImage - takes two images and finds the minimum pixel value at each coordinate. Useful for merging multiple light sources into one "lightSpace" that you can shade all at once
> Add shader package

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpr.yml
- .github/workflows/pxt-buildpush.yml
see https://github.com/microsoft/pxt/pull/9550; we're getting a spurious diagnostic on every build 
that appeared to be causing some build inconsistencies on occasion (in the build linked from that pr, it's my best guess as the random build error can come from wrong node version being used).
will do the same pr over in microbit, minecraft, arcade for now~
> update checkout, setup-node actions

- libs/screen/sim/image.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5994
The issue is that when drawing started at a negative y position, we were adjusting the start index from the icon so that we were only reading the pixels that actually appear on screen. However, we weren't adjusting the destination index in the image we were drawing to which resulted in everything being shifted up a few pixels.
I also renamed all of the variables to make it easier to read. The only actual change is line 563
> Fix draw icon in the simulator

- libs/game/sprite.ts
- libs/game/sprites.ts
This flag turns off pixel perfect overlaps for a sprite. Adding for use with things that extend the Sprite class but don't necessarily have an image associated with them (like TextSprites from my fancy text extension).
I suppose you could also use it to make your bullet hell game run faster.
> Add hitbox overlaps flag

- libs/screen/sim/image.ts
in https://github.com/microsoft/pxt-common-packages/pull/1450 looks like these got duped by accident when they were moved out to a separate package
> remove dup merge image in sim/image.ts

- libs/screen/fieldeditors.ts
This change is a partial fix for having qualified names for images result in a sprite editor instead of an image picker in blocks. 
When a qualified name is used, the resulting editor will have all image types in the gallery including tiles, dialogs, and backgrounds. This is different from the default editors for sprites, backgrounds, tiles, and dialogs which filter out images accordingly.
> Change image field editor to sprite editor

- libs/game/controller.ts
The help path for `controller.dy()` was incorrectly set to `help='keys/dy'`.
Fixes https://github.com/microsoft/pxt-arcade/issues/6287
> Correct the help path for 'controller.dy'

- libs/game/docs/reference/animation/animation-frames.md
- libs/game/docs/reference/images/image.md
- libs/game/docs/reference/images/image/equals.md
- libs/game/docs/reference/images/sprite-image.md
- libs/game/docs/reference/info/change-countdown-by.md
- libs/game/docs/reference/info/change-score-by.md
- libs/game/docs/reference/info/countdown.md
- libs/game/docs/reference/sprites/all-of-kind.md
- libs/game/docs/reference/sprites/on-overlap.md
- libs/game/game.ts
- libs/game/info.ts
- libs/game/spriteevents.ts
- libs/game/sprites.ts
- libs/screen/fieldeditors.ts
- libs/screen/image.d.ts
Add some missing block reference pages and correct some bad help paths.
**Note**: There is no mechanism for setting help paths for class properties (e.g.: `mySprite.vx`), or ``blockcombine`` attributed methods. So, such properties, like `mySprite.vx`, are documented but not linked to the block help menu item. For example,
https://arcade.makecode.com/reference/sprites/sprite/vx. I've asked for a way to link these up but such a feature has yet to get in.
Closes https://github.com/microsoft/pxt-arcade/issues/6231
> Fix block help paths and missing ref pages

- libs/game/camera.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6115 . Fx8 rounding issue
https://github.com/microsoft/pxt-common-packages/blob/fixCameraOddSize/libs/game/sprite.ts#L112 looks like the root cause (/ potentially better point to fix), putting this up for ref but may change after grabbing lunch to fix over there instead. Need to test more but feels like they could be related to a few of the other issues relating to odd sized sprites in general. e.g. inconsistency in overlaps with 1px wide sprites
> fix camera stuttering on following on size sprite

- libs/browser-events/browserEvents.cpp
- libs/browser-events/browserEvents.ts
- libs/browser-events/keyboard.ts
- libs/browser-events/pxt.json
- libs/browser-events/shims.d.ts
- libs/browser-events/sim/browserEvent.ts
- libs/browser-events/sim/keyboard.ts
- libs/browser-events/sim/mouseState.ts
This PR adds a browser-only extension that enables support for keyboard and mouse events.
There are two more PRs for this, one in pxt-arcade and one in pxt-arcade-sim.
The API for keyboard keys treats each key as an individual controller button. There is no "get last character typed" block because this API is not meant for typing text, just letting the player have extra button options (typing in our sim would be super cumbersome anyhow given that we have keys that map to special functions like taking a screenshot).
Also, as an added safety feature all keyboard and mouse events are disabled in mutliplayer (the code doing the disabling is in pxt-arcade-sim).
> Add keyboard and mouse events extension

- libs/game/assetTemplates.ts
- libs/game/tilemap.ts
The pxt-common-packages part of https://github.com/microsoft/pxt/pull/9853
This adds no new blocks, but opens up the ability for me to add a block in an extension (like tile util)
> Add support for tilemaps with 4x4 tiles

- libs/mixer/sim/music.ts
Another bug we encountered during stream today! Events for sequencers were being sent with undefined as the id.
> fix the id we send for sequencer events

- libs/mixer/sim/music.ts
Cherry picking this fix to the arcade stable branch! This is for an extension we've been working on in stream. See also https://github.com/microsoft/pxt/pull/9928
> [Stable10.3] fix the id we send for sequencer events (#1474)

- libs/game/game.ts
- libs/game/info.ts
Needed for: https://github.com/microsoft/pxt/pull/10041
This is a small change to the game over block to include the scoring method in the event that game over sends to the simulator. The event that was modified only gets used by the kiosk.
> Game over block: made saveAllScores take the scoring method

- libs/base/sim/control.ts
- package.json
This is part two of the fix for https://github.com/microsoft/pxt-microbit/issues/5709
Requires this PR (build will probably break until this gets merged/bumped):
https://github.com/microsoft/pxt/pull/10054
> Pass on the message bus listener flags in the sim

- libs/base/core.cpp
Fixes https://github.com/microsoft/pxt-microbit/issues/2192
We've long had an optional define (`PXT_POWI`) which can be used to prevent the compile from pulling in the std implementation of `pow` (which is 4k of code by itself). As far as I know, this flag is only actually used in the pxt-microbit to prevent hex size issues with the v1 micro:bit.
The historic PXT_POWI implementation casts the exponent to an integer which obviously provides pretty inaccurate results. This new implementation instead takes advantage of the fact that for positive non-zero x values:
```
Math.pow(x, y) = Math.exp(y * Math.log(x))
```
`exp` and `log` are already pulled into the hex, so this doesn't increase the hex file size at all (i verified this locally)
this is mostly based on @martinwork's …
> replace pxt_powi implementation with better one

- libs/multiplayer/player.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/5952
Fixes the player state in the multiplayer extension.
The only actual issue was the check in ensure state (should be `this._state.length <= key`), but I dislike arbitrarily limiting the number of entries to 255 so I reverted the implementation to that of my original extension which uses an array of objects rather than a sparse array of numbers.
> Fix multiplayer state

- libs/browser-events/browserEvents.cpp
- libs/browser-events/shims.d.ts
- libs/browser-events/sim/time.ts
adds date APIs to the browser-events extension. these let you get the current time in milliseconds since the epoch and also break that time into its constituent parts using the local browser/system settings. this is currently javascript only, but i might add blocks later. also this does nothing on hardware (obviously)
this is a frequent request on the forum.
> add date APIs to browser events extension

- libs/game/sprite.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6678
this fixes the above issue, which was caused because this deprecated block references a block that doesn't exist anymore.
the larger issue here is that we probably shouldn't be showing deprecated blocks in this scenario in the first place. in the above issue, if you load a tilemap that doesn't filter the toolbox, then we include *all* the blocks in each of the flyouts including deprecated blocks. we probably shouldn't be doing that!
@abchatra this is an exceedingly safe fix so i think we should hotfix it to arcade ASAP to unblock the teacher who is using this
> remove reference to invalid shadow on deprecated block

- libs/game/sprite.ts
cherry picking the as of yet unmerged https://github.com/microsoft/pxt-common-packages/pull/1492
this is a very safe fix so i think we should hotfix it
> [Stable10.3] cherry pick scene category fix

- libs/game/numberprompt.ts
- libs/game/prompt.ts
- libs/game/pxt.json
- libs/game/systemKeyboard.cpp
- libs/game/systemKeyboard.d.ts
requires https://github.com/microsoft/pxt-arcade-sim/pull/110
this adds support for requesting strings using the system keyboard so that you can just type responses to the ask for string and ask for number blocks. i also greatly refactored the prompt code and deleted all of the duplicated code in the number prompt class.
see the sim pr for details on how the simulator side of this works. also, this is not supported on hardware.
> Add system keyboard support to number and string prompts

- libs/game/systemKeyboard.cpp
the RPI build was failing because it doesn't use CODAL
> fix rpi build on system keyboard APIs

- libs/game/spritesay.ts
fixes https://github.com/microsoft/pxt-arcade/issues/5441
this fixes two bugs:
1. the arrow for the sprite say dialog wasn't taking into account the camera. not sure this one was ever actually filed, but it always bothered me!
2. the old sprite say (pre line-wrapping) was broken at some point. this fixes it, but only applies to old projects
> Fixing a couple of sprite say bugs

- libs/screen---st7735/screen.cpp
As mentioned in this issue https://github.com/microsoft/pxt-arcade/issues/6438 changing the CFG0 bytes does not lead to the desired change in e.g. the offset values for the display when the display type is set to 4242 (Smart Display). I could trace this down to the smartConfigure function, in which in line 173 or 175 the content of the cfg0 variable is currently rewritten to either 0x80 or 0x40. Since the smartConfigure function is called before the offset values are read out (line 82), the rewriting leads to an erasure of the offset values. My proposed fix is to bitmask writing the cfg0 variable to keep all bytes despite the LSB.
Edit: Another way of fixing this issue could also be to extract the offset values before calling the smartConfigure function.
> fix: prevent overwrite in smartConfigureof cfg0

- libs/game/sprites.ts
- libs/multiplayer/player.ts
* Update the **spritecreatenoset** block def to duplicate on shadow drag.
* Update the **mp_setPlayerSprite** block def to use **spritecreatenoset** as a shadow block.
Fixes https://github.com/microsoft/pxt-arcade/issues/5597
> duplicate sprite create on shadow drag

- libs/game/physics.ts
- libs/game/sprite.ts
- libs/game/spritemap.ts
@jwunderl and i were playing with the physics engine on livestream yesterday and discovered that the biggest performance bottleneck in games with lots of overlapping sprites was our SpriteMap's overlaps function. for those who haven't looked at this code before, we use a form of spatial hashing in our overlap detection where we divide the screen/tilemap into buckets and then place each sprite into every bucket it overlaps with. then, during the overlap step in our physics engine we loop over all moving sprites and build up a list of potential overlappers by merging all of the buckets that the sprite is in. this ends up being faster than the N^2 alternative for games with lots of sprites but just barely because merging those buckets is expensive and we end up doing it several times per …
> optimize sprite overlap step

- libs/game/docs/reference/sprites.md
Link to `clear-particles` is pathed via `/reference/effects` and not `/reference/sprites/sprite`.
Closes https://github.com/microsoft/pxt-arcade/issues/6621
> Fix link to 'clear-particles'

- libs/base/docs/reference/loops/forever.md
Replace the article 'an' with the more appropriate 'a'
> Fix grammatical error in example sentence

- libs/game/numberprompt.ts
- libs/game/prompt.ts
- libs/game/systemKeyboard.cpp
- libs/game/systemKeyboard.d.ts
requires https://github.com/microsoft/pxt-arcade-sim/pull/111
this is the main part of https://github.com/microsoft/pxt-arcade/issues/6810
adds a new sim API for localizing the system keyboard instruction text and flips the default for that ask for string/number blocks to using the keyboard for text entry. the wording for the new option is "use on-screen keyboard"
here's the current block:
and here's the new one:
> change system keyboard to default and add sim API for localizing system keyboard instructions

- libs/game/docs/reference/sprites/on-overlap.md
- libs/game/docs/reference/sprites/sprite/say.md
Update some old sprite overlap examples in reference pages.
Closes https://github.com/microsoft/pxt-arcade/issues/6291
> Fix some sprite overlap examples

- libs/browser-events/browserEvents.ts
Fixes https://github.com/microsoft/pxt-arcade/issues/6884
There are three bugs in this issue. One and three I technically already addressed here: https://github.com/microsoft/pxt-common-packages/pull/1508, but when testing and poking for _this_ bug, I realized that the pointer events had the correct associated numbers and we were actually handling the pressed state wrong. I just assumed that flipping them would be the solution since that was the fix for the mouse and wheel bug also fixed in the above PR. By flipping them, I actually introduced the same bug in the more generic `browswerEvents` block. I've switched the numbers back and fixed where the actual problem was with pressed so all of the events blocks behave as expected now.
Bug 2 in that issue helped reveal the problems above and …
> fix pause until bug, change pointer events back

- libs/game/hitbox.ts
- libs/game/pxt.json
- libs/game/rotation.ts
- libs/game/sprite.ts
- libs/screen/image.cpp
- libs/screen/image.ts
- libs/screen/sim/image.ts
this PR adds a new rotation property to sprites. this property works similarly to the two scale properties (sx and sy) but instead of stretching the sprite it rotates it using the "three shears" algorithm. this adds two new properties to the sprite dropdown:
they both map to the same thing but obviously use different units. radians is what you want if you're going to be using this with trigonometric functions like sin and cos, but degrees is easier to understand/think about. 
the drawing for the rotation is implemented in c++ with fixed point math and it runs pretty well on hardware, though it's still much slower than non-rotated sprites. however, because we're talking about rotating pixel art here, the results don't always look amazing especially for smaller sprites. for example, here is …
> add rotation property to sprites

- libs/browser-events/browserEvents.cpp
- libs/browser-events/browserEvents.ts
- libs/browser-events/keyboard.ts
- libs/browser-events/shims.d.ts
- libs/browser-events/sim/keyboard.ts
this PR does a few things to address various bits of feedback from the forum
* fixes the casing on all of the event names to be consistent with our other event blocks
* adds a few missing keys to the keyboard events: delete, backspace, left shift, right shift, left control, right control
* adds a `setCursorVisible` API that lets you hide the mouse cursor on the game screen
* adds a "repeat" event to the keyboard events along with a new block for setting the delay/interval (just like in controller)
* makes the keyboard events play nicely with push/pop scene. previously it only worked for the bottom scene
note that i added backspace, but i think backspace is mapped to the simulator restart by default so that needs to be remapped before people actually use it in their programs. i think we …
> address some bits of feedback on the browser events extension

- libs/browser-events/browserEvents.ts
- libs/browser-events/keyboard.ts
- libs/browser-events/sim/keyboard.ts
- libs/browser-events/sim/mouseState.ts
this fixes a bug reported on the forum here: https://forum.makecode.com/t/browser-events-extension-bug/35709
basically the bug worked like this:
1. someone presses a button and the simulator fires the pressed event
2. the game engine updates the pressed state of the button to true and invokes the user's button handler
3. the button handler pauses for some amount of time
4. the button is released and the simulator fires the released event
5. the game engine updates the pressed state of the button to false
6. the user presses the button a second time
7. because the button handler from step 3 is still paused, the pressed event is queued by the event bus
8. the button is released
9. the handler from step 3 finishes pausing and the queued event from step 7 is invoked
10. the game engine …
> fix queueing of browser events and handle scenes with the mouse

- libs/screen---st7735/screen.cpp
Fix for https://github.com/microsoft/pxt-arcade/issues/6904. Tested and working. Forgot to properly mask to keep previous bits alive.
> orientation fix 

- libs/game/game.ts
- libs/mixer/playable.ts
- libs/mixer/soundEffect.ts
fixes the two places where the mixer lib has a dependency on the game package, which it doesn't actually need and is preventing maker from building. i should have fixed this a while ago...
> Remove mixer libs dependencies on game package

- libs/base/math.ts
fixes https://github.com/microsoft/pxt-microbit/issues/4276
adds a math constants block with all the usual constants, but most importantly pi
we already have all of the trigonometric functions in the toolbox, and you really need PI for them to be useful.
> add a math constants block

- package.json
__Do not edit the PR title.__
It was automatically generated by `pxt bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
> [pxt-cli] bump version to v12.3.31
